### ISSUE TITLE
Crash when resuming from sleep mode

### ISSUE THREAD

**Issue by arza-zara** [The-Compiler/qutebrowser#1163]
Sometimes, when I resume from suspend-to-RAM, qutebrowser crashes immediately.
```
17:40:10 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
17:40:10 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
17:40:12 DEBUG    destroy    lineparser:_after_save:87 Saved to /home/user/.local/share/qutebrowser/cookies
[New Thread 0x7ffe577fe700 (LWP 32667)]

Program received signal SIGSEGV, Segmentation fault.
WTF::Vector<WebCore::FormDataElement, 0ul, WTF::CrashOnOverflow>::operator= (this=this@entry=0xc6ae170, other=...) at ../WTF/wtf/Vector.h:712
712     ../WTF/wtf/Vector.h: No such file or directory.

#0  WTF::Vector<WebCore::FormDataElement, 0ul, WTF::CrashOnOverflow>::operator= (this=this@entry=0xc6ae170, other=...)
    at ../WTF/wtf/Vector.h:712
No locals.
#1  0x00007fffe3adba5b in WebCore::FormDataIODevice::reset (this=0xc6ae160) at platform/network/qt/QNetworkReplyHandler.cpp:73
No locals.
#2  0x00007ffff1c44b13 in QNonContiguousByteDeviceIoDeviceImpl::reset (this=0xc378080) at io/qnoncontiguousbytedevice.cpp:368
        reset = <optimized out>
#3  0x00007fffe6c13390 in QNetworkReplyHttpImplPrivate::resetUploadDataSlot (this=0x435c1d0, r=0x7ffeb6adb827)
    at access/qnetworkreplyhttpimpl.cpp:1281
No locals.
#4  0x00007fffe6c9f07a in QNetworkReplyHttpImpl::qt_static_metacall (_o=0xc52ef40, _c=<optimized out>, _id=<optimized out>, _a=0x7ffeb6adb7f0)
    at .moc/moc_qnetworkreplyhttpimpl_p.cpp:254
        _t = 0xc52ef40
#5  0x00007ffff1d53ebf in QObject::event (this=0xc52ef40, e=<optimized out>) at kernel/qobject.cpp:1239
        mce = <optimized out>
        sw = {receiver = 0xc52ef40, previousSender = 0x0, currentSender = {sender = 0x26002d0, signal = 7, ref = 1}, switched = true}
#6  0x00007fffea8b0ad2 in QApplicationPrivate::notify_helper (this=this@entry=0x103f460, receiver=receiver@entry=0xc52ef40, 
    e=e@entry=0x7ffeb040bb10) at kernel/qapplication.cpp:3716
        consumed = <optimized out>
#7  0x00007fffea8b5dbe in QApplication::notify (this=0x103ba90, receiver=0xc52ef40, e=<optimized out>) at kernel/qapplication.cpp:3160
        res = false
#8  0x00007fffeb3518de in sipQApplication::notify (this=0x103ba90, a0=0xc52ef40, a1=0x7ffeb040bb10) at sipQtWidgetsQApplication.cpp:349
        sipGILState = PyGILState_LOCKED
        sipMeth = 0x0
#9  0x00007ffff1d21a9b in QCoreApplication::notifyInternal (this=0x103ba90, receiver=0xc52ef40, event=event@entry=0x7ffeb040bb10)
    at kernel/qcoreapplication.cpp:965
        result = false
        cbdata = {0xc52ef40, 0x7ffeb040bb10, 0x7fffffffd8bf}
        d = <optimized out>
        threadData = 0xbab180
        loopLevelCounter = {threadData = 0xbab180}
#10 0x00007ffff1d2415f in QCoreApplication::sendEvent (event=0x7ffeb040bb10, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:224
No locals.
#11 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0xbab180)
    at kernel/qcoreapplication.cpp:1593
        e = 0x7ffeb040bb10
        pe = <optimized out>
        r = <optimized out>
        unlocker = {m = <synthetic pointer>}
        event_deleter = {d = 0x7ffeb040bb10}
        locker = {val = 12235176}
        startOffset = 0
        i = @0xbab19c: 107
        cleanup = {receiver = 0x0, event_type = 0, data = 0xbab180, exceptionCaught = true}
#12 0x00007ffff1d2468c in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0)
    at kernel/qcoreapplication.cpp:1451
        data = <optimized out>
#13 0x00007ffff1d7c27a in postEventSourceDispatch (s=0x10916c0) at kernel/qeventdispatcher_glib.cpp:271
        source = 0x10916c0
#14 0x00007ffff36a7dc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#15 0x00007ffff36a8020 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#16 0x00007ffff36a80cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#17 0x00007ffff1d7c700 in QEventDispatcherGlib::processEvents (this=0x108f640, flags=...) at kernel/qeventdispatcher_glib.cpp:418
        d = 0x1090ee0
        canWait = true
        savedFlags = {i = 0}
        result = <optimized out>
#18 0x00007fffdd1f8bb5 in QPAEventDispatcherGlib::processEvents (this=<optimized out>, flags=...)
    at eventdispatchers/qeventdispatcher_glib.cpp:115
No locals.
#19 0x00007ffff1d1ef83 in QEventLoop::exec (this=this@entry=0x7fffffffdbf0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
        d = 0x13286f0
        locker = {val = 14677040}
        ref = {d = 0x13286f0, locker = @0x7fffffffdb70, exceptionCaught = true}
#20 0x00007ffff1d27796 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1229
        threadData = 0xbab180
        eventLoop = {<QObject> = {_vptr.QObject = 0x7ffff21654d8 <vtable for QEventLoop+16>, static staticMetaObject = {d = {superdata = 0x0, 
                stringdata = 0x7ffff1e83f60 <qt_meta_stringdata_QObject>, data = 0x7ffff1e83e40 <qt_meta_data_QObject>, 
                static_metacall = 0x7ffff1d5b480 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
                relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x13286f0}, static staticQtMetaObject = {d = {superdata = 0x0, 
                stringdata = 0x7ffff1ece0c0 <qt_meta_stringdata_Qt>, data = 0x7ffff1ecb6c0 <qt_meta_data_Qt>, static_metacall = 0x0, 
                relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {
              superdata = 0x7ffff215cb80 <QObject::staticMetaObject>, stringdata = 0x7ffff1ee3080 <qt_meta_stringdata_QEventLoop>, 
              data = 0x7ffff1ee3020 <qt_meta_data_QEventLoop>, 
              static_metacall = 0x7ffff1dd8a10 <QEventLoop::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
              relatedMetaObjects = 0x0, extradata = 0x0}}}
        returnCode = <optimized out>
#21 0x00007fffea0b2dec in QGuiApplication::exec () at kernel/qguiapplication.cpp:1527
No locals.
#22 0x00007fffea8ac274 in QApplication::exec () at kernel/qapplication.cpp:2976
No locals.
#23 0x00007fffeb354722 in meth_QApplication_exec_ (sipArgs=0x7ffff7f81048) at sipQtWidgetsQApplication.cpp:1503
        _save = 0x62a220
        sipRes = 32767
        sipParseErr = 0x0
#24 0x00007ffff79bd959 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#25 0x00007ffff7a3566c in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#26 0x00007ffff7a359bd in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#27 0x00007ffff7a359bd in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#28 0x00007ffff7a359bd in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#29 0x00007ffff7a36a62 in ?? () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#30 0x00007ffff7a36b43 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#31 0x00007ffff7a36b6b in PyEval_EvalCode () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#32 0x00007ffff7a2b0bd in ?? () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#33 0x00007ffff79bd959 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#34 0x00007ffff7a3566c in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#35 0x00007ffff7a36a62 in ?? () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#36 0x00007ffff7a33770 in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#37 0x00007ffff7a36a62 in ?? () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#38 0x00007ffff7a36b43 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#39 0x00007ffff79a0e78 in ?? () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#40 0x00007ffff797643a in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#41 0x00007ffff7a6df21 in ?? () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#42 0x00007ffff7a6e7fc in Py_Main () from /usr/lib/libpython3.5m.so.1.0
No symbol table info available.
#43 0x0000000000400af7 in main ()
No symbol table info available.
```

**Comment by The-Compiler** [comment]
This is some kind of upstream issue in QtWebKit - unfortunately, since QtWebKit is deprecated, I don't think it'll help much to report this upstream I'm afraid...

This will probably be better when there's a QtWebEngine backend (#666) if you're on a distribution which packes QtWebEngine.
