### ISSUE TITLE
AssertionError when starting with -c ""

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1169]
```
$ qutebrowser --debug -c ""
09:04:43 DEBUG    init       app:__init__:741 Qt arguments: ['/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py'], based on Namespace(basedir=None, cachedir=None, color=True, command=[], confdir='', datadir=None, debug=True, debug_exit=False, harfbuzz='auto', json_args=None, logfilter=None, loglevel='info', loglines=2000, no_err_windows=False, nowindow=False, override_restore=False, pdb_postmortem=False, qt_name=None, qt_qmljsdebugger=None, qt_reverse=None, qt_style=None, qt_stylesheet=None, qt_widgetcount=None, relaxed_config=False, session=None, target=None, temp_basedir=False, temp_settings=[], url=[], version=False)
[...]
09:04:44 DEBUG    init       app:_init_modules:411 Initializing websettings...
09:04:44 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 153, in main
    return app.run(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 110, in run
    init(args, crash_handler)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 137, in init
    _init_modules(args, crash_handler)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 412, in _init_modules
    websettings.init()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/websettings.py", line 421, in init
    value = config.get(sectname, optname)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 128, in get
    return objreg.get('config').get(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.4/functools.py", line 458, in wrapper
    result = user_function(*args, **kwds)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 666, in get
    newval = val.typ.transform(newval)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1262, in transform
    path = super().transform(value)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 901, in transform
    assert cfgdir is not None
AssertionError
```

**Comment by derlaft** [comment]
Are you still able to reproduce? No crash here

**Comment by The-Compiler** [comment]
Hm, indeed, works again! I definitely should have an end-to-end test for this though :wink:

**Comment by The-Compiler** [comment]
No, I can definitely reproduce this - I guess I had another instance open when I tried last time.
