### ISSUE TITLE
AssertionError in on_last_window_closed when saving session

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1238]
Got 4 reports about this.

- On v0.4.1, 2061080, 37022b8 and 83dc390.
- All with `general -> save-session` set to `true`.
- All on Qt 5.5.1.

# Reports

- I left my computer, came back after an hour or two, and it had crashed. First crash I've seen in my week or so of using qutebrowser.
- left browser open with no input for about five minutes
- Disconnected external monitor
- Disconnecting my thinkpad from docking station.
- nothing. I wasn't even near my computer

# Exception

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 464, in on_last_window_closed
    self.shutdown(last_window=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 598, in shutdown
    load_next_time=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/sessions.py", line 228, in save
    assert data is not None
AssertionError
```

This would mean `SessionManager.save_last_window_session` didn't get called before `on_last_window_closed`.

# Logs

```
16:22:56 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:22:56 DEBUG    keyboard   basekeyparser:_debug_log:107 No binding found for wake up.
16:22:56 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x10000b8 / text: ''
16:22:56 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
16:22:56 DEBUG    modes      modeman:_eventFilter_keypress:197 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=127 url='http://www.last.fm/user/fm4d/library'>)
16:22:56 DEBUG    misc       app:on_focus_object_changed:756 Focus object changed: None
16:23:03 DEBUG    destroy    app:shutdown:631 Shutting down with status 0, session None...
16:23:03 DEBUG    sessions   sessions:save:231 Saving session default to /home/fm4d/.local/share/qutebrowser/sessions/default.yml...
16:23:03 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
```

```
23:51:16 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
23:51:17 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
23:51:17 DEBUG    destroy    app:shutdown:631 Shutting down with status 0, session None...
23:51:17 DEBUG    sessions   sessions:save:231 Saving session default to /home/premysl/.local/share/qutebrowser/sessions/default.yml...
23:51:17 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
```

```
12:11:44 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
12:11:47 DEBUG    destroy    lineparser:_prepare_save:81 Saving to /home/peter/.local/share/qutebrowser/cookies
12:13:26 DEBUG    destroy    app:shutdown:590 Shutting down with status 0, session None...
12:13:26 DEBUG    sessions   sessions:save:225 Saving session default to /home/peter/.local/share/qutebrowser/sessions/default.yml...
12:13:26 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
```

```
01:23:46 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
01:23:52 DEBUG    destroy    lineparser:_prepare_save:81 Saving to /home/peter/.local/share/qutebrowser/cookies
01:26:46 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
01:26:52 DEBUG    destroy    lineparser:_prepare_save:81 Saving to /home/peter/.local/share/qutebrowser/cookies
01:27:37 DEBUG    destroy    app:shutdown:590 Shutting down with status 0, session None...
01:27:37 DEBUG    sessions   sessions:save:225 Saving session default to /home/peter/.local/share/qutebrowser/sessions/default.yml...
01:27:37 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 464, in on_last_window_closed
    self.shutdown(last_window=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 598, in shutdown
    load_next_time=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/sessions.py", line 228, in save
    assert data is not None
AssertionError
```

```
23:34:11 DEBUG    misc       app:on_focus_object_changed:767 Focus object changed: None
23:54:04 DEBUG    ipc        ipc:update_atime:374 Touching /tmp/runtime-xing/qutebrowser/ipc-866a6cafcf74ab3c2612a85626f1c706
23:54:24 DEBUG    destroy    app:shutdown:640 Shutting down with status 0, session None...
23:54:24 DEBUG    sessions   sessions:save:231 Saving session default to /home/xing/.local/share/qutebrowser/sessions/default.yml...
23:54:24 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/qutebrowser/app.py", line 484, in on_last_window_closed
    self.shutdown(last_window=True)
  File "/usr/lib64/python3.4/site-packages/qutebrowser/app.py", line 648, in shutdown
    load_next_time=True)
  File "/usr/lib64/python3.4/site-packages/qutebrowser/misc/sessions.py", line 234, in save
    assert data is not None
AssertionError
```

Those all have in common that a shutdown happened suddenly/unexpectedly...

**Comment by The-Compiler** [comment]
> > But I still have no idea what's going on. Do you have any idea if
> > something affected monitor geometry (docking/undocking, maybe even
> > going to standby) happened after those 20min?
> 
> I'm afraid I have no idea about the crashes. This crash happens frequently and
> often I'm not even at the computer. It's a desktop computer so there are no
> real hardware changes except for the occasional USB stick. They also occur
> irrespective of standby or anything else I can think of.
> 
> Sorry that I can't be of more help. I've been trying to work out a pattern
> behind the crashes ever since they started. It's certainly a bug that was
> introduced some time ago since this behaviour was not present before. Not sure
> what version introduced it but I'm quite certain version 0.4.1 didn't have it

**Comment by The-Compiler** [comment]
> I think it might have something to do with the screensaver. crashes usually
> happen, when i'm not at the computer. I don't have any special screensaver
> installed but i use xset to set the timeout. here are the relevant settings
> from my ~/.xinitrc:
> 
> xset s off
> xset +dpms
> xset dpms 600 600 600

**Comment by The-Compiler** [comment]
> Disconnected external monitor and changed screen resolution

**Comment by The-Compiler** [comment]
I can't reproduce this (even playing with docking/undocking, xrandr, dpms, etc.), but I added a workaround in a33aa524defa7605b1169b01f2ab6270c479f12b.
