### ISSUE TITLE
Deleted C++ object: DownloadManager in DownloadManager.remove_item

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1242]
With 8b76eb5 on Gentoo with Qt 5.5.1:

```
03:41:34 DEBUG    downloads  downloads:fetch:844 fetch: PyQt5.QtCore.QUrl('http://www.mathe-online.at/materialien/hannah.theil/files/Testpfad/Uebungsblatt9_Schnittgerade_von_zwei_Ebenen.pdf') -> Uebungsblatt9_Schnittgerade_von_zwei_Ebenen.pdf
03:41:34 DEBUG    downloads  downloads:set_filename:540 Setting filename to /home/chris/Downloads/tmp
03:41:34 DEBUG    downloads  downloads:set_fileobj:567 buffer: 0 bytes
03:41:34 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=4 url=''>: LoadStatus.success
03:41:34 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('success') (tab 0)
03:41:34 DEBUG    webview    tabbedbrowser:on_title_changed:483 Ignoring title change to ''.
03:41:34 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(False) (tab 0)
03:41:35 DEBUG    downloads  downloads:on_reply_finished:614 Reply finished, fileobj <_io.BufferedWriter name='/home/chris/Downloads/tmp/Uebungsblatt9_Schnittgerade_von_zwei_Ebenen.pdf'>
03:41:35 DEBUG    downloads  downloads:finish_download:585 Finishing download...
03:41:35 DEBUG    downloads  downloads:finish_download:596 Download finished
03:41:39 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
03:41:39 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
03:41:39 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x1000022 / text: ''
03:41:39 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
03:41:39 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=4 url=''>)
03:41:39 DEBUG    misc       app:on_focus_object_changed:756 Focus object changed: None
03:41:39 DEBUG    destroy    mainwindow:_do_close:406 Closing window 4
03:41:39 DEBUG    destroy    webview:shutdown:332 Shutting down <qutebrowser.browser.webview.WebView tab_id=4 url=''>.
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 4
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 4
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: main-window
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: message-bridge
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: download-manager
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: statusbar
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: prompt
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: status-command
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: tabbed-browser
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: completion
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: completer
03:41:39 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: mode-manager
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: 4
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: 4
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: main-window
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: message-bridge
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: download-manager
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: statusbar
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: prompt
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: status-command
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: tabbed-browser
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: completion
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: completer
03:41:39 DEBUG    destroy    objreg:_on_destroyed:123 removed: mode-manager
03:41:39 DEBUG    misc       app:on_focus_object_changed:756 Focus object changed: <qutebrowser.browser.webview.WebView tab_id=3 url='http://www.mathe-online.at/lernpfade/testpfad_hannah/?kapitel=2'>
03:41:39 DEBUG    misc       app:on_focus_object_changed:756 Focus object changed: <qutebrowser.browser.webview.WebView tab_id=3 url='http://www.mathe-online.at/lernpfade/testpfad_hannah/?kapitel=2'>
03:41:39 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/qutebrowser/browser/downloads.py", line 1095, in remove_item
    self.beginRemoveRows(QModelIndex(), idx, idx)
RuntimeError: wrapped C/C++ object of type DownloadManager has been deleted
```

**Comment by The-Compiler** [comment]
Another one on v0.5.1:

> Just closed metroforsteam.com after downloading a zip, my local plexmediaserver was the only other tab open (and it wasn't playing anything)

```
22:31:08 DEBUG    webview    webpage:acceptNavigationRequest:583 acceptNavigationRequest, url http://metroforsteam.com/downloads/4.0.4.zip, type NavigationTypeLinkClicked, hint target None, open_target ClickTarget.normal
[...]
22:31:08 DEBUG    downloads  downloads:fetch:844 fetch: PyQt5.QtCore.QUrl('http://metroforsteam.com/downloads/4.0.4.zip') -> 4.0.4.zip
[...]
22:31:10 DEBUG    downloads  downloads:set_filename:540 Setting filename to /home/Link/Downloads/
22:31:10 DEBUG    downloads  downloads:set_fileobj:567 buffer: 1024 bytes
22:31:10 DEBUG    downloads  downloads:on_reply_finished:614 Reply finished, fileobj <_io.BufferedWriter name='/home/Link/Downloads/4.0.4.zip'>
22:31:10 DEBUG    downloads  downloads:finish_download:585 Finishing download...
22:31:10 DEBUG    downloads  downloads:finish_download:596 Download finished
[...]
22:31:12 DEBUG    commands   command:run:490 command called: tab-close
[...]
22:31:12 DEBUG    destroy    objreg:_on_destroyed:123 removed: 6
[...]
22:31:12 DEBUG    destroy    objreg:_on_destroyed:123 removed: download-manager
[...]
22:31:19 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 1095, in remove_item
    self.beginRemoveRows(QModelIndex(), idx, idx)
RuntimeError: wrapped C/C++ object of type DownloadManager has been deleted
```

**Comment by The-Compiler** [comment]
I can now reproduce this:

- Set `ui -> remove-finished-downloads` to 2000
- Open a new window
- Start a download and wait for it to be finished
- Close the window
- Exception when the delay is over and the download should get removed
