### ISSUE TITLE
text is None in DownloadManager.ask_for_filename -> utils.force_encoding

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1243]
On v0.5.0:

```
21:16:07 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 1 to 'https://kat.cr/desperados-wanted-dead-or-alive-gog-t9671892.html'
[...]
21:16:09 DEBUG    misc       webelem:is_editable:261 Checking if element is editable: <qutebrowser.browser.webelem.WebElementWrapper html='<i class="ka ka-magnet"></i>'>
[...]
21:16:09 DEBUG    mouse      webview:_mousepress_opentarget:325 Normal click, setting normal target
21:16:09 DEBUG    misc       app:on_focus_object_changed:756 Focus object changed: <PyQt5.QtWidgets.QMenu object at 0x7f5a1954e948>
21:16:09 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=11 url='https://kat.cr/desperados-wanted-dead-or-alive-gog-t9671892.html'>: LoadStatus.success_https
[...]
21:16:11 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/webpage.py", line 290, in on_download_requested
    download_manager.get_request(req, page=self)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 783, in get_request
    prompt_download_directory=prompt_download_directory
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 146, in ask_for_filename
    encoding)
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/utils.py", line 705, in force_encoding
    return text.encode(encoding, errors='replace').decode(encoding)
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by The-Compiler** [comment]
This might be the same issue:

```
16:28:35 DEBUG    downloads  downloads:fetch:789 fetch: PyQt5.QtCore.QUrl('https://my.owndrive.com/index.php/apps/files/ajax/download.php?dir=%2FfotoNZ%2FAuckland&files=%5B%22img_20150801_064023.jpg%22%2C%22img_20150801_214429.jpg%22%2C%2211896197_10156135352470413_5658012712417815962_n.jpg%22%5D') -> Auckland.zip
16:28:35 DEBUG    statusbar  prompter:ask_question:304 Asking question <qutebrowser.utils.usertypes.Question default='"/home/esse/var/dnl" /' mode=<PromptMode.text: 2> text='Save file to:'>, blocking False, loops [], queue deque([])
[...]
16:28:51 DEBUG    commands   command:run:490 command called: prompt-accept
[...]
16:28:51 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/esse/opt/git/qutebrowser/qutebrowser/browser/downloads.py", line 461, in set_filename
    _last_used_directory = os.path.dirname(self._filename)
  File "/home/esse/opt/git/qutebrowser/.venv/lib/python3.4/posixpath.py", line 148, in dirname
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by The-Compiler** [comment]
Another similar one on v0.4.0:

> Crashed when tried to save a downloaded file on a network folder (NAS)

```
15:48:24 DEBUG    webview    webpage:acceptNavigationRequest:559 acceptNavigationRequest, url http://filehippo.com/download_ccleaner/download/946bb16ff8ce0569a852f4929a4b0e80/, type NavigationTypeLinkClicked, hint target ClickTarget.normal, open_target ClickTarget.normal
[...]
15:48:28 DEBUG    downloads  downloads:fetch:789 fetch: PyQt5.QtCore.QUrl('http://fs30.filehippo.com/1098/ec620925088c4ba8a382745b871ff34b/ccsetup509.exe') -> ccsetup509.exe
15:48:28 DEBUG    statusbar  prompter:ask_question:304 Asking question <qutebrowser.utils.usertypes.Question default='\\\\NSA\\download' mode=<PromptMode.text: 2> text='Save file to:'>, blocking False, loops [], queue deque([])
[...]
15:48:28 DEBUG    webview    webview:_set_load_status:181 load status for <qutebrowser.browser.webview.WebView tab_id=0 url='http://filehippo.com/download_ccleaner/download/9…'>: LoadStatus.success
[...]
15:48:35 DEBUG    downloads  downloads:on_reply_finished:556 Reply finished, fileobj None
[...]
15:48:46 DEBUG    commands   command:run:490 command called: prompt-accept
15:48:46 DEBUG    commands   command:run:504 Calling qutebrowser.mainwindow.statusbar.prompter.Prompter.prompt_accept(<qutebrowser.mainwindow.statusbar.prompter.Prompter busy=True loops=0 question=<qutebrowser.utils.usertypes.Question default='\\\\NSA\\download' mode=<PromptMode.text: 2> text='Save file to:'> queue=…)
[...]
15:48:46 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "scripts/dev\..\..\scripts\..\qutebrowser\browser\downloads.py", line 461, in set_filename
  File "c:\Python\64-bit\3.4\lib\ntpath.py", line 253, in dirname
  File "c:\Python\64-bit\3.4\lib\ntpath.py", line 217, in split
  File "c:\Python\64-bit\3.4\lib\ntpath.py", line 159, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

**Comment by The-Compiler** [comment]
I can reproduce the original issue by doing a right-click on magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&dn and selecting "save link".
