### ISSUE TITLE
Crash when opening second instance when config error is shown

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1246]
With `storage -> download-directory` set to `/does/not/exist` and starting a second instance while the first one displays the config error:

```
16:59:32 ERROR    init       config:_init_main_config:148 Invalid value '/does/not/exist' - must be a valid directory!
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 146, in _init_main_config
    relaxed=args.relaxed_config)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 578, in read
    self._validate_all()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 537, in _validate_all
    opt.typ.validate(interpolated)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 954, in validate
    value, "must be a valid directory!")
qutebrowser.config.configexc.ValidationError: Invalid value '/does/not/exist' - must be a valid directory!
[...]
16:59:35 DEBUG    ipc        ipc:handle_connection:252 Client connected (socket 0x7efd354718b8).
16:59:35 DEBUG    ipc        ipc:on_ready_read:304 Read from socket 0x7efd354718b8: b'{"target_arg": null, "args": [], "cwd": "/home/florian/proj/qutebrowser/git", "protocol_version": 1, "version": "0.5.0"}\n'
16:59:35 DEBUG    ipc        ipc:on_ready_read:314 Processing: {"target_arg": null, "args": [], "cwd": "/home/florian/proj/qutebrowser/git", "protocol_version": 1, "version": "0.5.0"}

16:59:35 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 146, in _init_main_config
    relaxed=args.relaxed_config)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 578, in read
    self._validate_all()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 537, in _validate_all
    opt.typ.validate(interpolated)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 954, in validate
    value, "must be a valid directory!")
qutebrowser.config.configexc.ValidationError: Invalid value '/does/not/exist' - must be a valid directory!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 108, in <lambda>
    target_arg=target_arg))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 252, in process_pos_args
    win_id = mainwindow.get_window(via_ipc, force_window=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 63, in get_window
    open_target = config.get('general', 'new-instance-open-target')
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 128, in get
    return objreg.get('config').get(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 217, in get
    return reg[name]
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.4/collections/__init__.py", line 884, in __getitem__
    raise KeyError(key)
KeyError: 'config'
```

**Comment by The-Compiler** [comment]
Still an issue with the new config:

```
20:07:31 ERROR: Error while loading config.py
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configinit.py", line 61, in early_init
    configfiles.read_config_py(config_file)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configfiles.py", line 291, in read_config_py
    raise configexc.ConfigFileErrors('config.py', api.errors)
qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py:
  Unhandled exception: name 'foo' is not defined



20:07:35 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 116, in <lambda>
    target_arg=target_arg))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 260, in process_pos_args
    win_id = mainwindow.get_window(via_ipc, force_window=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 83, in get_window
    window = MainWindow(private=None)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 168, in __init__
    self._init_downloadmanager()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 295, in _init_downloadmanager
    self.win_id, self)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/qtnetworkdownloads.py", line 375, in __init__
    private=config.val.content.private_browsing, parent=self)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webkit/network/networkmanager.py", line 156, in __init__
    self._set_cookiejar()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webkit/network/networkmanager.py", line 170, in _set_cookiejar
    cookie_jar = objreg.get('cookie-jar')
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 229, in get
    return reg[name]
  File "/usr/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: 'cookie-jar'
20:07:35 ERROR: Error while recovering pages: 'tabbed-browser'
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/crashsignal.py", line 184, in _get_exception_info
    pages = self._recover_pages(forgiving=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/crashsignal.py", line 124, in _recover_pages
    window=win_id)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 229, in get
    return reg[name]
  File "/usr/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: 'tabbed-browser'
20:07:35 ERROR: Error while getting history: 'command-history'
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/crashsignal.py", line 190, in _get_exception_info
    cmd_history = objreg.get('command-history')[-5:]
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 229, in get
    return reg[name]
  File "/usr/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: 'command-history'
```

**Comment by The-Compiler** [comment]
This changed slightly with v1.14.0 / 4cd255c7372625b4c3a630844ffd2b42d6ddde58:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 335, in last_focused_window
    window = get('last-focused-main-window')
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 247, in get
    return reg[name]
  File "/usr/lib/python3.8/collections/__init__.py", line 1010, in __getitem__
    raise KeyError(key)
KeyError: 'last-focused-main-window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 122, in <lambda>
    process_pos_args(args, cwd=cwd, via_ipc=True,
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 290, in process_pos_args
    win_id = open_url(url, target=open_target, via_ipc=via_ipc)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 307, in open_url
    win_id = mainwindow.get_window(via_ipc=via_ipc, target=target,
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 72, in get_window
    window = get_target_window()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 116, in get_target_window
    return getter()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 337, in last_focused_window
    return last_opened_window()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 357, in last_opened_window
    raise utils.Unreachable()
qutebrowser.utils.utils.Unreachable
```

That was an accident - will change back to the old exception for v1.14.1. Still haven't figured out how to best fix the real issue for this one yet... if I'm reading things right (from a very quick look), what happens is:

- We search a window in `get_target_window` for the link we got via IPC
- No window is open yet, so we return `None`
- Thus, we want to open a new window as target
- But we didn't fully initialize yet, so that fails
