### ISSUE TITLE
self._filename is None in set_filename

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1269]
Extracted from #1243:

---

This might be the same issue (on 294eb19):

```
16:28:35 DEBUG    downloads  downloads:fetch:789 fetch: PyQt5.QtCore.QUrl('https://my.owndrive.com/index.php/apps/files/ajax/download.php?dir=%2FfotoNZ%2FAuckland&files=%5B%22img_20150801_064023.jpg%22%2C%22img_20150801_214429.jpg%22%2C%2211896197_10156135352470413_5658012712417815962_n.jpg%22%5D') -> Auckland.zip
16:28:35 DEBUG    statusbar  prompter:ask_question:304 Asking question <qutebrowser.utils.usertypes.Question default='"/home/esse/var/dnl" /' mode=<PromptMode.text: 2> text='Save file to:'>, blocking False, loops [], queue deque([])
[...]
16:28:51 DEBUG    commands   command:run:490 command called: prompt-accept
[...]
16:28:51 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/esse/opt/git/qutebrowser/qutebrowser/browser/downloads.py", line 461, in set_filename
    _last_used_directory = os.path.dirname(self._filename)
  File "/home/esse/opt/git/qutebrowser/.venv/lib/python3.4/posixpath.py", line 148, in dirname
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

---

Another similar one on v0.4.0:

> Crashed when tried to save a downloaded file on a network folder (NAS)

```
15:48:24 DEBUG    webview    webpage:acceptNavigationRequest:559 acceptNavigationRequest, url http://filehippo.com/download_ccleaner/download/946bb16ff8ce0569a852f4929a4b0e80/, type NavigationTypeLinkClicked, hint target ClickTarget.normal, open_target ClickTarget.normal
[...]
15:48:28 DEBUG    downloads  downloads:fetch:789 fetch: PyQt5.QtCore.QUrl('http://fs30.filehippo.com/1098/ec620925088c4ba8a382745b871ff34b/ccsetup509.exe') -> ccsetup509.exe
15:48:28 DEBUG    statusbar  prompter:ask_question:304 Asking question <qutebrowser.utils.usertypes.Question default='\\\\NSA\\download' mode=<PromptMode.text: 2> text='Save file to:'>, blocking False, loops [], queue deque([])
[...]
15:48:28 DEBUG    webview    webview:_set_load_status:181 load status for <qutebrowser.browser.webview.WebView tab_id=0 url='http://filehippo.com/download_ccleaner/download/9…'>: LoadStatus.success
[...]
15:48:35 DEBUG    downloads  downloads:on_reply_finished:556 Reply finished, fileobj None
[...]
15:48:46 DEBUG    commands   command:run:490 command called: prompt-accept
15:48:46 DEBUG    commands   command:run:504 Calling qutebrowser.mainwindow.statusbar.prompter.Prompter.prompt_accept(<qutebrowser.mainwindow.statusbar.prompter.Prompter busy=True loops=0 question=<qutebrowser.utils.usertypes.Question default='\\\\NSA\\download' mode=<PromptMode.text: 2> text='Save file to:'> queue=…)
[...]
15:48:46 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "scripts/dev\..\..\scripts\..\qutebrowser\browser\downloads.py", line 461, in set_filename
  File "c:\Python\64-bit\3.4\lib\ntpath.py", line 253, in dirname
  File "c:\Python\64-bit\3.4\lib\ntpath.py", line 217, in split
  File "c:\Python\64-bit\3.4\lib\ntpath.py", line 159, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

**Comment by Kingdread** [comment]
I can reproduce it on the latest master version and I believe that it's the same issue as #866.

Steps to reproduce:
* Set a non-absolute path as XDG_DOWNLOAD_DIR in `~/.config/user-dirs.dirs`, e.g. `XDG_DOWNLOAD_DIR="foo/bar"`
* set `storage -> download-directory` to `""`
* don't use `--temp-basedir`, as this will overwrite the `XDG_DOWNLOAD_DIR` value (at least I believe so, correct me if I'm wrong)
* Try to download a file with qutebrowser. For the filename, specify a non-absolute path (e.g. just `download`)
* qute will crash

The thing is that we never get an absolute path, since 1. the filename is not absolute and 2. the joined path of `download_dir()` and the filename is not absolute, but we never check for the second case, as we assume that we get a correct path on the second try (see [this part](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/downloads.py#L529-L535))

We should probably check for `None` again and display some error, as there is on sensible default and a non-absolute value in `XDG_DOWNLOAD_DIR` is invalid anyway:

> All paths set in these environment variables must be absolute. If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.

*(cf. the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.8.html#basics))*
