### ISSUE TITLE
qutebrowser freezes on certain sites

### ISSUE THREAD

**Issue by martynjy** [The-Compiler/qutebrowser#1289]
qutebrowser 0.5.1-1

When trying to play radio streams on certain sites qutebrowser freezes requiring sigkill.  Just a few example sites:

http://www.pri.org/
http://birdsong.fm/
http://tunein.com/
http://www.radionomy.com/
http://www.shoutcast.com/

Some sites freeze on loading but most load then freeze when I press the play stream button.  These and other sites play fine in Chromium and Midori!

**Comment by The-Compiler** [comment]
I'm guessing you're running into [QTBUG-43668](https://bugreports.qt.io/browse/QTBUG-43668).

Can you try to run something like `gdb $(which python3) -ex 'run -m qutebrowser --debug --temp-basedir`, and when it freezes, hit `Ctrl-C` in the gdb shell, run `bt`, and show the stacktrace and log output (if anything looks relevant)?

**Comment by pineman** [comment]
I can reproduce this issue.
Here's the stacktrace as asked.
I was on [http://www.radionomy.com](url) and tried to play a radio stream.
```
#1  0x00007ffff4646dbc in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007fffe5843d54 in gst_object_get_parent () from /usr/lib/libgstreamer-1.0.so.0
#3  0x00007fffe5843dd2 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#4  0x00007fffed7659d1 in g_object_notify () from /usr/lib/libgobject-2.0.so.0
#5  0x00007fffe74b4827 in ?? () from /usr/lib/libQt5WebKit.so.5
#6  0x00007fffe714c893 in ?? () from /usr/lib/libQt5WebKit.so.5
#7  0x00007fffe71a7608 in ?? () from /usr/lib/libQt5WebKit.so.5
#8  0x00007fffe73cf53c in ?? () from /usr/lib/libQt5WebKit.so.5
#9  0x00007fffe73d01aa in ?? () from /usr/lib/libQt5WebKit.so.5
#10 0x00007fffe73d0b08 in ?? () from /usr/lib/libQt5WebKit.so.5
#11 0x00007fffe73d0d8c in ?? () from /usr/lib/libQt5WebKit.so.5
#12 0x00007ffff5b8d31a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#13 0x00007fffe937c636 in ?? () from /usr/lib/libQt5Network.so.5
#14 0x00007fffe93fd44b in ?? () from /usr/lib/libQt5Network.so.5
#15 0x00007ffff5b8e1e1 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#16 0x00007fffee0459ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007fffee04ae86 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007fffee91609e in ?? () from /usr/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#19 0x00007ffff5b5ebab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff5b60fa6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#21 0x00007ffff5bb5143 in ?? () from /usr/lib/libQt5Core.so.5
#22 0x00007ffff4602dc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#23 0x00007ffff4603020 in ?? () from /usr/lib/libglib-2.0.so.0
#24 0x00007ffff46030cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#25 0x00007ffff5bb556b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff5b5c57a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#27 0x00007ffff5b6453c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#28 0x00007fffee9149db in ?? () from /usr/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#29 0x00007ffff79bca89 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#30 0x00007ffff7a34a01 in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#31 0x00007ffff7a34d52 in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#32 0x00007ffff7a34d52 in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#33 0x00007ffff7a34d52 in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#34 0x00007ffff7a35df2 in ?? () from /usr/lib/libpython3.5m.so.1.0
#35 0x00007ffff7a35ed3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
#36 0x00007ffff7a35efb in PyEval_EvalCode () from /usr/lib/libpython3.5m.so.1.0
#37 0x00007ffff7a2a43d in ?? () from /usr/lib/libpython3.5m.so.1.0
#38 0x00007ffff79bca89 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#39 0x00007ffff7a34a01 in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#40 0x00007ffff7a35df2 in ?? () from /usr/lib/libpython3.5m.so.1.0
#41 0x00007ffff7a32af0 in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#42 0x00007ffff7a35df2 in ?? () from /usr/lib/libpython3.5m.so.1.0
#43 0x00007ffff7a35ed3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
#44 0x00007ffff799ffe8 in ?? () from /usr/lib/libpython3.5m.so.1.0
#45 0x00007ffff79754ca in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
#46 0x00007ffff7a6d311 in ?? () from /usr/lib/libpython3.5m.so.1.0
#47 0x00007ffff7a6dbec in Py_Main () from /usr/lib/libpython3.5m.so.1.0
#48 0x0000000000400af7 in main ()
```

**Comment by The-Compiler** [comment]
Yeah, looks like that bug. I can't fix this in Qt/GStreamer myself, so there really isn't much I can do here I'm afraid... It'll probably go away when using the QtWebEngine backend (#666) in the future.
