### ISSUE TITLE
Unhandled no space left on device error from Saveable

### ISSUE THREAD

**Issue by toofar** [The-Compiler/qutebrowser#1371]
I would rather have it spit out errors than crash. Not sure about wether to clear the dirty flag or to print the whole stack trace or not. The errors I got for session autosave were:

    qutebrowser.utils.qtutils.QtOSError: No space left on device
    qutebrowser.misc.sessions.SessionError: No space left on device
    qutebrowser.commands.cmdexc.CommandError: Error while saving session: No space left on device

I just set it to print the whole stack trace so I know what exception actuall happened.

    diff --git i/qutebrowser/misc/savemanager.py w/qutebrowser/misc/savemanager.py
    index c2e1fea5aaea..0e99b2041396 100644
    --- i/qutebrowser/misc/savemanager.py
    +++ w/qutebrowser/misc/savemanager.py
    @@ -97,7 +99,10 @@ class Saveable:
                                    self._name, self._dirty, self._save_on_exit,
                                    is_exit, force, do_save))
             if do_save:
    -            self._save_handler()
    +            try:
    +                self._save_handler()
    +            except Exception as e:
    +                log.save.exception("Save of {} failed".format(self._name))
                 self._dirty = False

**Comment by The-Compiler** [comment]
Can you show the full stacktraces? Would be interesting where they are coming from exactly.

**Comment by toofar** [comment]
This is for autosaving of sessions that I have patched into my local copy but i imagine it would be the same for history and cookies:

    Traceback (most recent call last):
      File "~/projects/qutebrowser/qutebrowser/misc/sessions.py", line 241, in save
        encoding='utf-8', allow_unicode=True)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/__init__.py", line 200, in dump
        return dump_all([data], stream, Dumper=Dumper, **kwds)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/__init__.py", line 188, in dump_all
        dumper.represent(data)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/representer.py", line 27, in represent
        self.serialize(node)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 54, in serialize
        self.serialize_node(node, None, None)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 108, in serialize_node
        self.serialize_node(value, node, key)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 98, in serialize_node
        self.serialize_node(item, node, index)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 108, in serialize_node
        self.serialize_node(value, node, key)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 98, in serialize_node
        self.serialize_node(item, node, index)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 108, in serialize_node
        self.serialize_node(value, node, key)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 98, in serialize_node
        self.serialize_node(item, node, index)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 107, in serialize_node
        self.serialize_node(key, node, None)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/serializer.py", line 90, in serialize_node
        style=node.style))
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/emitter.py", line 115, in emit
        self.state()
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/emitter.py", line 412, in expect_block_mapping_simple_value
        self.expect_node(mapping=True)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/emitter.py", line 244, in expect_node
        self.expect_scalar()
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/emitter.py", line 268, in expect_scalar
        self.process_scalar()
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/emitter.py", line 533, in process_scalar
        self.write_plain(self.analysis.scalar, split)
      File "~/projects/qutebrowser/.venv/lib/python3.5/site-packages/yaml/emitter.py", line 1131, in write_plain
        self.stream.write(data)
      File "~/projects/qutebrowser/qutebrowser/utils/qtutils.py", line 368, in write
        raise QtOSError(self.dev)
    qutebrowser.utils.qtutils.QtOSError: No space left on device
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "~/projects/qutebrowser/qutebrowser/misc/sessions.py", line 409, in session_save
        name = self.save(name)
      File "~/projects/qutebrowser/qutebrowser/misc/sessions.py", line 243, in save
        raise SessionError(e)
    qutebrowser.misc.sessions.SessionError: No space left on device
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "~/projects/qutebrowser/qutebrowser/misc/savemanager.py", line 184, in autosave
        saveable.save(silent=True)
      File "~/projects/qutebrowser/qutebrowser/misc/savemanager.py", line 102, in save
        self._save_handler()
      File "~/projects/qutebrowser/qutebrowser/misc/sessions.py", line 412, in session_save
        .format(e))
    qutebrowser.commands.cmdexc.CommandError: Error while saving session: No space left on device

Actually here is one for history after I added that try/except:

    Traceback (most recent call last):
      File "~/projects/qutebrowser/qutebrowser/misc/lineparser.py", line 106, in _open
        yield f
      File "~/projects/qutebrowser/qutebrowser/misc/lineparser.py", line 190, in save
        self._write(f, self.new_data)
      File "~/projects/qutebrowser/qutebrowser/misc/lineparser.py", line 123, in _write
        fp.flush()
    OSError: [Errno 28] No space left on device
    
    During handling of the above exception, another exception occurred:
    
    OSError: [Errno 28] No space left on device
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "~/projects/qutebrowser/qutebrowser/misc/savemanager.py", line 103, in save
        self._save_handler()
      File "~/projects/qutebrowser/qutebrowser/browser/history.py", line 173, in save
        self._lineparser.save()
      File "~/projects/qutebrowser/qutebrowser/misc/lineparser.py", line 190, in save
        self._write(f, self.new_data)
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "~/projects/qutebrowser/qutebrowser/misc/lineparser.py", line 106, in _open
        yield f
    OSError: [Errno 28] No space left on device

**Comment by The-Compiler** [comment]
Somewhat similarily, when writing the key config fails:

```
13:47:03 DEBUG    save       savemanager:save:98 Save of key-config requested - dirty True, save_on_exit False, is_exit False, force False -> True
13:47:03 DEBUG    destroy    keyconf:save:148 Saving key config to C:\Users\nisom\AppData\Local\qutebrowser\keys.conf
13:47:03 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "scripts/dev\..\..\scripts\..\qutebrowser\misc\savemanager.py", line 100, in save
  File "scripts/dev\..\..\scripts\..\qutebrowser\config\parsers\keyconf.py", line 151, in save
  File "c:\Python\64-bit\3.4\lib\contextlib.py", line 66, in __exit__
  File "scripts/dev\..\..\scripts\..\qutebrowser\utils\qtutils.py", line 219, in savefile_open
qutebrowser.utils.qtutils.QtOSError: Commit failed!
```

**Comment by toofar** [comment]
I think this can be closed.

* The first trace was caused be me using a command handler as a saveable (whoops), so the OSError was getting swallowed and replaced with a CommandError, 
* The second one is handled fine already (I tested with the bookmark saveables
  which also uses lineparser). I guess I got confused from seeing that
  stacktrace because the only reason I saw it is that I caught the exception
  before it got to the place that it was normally caught.
* The third one I'm less sure about, but it doesn't look like it is from an
  autosave, a QtOSError there definitely should have been caught. Anyway,
  keyconf isn't a thing anymore.
