### ISSUE TITLE
Error during installation when trying to install all needed Python dependencies in a .venv subfolder

### ISSUE THREAD

**Issue by alanrussel** [The-Compiler/qutebrowser#1377]
Hello,
I am trying to install qutebrowser on ubuntu 15.10 wily. When running tox inside the qutebrowser repository to set up a virtual environment ( $ tox -e mkvenv ) I get the following error message:

```
mkvenv create: /home/ich/qutebrowser/.venv
ERROR: invocation failed (exit code 1), logfile: /home/ich/qutebrowser/.venv/log/mkvenv-0.log
ERROR: actionid: mkvenv
msg: getenv
cmdargs: ['/home/ich/anaconda3/bin/python3', '-m', 'virtualenv', '--python', '/home/ich/anaconda3/bin/python3', '.venv']
env: {'_': '/home/ich/anaconda3/bin/tox', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'PATH': '/home/ich/qutebrowser/.venv/bin:/home/ich/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'XDG_SESSION_TYPE': 'x11', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_CURRENT_DESKTOP': 'Unity', 'VIRTUAL_ENV':
'/home/ich/qutebrowser/.venv', 'XMODIFIERS': '@im=ibus', 'PYTHONHASHSEED': '1414026005', 'UPSTART_INSTANCE': '', 'HOME': '/home/ich', 'INSTANCE': '', 'SHLVL': '1', 'QT_IM_MODULE': 'ibus', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'XDG_SEAT': 'seat0', 'LOGNAME': 'ich', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/', 'VTE_VERSION': '4002', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'GDMSESSION': 'ubuntu', 'XDG_SESSION_ID':
'c2', 'PWD': '/home/ich/qutebrowser', 'UPSTART_EVENTS': 'xsession started', 'IM_CONFIG_PHASE': '1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-sK6g1yi8VH', 'DISPLAY': ':0', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/ich', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/home/ich/qutebrowser/.venv/Lib/site-packages/PyQt5/plugins/platforms', 'SESSION': 'ubuntu', 'GDM_LANG': 'en_US', 'XDG_CONFIG_DIRS':
'/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'USER': 'ich', 'GTK2_MODULES': 'overlay-scrollbar', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/1051', 'WINDOWID': '73400330', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'GNOME_KEYRING_CONTROL': '', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'CLUTTER_IM_MODULE': 'xim', 'PYTEST_QT_API': 'pyqt5', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'GTK_MODULES': 'unity-gtk-module',
'LANG': 'en_US.UTF-8', 'COMPIZ_BIN_PATH': '/usr/bin/', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'JOB': 'unity-settings-daemon', 'UPSTART_JOB': 'unity7', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XDG_VTNR': '7', 'GPG_AGENT_INFO': '/tmp/gpg-e5F0tT/S.gpg-agent:1172:1', 'QT4_IM_MODULE': 'xim', 'SESSIONTYPE': 'gnome-session', 'XAUTHORITY': '/home/ich/.Xauthority', 'DESKTOP_SESSION': 'ubuntu', 'XDG_SESSION_DESKTOP': 'ubuntu', 'LESSCLOSE':
'/usr/bin/lesspipe %s %s', 'LANGUAGE': 'en_US', 'GNOME_KEYRING_PID': '', 'OLDPWD': '/home/ich', 'GTK_IM_MODULE': 'ibus', 'LS_COLORS':
'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'}

Already using interpreter /home/ich/anaconda3/bin/python3
Using base prefix '/home/ich/anaconda3'
New python executable in /home/ich/qutebrowser/.venv/bin/python3
Also creating executable in /home/ich/qutebrowser/.venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/ich/qutebrowser/.venv/bin/python3 - setuptools pip wheel:
    Traceback (most recent call last):
      File "<stdin>", line 7, in <module>
        File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
          File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
            File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
              File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
                File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 18, in <module>
                  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
                    File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
                      File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
                        File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
                          File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/commands/__init__.py", line 6, in <module>
                            File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
                              File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
                                File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
                                  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
                                    File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/commands/completion.py", line 4, in <module>
                                      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
                                        File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
                                          File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
                                            File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
                                              File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/basecommand.py", line 19, in <module>
                                                File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
                                                  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
                                                    File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
                                                      File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
                                                        File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/req/__init__.py", line 3, in <module>
                                                          File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
                                                            File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
                                                              File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
                                                                File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
                                                                  File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/req/req_install.py", line 18, in <module>
                                                                    File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
                                                                      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
                                                                        File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
                                                                          File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
                                                                            File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/_vendor/distlib/markers.py", line 20, in <module>
                                                                              File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/_vendor/distlib/markers.py", line 48, in Evaluator
                                                                                File "/home/ich/anaconda3/lib/python3.4/platform.py", line 1319, in python_implementation
                                                                                    return _sys_version()[0]
                                                                                      File "/home/ich/anaconda3/lib/python3.4/platform.py", line 1282, in _sys_version
                                                                                          repr(sys_version))
                                                                                          ValueError: failed to parse CPython sys.version: '3.4.3+ (default, Oct 14 2015, 16:03:50) \n[GCC 5.2.1 20151010]'
                                                                                          ----------------------------------------
                                                                                          ...Installing setuptools, pip, wheel...done.
                                                                                          Traceback (most recent call last):
                                                                                            File "/home/ich/anaconda3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
                                                                                                "__main__", mod_spec)
                                                                                                  File "/home/ich/anaconda3/lib/python3.4/runpy.py", line 85, in _run_code
                                                                                                      exec(code, run_globals)
                                                                                                        File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 2316, in <module>
                                                                                                            main()
                                                                                                              File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 708, in main
                                                                                                                  symlink=options.symlink)
                                                                                                                    File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 941, in create_environment
                                                                                                                        download=download,
                                                                                                                          File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 897, in install_wheel
                                                                                                                              call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
                                                                                                                                File "/home/ich/anaconda3/lib/python3.4/site-packages/virtualenv.py", line 792, in call_subprocess
                                                                                                                                    % (cmd_desc, proc.returncode))
                                                                                                                                    OSError: Command /home/ich/qutebrowser/.venv/bin/python3 - setuptools pip wheel failed with error code 1

                                                                                                                                    ERROR: InvocationError: /home/ich/anaconda3/bin/python3 -m virtualenv --python /home/ich/anaconda3/bin/python3 .venv (see /home/ich/qutebrowser/.venv/log/mkvenv-0.log)
                                                                                                                                    ___________________________________ summary ____________________________________
                                                                                                                                    ERROR:   mkvenv: InvocationError: /home/ich/anaconda3/bin/python3 -m virtualenv --python /home/ich/anaconda3/bin/python3 .venv (see /home/ich/qutebrowser/.venv/log/mkvenv-0.log)
                                                                                                                                    
```

**Comment by The-Compiler** [comment]
Seems like `/home/ich/anaconda3/bin/python3` is used - could you try removing that from your `$PATH` and see if it works with a non-anaconda python?

**Comment by The-Compiler** [comment]
For posterity - that worked:

```
10:08 <sker> Hello! I opened issue 1377 and got the following response 'Seems like /home/ich/anaconda3/bin/python3 is used - could you try removing that from your $PATH and see if it works with a non-anaconda python?' Im a beginner and would like to know if i cannot use anaconda anymore if i do this?
10:10 <The-Compiler> sker: Hi! You could do that temporarily in the shell you're using just to check if that fixes it
10:10 <The-Compiler> sker: can you show what "echo $PATH" shows there?
10:13 <sker> @ Compiler: It shows this /home/ich/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10:15 <The-Compiler> sker: okay - can you do   export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games   and then try  tox -e mkvenv  again? That change will only be active in the shell you run it in.
10:19 <sker> The-Compiler: Oh nice, this succeeded! 
10:20 <The-Compiler> sker: awesome! I think now you'll be able to start qutebrowser via ./.venv/bin/python -m qutebrowser even with anaconda in the path
```
