### ISSUE TITLE
Deleted C++ object: WebView in NetworkManager.createRequest

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1449]
> opening qutebrowser after closing with :wq
> i didnt want everything to load so i openend a new window and closed the one where
> every tab wanted to download its contents.

```
01:35:46 DEBUG    commands   command:run:490 command called: close
01:35:46 DEBUG    commands   command:run:504 Calling qutebrowser.mainwindow.mainwindow.MainWindow.close(<qutebrowser.mainwindow.mainwindow.MainWindow>)
01:35:46 DEBUG    destroy    mainwindow:_do_close:402 Closing window 0
01:35:46 DEBUG    destroy    webview:shutdown:334 Shutting down <qutebrowser.browser.webview.WebView tab_id=0 url='…'>.
01:35:46 DEBUG    webview    webview:_set_load_status:184 load status for <qutebrowser.browser.webview.WebView tab_id=0 url='…'>: LoadStatus.success
01:35:46 DEBUG    signals    signalfilter:_filter_signals:92 ignoring: cur_load_status_changed('success') (tab 0)
01:35:46 DEBUG    webview    webview:_handle_auto_insert_mode:450 Focused element is null!
01:35:46 DEBUG    signals    signalfilter:_filter_signals:92 ignoring: cur_load_finished(False) (tab 0)
01:35:46 DEBUG    destroy    webview:shutdown:334 Shutting down <qutebrowser.browser.webview.WebView tab_id=1 url='…'>.
[...]
01:35:49 DEBUG    webview    webview:_set_load_status:184 load status for <qutebrowser.browser.webview.WebView tab_id=7 url='…'>: LoadStatus.success
01:35:49 DEBUG    signals    signalfilter:_filter_signals:92 ignoring: cur_load_status_changed('success') (tab 0)
01:35:49 DEBUG    webview    webview:_handle_auto_insert_mode:450 Focused element is null!
01:35:49 DEBUG    signals    signalfilter:_filter_signals:92 ignoring: cur_load_finished(False) (tab 0)
01:35:49 DEBUG    destroy    webview:shutdown:334 Shutting down <qutebrowser.browser.webview.WebView tab_id=8 url='…'>.
01:35:50 DEBUG    destroy    webview:shutdown:334 Shutting down <qutebrowser.browser.webview.WebView tab_id=9 url='…'>.
01:35:50 DEBUG    destroy    webview:shutdown:334 Shutting down <qutebrowser.browser.webview.WebView tab_id=10 url='…'>.
01:35:50 DEBUG    webview    webview:_set_load_status:184 load status for <qutebrowser.browser.webview.WebView tab_id=10 url='…'>: LoadStatus.success
[...]
01:35:56 DEBUG    webview    tabbedbrowser:_tab_index:133 Got invalid tab (index is -1)!
01:35:56 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 0
01:35:56 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
01:35:56 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
[...]
01:36:02 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 37
01:36:02 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
01:36:02 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
01:36:02 ERROR    misc       utils:wrapper:513 Error in qutebrowser.browser.network.networkmanager.NetworkManager.createRequest
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/utils.py", line 511, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/network/networkmanager.py", line 369, in createRequest
    current_url = webview.url()
RuntimeError: wrapped C/C++ object of type WebView has been deleted
[...]
01:36:02 DEBUG    destroy    objreg:_on_destroyed:123 removed: 0
01:36:02 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
01:36:02 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager
[...]
01:36:02 DEBUG    destroy    objreg:_on_destroyed:123 removed: 37
01:36:02 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
01:36:02 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager
01:36:02 DEBUG    webview    tabbedbrowser:_tab_index:133 Got invalid tab (index is -1)!
01:36:02 DEBUG    webview    webview:_set_load_status:184 load status for <qutebrowser.browser.webview.WebView tab_id=63 url='…'>: LoadStatus.success
01:36:02 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('success') (tab -1)
01:36:02 DEBUG    webview    webview:_handle_auto_insert_mode:450 Focused element is null!
01:36:02 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(True) (tab -1)
01:36:02 DEBUG    webview    tabbedbrowser:_tab_index:133 Got invalid tab (index is -1)!
01:36:02 DEBUG    completion completer:update_cursor_part:430 cursor_part 0, spaces False
01:36:02 DEBUG    completion completer:update_completion:307 Updating completion - prefix , parts [''], cursor_part 0
01:36:02 DEBUG    destroy    lineparser:_prepare_save:81 Saving to /home/nulterm/.local/share/qutebrowser/cmd-history
01:36:02 DEBUG    destroy    lineparser:_prepare_save:81 Saving to /home/nulterm/.local/share/qutebrowser/cookies
01:36:03 DEBUG    webview    tabbedbrowser:_tab_index:133 Got invalid tab (index is -1)!
01:36:03 ERROR    webview    webpage:_handle_errorpage:165 Error while loading ... Network access is disabled.
01:36:03 DEBUG    webview    webpage:_handle_errorpage:167 Error domain: 0, error code: 99
01:36:03 DEBUG    webview    tabbedbrowser:_tab_index:133 Got invalid tab (index is -1)!
01:36:03 DEBUG    webview    tabbedbrowser:_tab_index:133 Got invalid tab (index is -1)!
01:36:03 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
01:36:03 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
01:36:03 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
01:36:03 DEBUG    webview    webview:_set_load_status:184 load status for <qutebrowser.browser.webview.WebView tab_id=64 url='…'>: LoadStatus.success
01:36:03 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('success') (tab 0)
01:36:03 DEBUG    webview    webview:_handle_auto_insert_mode:450 Focused element is null!
01:36:03 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(True) (tab 0)
01:36:03 DEBUG    webview    tabbedbrowser:_tab_index:133 Got invalid tab (index is -1)!
01:36:14 DEBUG    destroy    lineparser:_prepare_save:81 Saving to /home/nulterm/.local/share/qutebrowser/cookies
```

**Comment by The-Compiler** [comment]
The crash report was with v0.4.1 - this was actually fixed already (#889).
