### ISSUE TITLE
QtValueError on invalid URL when e.g. searching (due to marks)

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1454]
When doing `/foo` quickly after qutebrowser started and is loading a page, this happens:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 265, in run_safely
    self.run(text, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 258, in run
    result.cmd.run(self._win_id, args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 505, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 1432, in search
    self.set_mark("'")
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 1911, in set_mark
    self._tabbed_browser.set_mark(key)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 659, in set_mark
    url = self.current_url().adjusted(QUrl.RemoveFragment)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 239, in current_url
    qtutils.ensure_valid(url)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/qtutils.py", line 145, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: PyQt5.QtCore.QUrl('') is not valid
```

@rcorre can you take a look at this? I'd propose to show an error when trying to set a mark on an invalid URL, and silently ignore it when setting the `'` mark (as that gets set automatically a lot)

**Comment by The-Compiler** [comment]
I don't know a way to automatically test this either, but I manually verified it works. Thanks!
