### ISSUE TITLE
python-pyqt5-5.6 crashes qutebrowser on starting

### ISSUE THREAD

**Issue by ngoonee** [The-Compiler/qutebrowser#1461]
This is the error I get. Downgrading fixes. Using Arch Linux, 64-bit.

```
16:00:48 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 195, in _process_args
    window = mainwindow.MainWindow()
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/mainwindow.py", line 134, in __init__
    download_manager = downloads.DownloadManager(self.win_id, self)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 729, in __init__
    win_id, None, self)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/network/networkmanager.py", line 116, in __init__
    self.authenticationRequired.connect(self.on_authentication_required)
TypeError: decorated slot has no signature compatible with authenticationRequired(QNetworkReply*,QAuthenticator*)
16:00:48 ERROR: Error while recovering pages
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/crashsignal.py", line 179, in _get_exception_info
    pages = self._recover_pages(forgiving=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/crashsignal.py", line 116, in _recover_pages
    window=win_id)
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/objreg.py", line 217, in get
    return reg[name]
  File "/usr/lib/python3.5/collections/__init__.py", line 969, in __getitem__
    raise KeyError(key)
KeyError: 'tabbed-browser'
16:00:48 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 195, in _process_args
    window = mainwindow.MainWindow()
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/mainwindow.py", line 134, in __init__
    download_manager = downloads.DownloadManager(self.win_id, self)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 729, in __init__
    win_id, None, self)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/network/networkmanager.py", line 116, in __init__
    self.authenticationRequired.connect(self.on_authentication_required)
TypeError: decorated slot has no signature compatible with authenticationRequired(QNetworkReply*,QAuthenticator*)
16:00:48 ERROR: Error while recovering pages
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/crashsignal.py", line 179, in _get_exception_info
    pages = self._recover_pages(forgiving=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/crashsignal.py", line 116, in _recover_pages
    window=win_id)
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/objreg.py", line 217, in get
    return reg[name]
  File "/usr/lib/python3.5/collections/__init__.py", line 969, in __getitem__
    raise KeyError(key)
KeyError: 'tabbed-browser'
```

(*edited by @The-Compiler to put the exception in a code block*)

**Comment by The-Compiler** [comment]
This is already fixed in the git repo. I'll release a v0.6.2 with the fixes later this week as there might be more things breaking and I want to use it for a few days first.

I [asked packagers to backport the patches](https://lists.schokokeks.org/pipermail/qutebrowser/2016-April/000200.html) but that hasn't happened for Archlinux yet. I recommend downgrading PyQt as you did, or using `qutebrowser-git` from the AUR in the meantime.
