### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'elems'

### ISSUE THREAD

**Issue by mgoral** [The-Compiler/qutebrowser#1464]
Hello,

when I close previously displayed hints with escape the following exception is raised, which ultimately leads to qutebrowser restart:

```
08:52:21 DEBUG    keyboard   basekeyparser:_debug_log:111 No binding found for f.
08:52:21 DEBUG    keyboard   basekeyparser:_debug_log:111 Got key: 0x46 / text: 'f'
08:52:21 DEBUG    keyboard   basekeyparser:_debug_log:111 Definitive match for 'f'.
08:52:21 DEBUG    commands   command:run:490 command called: hint
08:52:21 DEBUG    commands   command:run:504 Calling qutebrowser.browser.hints.HintManager.start(<qutebrowser.browser.hints.HintManager object at 0x7f98b97d9558>, False, <Group.all: 1>, <Target.normal: 1>, win_id
=0)
08:52:21 DEBUG    hints      hints:_init_elements:691 hints: a, s, d, f, w, e, r, g, h, j
08:52:21 DEBUG    message    message:set_text:323 Follow hint...
08:52:21 DEBUG    statusbar  text:set_text:60 Setting normal text to 'Follow hint...'.
08:52:21 DEBUG    hints      hints:_connect_frame_signals:653 Connecting frame <PyQt5.QtWebKitWidgets.QWebFrame object at 0x7f98700a2558>
08:52:21 DEBUG    modes      modeman:enter:240 Entering mode KeyMode.hint (reason: HintManager.start)
08:52:21 DEBUG    modes      modeman:_eventFilter_keypress:194 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webview.WebView ta
b_id=0 url='https://duckduckgo.com/'>)
08:52:21 DEBUG    modes      modeman:_eventFilter_keyrelease:214 filter: True
08:52:22 DEBUG    modes      modeman:_eventFilter_keypress:169 got keypress in mode KeyMode.hint - delegating to <qutebrowser.keyinput.modeparsers.HintKeyParser supports_chains=True supports_count=False>
08:52:22 DEBUG    keyboard   basekeyparser:_debug_log:111 Got key: 0x1000000 / text: '
08:52:22 DEBUG    keyboard   basekeyparser:_debug_log:111 Ignoring, no text char
08:52:22 DEBUG    keyboard   modeparsers:_handle_special_key:141 Got special key 0x1000000 text
08:52:22 DEBUG    commands   command:run:490 command called: clear-keychain
08:52:22 DEBUG    commands   command:run:504 Calling qutebrowser.keyinput.modeman.ModeManager.clear_keychain(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.hint: 2>>)
08:52:22 DEBUG    keyboard   basekeyparser:_debug_log:111 discarding keystring ''.
08:52:22 DEBUG    hints      hints:handle_partial_key:841 Handling new keystring: ''
08:52:22 DEBUG    commands   command:run:490 command called: leave-mode
08:52:22 DEBUG    commands   command:run:504 Calling qutebrowser.keyinput.modeman.ModeManager.leave_current_mode(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.hint: 2>>)
08:52:22 DEBUG    modes      modeman:leave:284 Leaving mode KeyMode.hint (reason: leave current)
08:52:22 DEBUG    hints      hints:_cleanup:178 Disconnecting frame <PyQt5.QtWebKitWidgets.QWebFrame object at 0x7f98700a2558>
08:52:22 DEBUG    hints      hints:_cleanup:192 Disconnected.
08:52:22 DEBUG    statusbar  text:maybe_reset_text:75 Resetting: 'Follow hint...'
08:52:22 DEBUG    statusbar  text:set_text:60 Setting normal text to ''.
08:52:22 DEBUG    keyboard   basekeyparser:_debug_log:111 discarding keystring ''.
08:52:22 DEBUG    hints      hints:handle_partial_key:841 Handling new keystring: ''
08:52:22 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/mgoral/code/qutebrowser/qutebrowser/keyinput/modeparsers.py", line 220, in on_keystring_updated
    hintmanager.handle_partial_key(keystr)
  File "/home/mgoral/code/qutebrowser/qutebrowser/browser/hints.py", line 842, in handle_partial_key
    for (text, elems) in self._context.elems.items():
AttributeError: 'NoneType' object has no attribute 'elems'
```

I can observe this error on current HEAD (60f8681b4113d671041b6b710f0d90b3bf063268), it doesn't seem to exist on v0.6.1.

**Comment by ml-** [comment]
broken as off 8b227f4ba46ba891ce6d5b81892417c93eedc75a

**Comment by The-Compiler** [comment]
Whooops! I likely won't have the time to look at this today, but I reverted 2d5ffbfd02e22fce9640089b58d4a4a73a25d081 as a stop-gap. @rcorre could you take a look at what's going on?

**Comment by rcorre** [comment]
Oops, sorry! Might just leave that reverted -- I'll look into #319 as a better solution to handling counts.

**Comment by The-Compiler** [comment]
Okay! I also added a test for this now, so I'm closing the issue.
