### ISSUE TITLE
Deleted C++ object: QNetworkReply in downloads. set_fileobj

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1470]
on 0.6.1, PyQt 5.5.1, Qt 5.6

> open a link for download a PDF from
> http://www.ieee.org/conferences_events/conferences/publishing/templates.html

```
20:36:42 DEBUG    webview    webpage:acceptNavigationRequest:583 acceptNavigationRequest, url http://www.ctan.org/tex-archive/macros/latex/contrib/IEEEtran/IEEEtran_HOWTO.pdf, type NavigationTypeLinkClicked, hint target None, open_target ClickTarget.normal
20:36:42 DEBUG    webview    tabbedbrowser:tabopen:384 Creating new tab with URL None
[...]
20:36:42 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=5 url='http://www.ieee.org/conferences_events/conferences/publishing/templates.html'>: LoadStatus.success
[...]
20:36:44 DEBUG    downloads  downloads:fetch:883 fetch: PyQt5.QtCore.QUrl('http://mirror.ibcp.fr/pub/CTAN/macros/latex/contrib/IEEEtran/IEEEtran_HOWTO.pdf') -> IEEEtran_HOWTO.pdf
20:36:44 DEBUG    statusbar  prompter:ask_question:304 Asking question <qutebrowser.utils.usertypes.Question default='/home/thibaut/Downloads/' mode=<PromptMode.text: 2> text='Save file to:'>, blocking False, loops [], queue deque([])
20:36:44 DEBUG    modes      prompter:_display_question:183 Question asked, focusing <qutebrowser.mainwindow.statusbar.prompt.PromptLineEdit>
20:36:44 DEBUG    statusbar  bar:_set_severity:281 Setting severity to Severity.normal
20:36:44 DEBUG    statusbar  bar:_set_prompt_active:300 Setting prompt_active to True
20:36:44 DEBUG    modes      modeman:enter:238 Entering mode KeyMode.prompt (reason: question asked)
20:36:44 DEBUG    statusbar  text:set_text:60 Setting normal text to '-- PROMPT MODE --'.
20:36:44 DEBUG    webview    webview:on_mode_entered:470 Ignoring focus because mode KeyMode.prompt was entered.
20:36:44 DEBUG    webview    webpage:_handle_errorpage:148 Ignored error on http://mirror.ibcp.fr/pub/CTAN/macros/latex/contrib/IEEEtran/IEEEtran_HOWTO.pdf: Frame load interrupted by policy change (error domain: 2, error code: 102)
20:36:44 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=7 url=''>: LoadStatus.success
20:36:44 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('success') (tab 0)
20:36:44 DEBUG    webview    tabbedbrowser:on_title_changed:490 Ignoring title change to ''.
20:36:44 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(False) (tab 0)
20:36:44 DEBUG    webview    webpage:_handle_errorpage:148 Ignored error on http://mirror.ibcp.fr/pub/CTAN/macros/latex/contrib/IEEEtran/IEEEtran_HOWTO.pdf: Frame load interrupted by policy change (error domain: 2, error code: 102)
20:36:44 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=6 url=''>: LoadStatus.success
20:36:44 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('success') (tab 0)
20:36:44 DEBUG    webview    tabbedbrowser:on_title_changed:490 Ignoring title change to ''.
20:36:44 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(False) (tab 0)
20:36:44 DEBUG    modes      modeman:_eventFilter_keypress:167 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
20:36:44 DEBUG    keyboard   basekeyparser:_debug_log:107 No binding found for d.
20:36:44 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x44 / text: 'd'
20:36:44 DEBUG    keyboard   basekeyparser:_debug_log:107 Definitive match for 'd'.
20:36:44 DEBUG    commands   command:run:490 command called: tab-close
20:36:44 DEBUG    commands   command:run:504 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
20:36:44 DEBUG    destroy    webview:shutdown:332 Shutting down <qutebrowser.browser.webview.WebView tab_id=6 url=''>.
20:36:44 DEBUG    downloads  downloads:on_reply_finished:632 Reply finished, fileobj None
20:36:44 DEBUG    destroy    mainwindow:_do_close:408 Closing window 6
20:36:44 DEBUG    modes      modeman:_eventFilter_keypress:193 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: None)
20:36:44 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 6
20:36:44 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
20:36:44 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
20:36:44 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 6
20:36:44 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: main-window
[...]
20:36:44 DEBUG    destroy    objreg:_on_destroyed:123 removed: 6
20:36:44 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
20:36:44 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager
20:36:44 DEBUG    destroy    objreg:_on_destroyed:123 removed: 6
20:36:44 DEBUG    destroy    objreg:_on_destroyed:123 removed: main-window
[...]
20:36:46 DEBUG    modes      modeman:_eventFilter_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='prompt' warn=False>
[...]
20:36:48 DEBUG    modes      modeman:_eventFilter_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='prompt' warn=False>
20:36:48 DEBUG    commands   command:run:490 command called: prompt-accept
20:36:48 DEBUG    commands   command:run:504 Calling qutebrowser.mainwindow.statusbar.prompter.Prompter.prompt_accept(<qutebrowser.mainwindow.statusbar.prompter.Prompter busy=True loops=0 question=<qutebrowser.utils.usertypes.Question default='/home/thibaut/Downloads/' mode=<PromptMode.text: 2> text='Save file to:'>…)
[...]
20:36:48 DEBUG    modes      tabbedbrowser:on_mode_left:544 Left status-input mode, focusing <qutebrowser.browser.webview.WebView tab_id=7 url=''>
20:36:48 DEBUG    misc       app:on_focus_object_changed:766 Focus object changed: <qutebrowser.browser.webview.WebView tab_id=7 url=''>
20:36:48 DEBUG    webview    webview:on_mode_left:498 Restoring focus policy because mode KeyMode.prompt was left.
20:36:48 DEBUG    downloads  downloads:set_filename:558 Setting filename to /tmp
20:36:48 DEBUG    downloads  downloads:set_fileobj:585 buffer: 0 bytes
20:36:48 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 571, in set_filename
    self._create_fileobj()
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 383, in _create_fileobj
    self.set_fileobj(fileobj)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 589, in set_fileobj
    if self.reply.isFinished():
RuntimeError: wrapped C/C++ object of type QNetworkReply has been deleted
```

**Comment by The-Compiler** [comment]
I've never seen this again.
