### ISSUE TITLE
flake8 env broken due to pip bug (?)

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1486]
Since today, this happens with [flake8 on Travis CI](https://travis-ci.org/The-Compiler/qutebrowser/jobs/129346122) (reproduced locally on Debian):

```
flake8 create: /home/travis/build/The-Compiler/qutebrowser/.tox/flake8
flake8 installdeps: -r/home/travis/build/The-Compiler/qutebrowser/requirements.txt, ebb-lint==0.4.4, flake8==2.5.4, flake8-copyright==0.1, flake8-debugger==1.4.0, flake8-deprecated==1.0, flake8-docstrings==0.2.6, flake8-future-import==0.3.2, flake8-mock==0.2, flake8-pep3101==0.3, flake8-putty==0.3.2, flake8-string-format==0.2.1, flake8-tidy-imports==1.0.0, flake8-tuple==0.2.9, hacking==0.11.0, intervaltree==2.1.0, mccabe==0.4.0, packaging==16.7, pbr==1.9.1, pep257==0.7.0, pep8==1.7.0, pep8-naming==0.3.3, pydocstyle==1.0.0, pyflakes==1.2.2, pyparsing==2.1.1  # rq.filter: != 2.1.2, six==1.10.0, sortedcontainers==1.4.4, venusian==1.0
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/The-Compiler/qutebrowser/.tox/flake8/log/flake8-1.log
ERROR: actionid: flake8
msg: getenv
cmdargs: [local('/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/bin/pip'), 'install', '-r/home/travis/build/The-Compiler/qutebrowser/requirements.txt', 'ebb-lint==0.4.4', 'flake8==2.5.4', 'flake8-copyright==0.1', 'flake8-debugger==1.4.0', 'flake8-deprecated==1.0', 'flake8-docstrings==0.2.6', 'flake8-future-import==0.3.2', 'flake8-mock==0.2', 'flake8-pep3101==0.3', 'flake8-putty==0.3.2', 'flake8-string-format==0.2.1', 'flake8-tidy-imports==1.0.0', 'flake8-tuple==0.2.9', 'hacking==0.11.0', 'intervaltree==2.1.0', 'mccabe==0.4.0', 'packaging==16.7', 'pbr==1.9.1', 'pep257==0.7.0', 'pep8==1.7.0', 'pep8-naming==0.3.3', 'pydocstyle==1.0.0', 'pyflakes==1.2.2', 'pyparsing==2.1.1  # rq.filter: != 2.1.2', 'six==1.10.0', 'sortedcontainers==1.4.4', 'venusian==1.0']
env: [...]
Invalid requirement: 'pyparsing==2.1.1  # rq.filter: != 2.1.2'
Traceback (most recent call last):
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 1172, in parseString
    raise exc
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 1162, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 1028, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 2462, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 1032, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/_vendor/pyparsing.py", line 2265, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 18), (line:1, col:19)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/flake8/lib/python3.4/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'# rq.fil'"
```

We worked around this in 7a51387fb33bad8a4b0e17c84e7492c632281ede and broke it again in e095f9ded209c31b4acf8417bca8fd0c55562b68 (when trying to fix another thirdparty bug...).

Not sure if [pip](https://github.com/pypa/pip/issues), [packaging](https://github.com/pypa/packaging/issues) or tox is to blame, but this [worked earlier](https://travis-ci.org/The-Compiler/qutebrowser/jobs/129274411) with a line-comment in `tox.ini`.

**Comment by The-Compiler** [comment]
Reported in https://github.com/pypa/pip/issues/3667, but we should have a way to hardcode the pip version in a way requirements.io picks it up.

**Comment by The-Compiler** [comment]
Worked around by b634b051c8bd87df02a9e412468c9a32743f25b8 and pip/virtualenv/... is now pinned. Keeping this open as a reminder to open a tox bug too.

**Comment by The-Compiler** [comment]
I also opened https://bitbucket.org/hpk42/tox/issues/332 some days ago.
