### ISSUE TITLE
RecursionError when using rapid hints with only one link

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1513]
Discovered by @rcorre in #1510

When opening a page with one link (like `tests/integration/data/hints/link.html`) and doing `;ra` we get:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 863, in eventFilter
    return handler(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 823, in _handle_key_event
    return man.eventFilter(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 318, in eventFilter
    return self._eventFilter_keypress(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 170, in _eventFilter_keypress
    handled = parser.handle(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeparsers.py", line 178, in handle
    match = self._handle_single_key(e)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 197, in _handle_single_key
    self.execute(binding, self.Type.chain, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeparsers.py", line 201, in execute
    hintmanager.fire(cmdstr)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/hints.py", line 950, in fire
    self.filter_hints(None)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/hints.py", line 893, in filter_hints
    self.fire(*visible)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/hints.py", line 950, in fire
    self.filter_hints(None)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/hints.py", line 893, in filter_hints
    self.fire(*visible)
  [...]
RecursionError: maximum recursion depth exceeded

**Comment by The-Compiler** [comment]
I think the following happens:

- `fire` is called because a keystring matched
- `fire` wants to display all hints again `self.filter_hints(None)` because a hint was fired and we're in rapid mode
- `filter_hints` does so, notices only one hint is visible, and tries to follow it (calls `fire`)
- etc.
