### ISSUE TITLE
Completing a single option-like argument crashes

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1523]
Do `:--<space>` and boom:

```
23:23:39 DEBUG    completion completer:schedule_completion_update:294 Scheduling completion update.
23:23:39 DEBUG    completion completer:schedule_completion_update:291 Ignoring update because there were no changes.
23:23:39 DEBUG    completion completer:update_cursor_part:427 cursor_part 1, spaces False
23:23:39 DEBUG    completion completer:update_completion:307 Updating completion - prefix :, parts ['--'], cursor_part 1
23:23:39 DEBUG    completion completer:_get_new_completion:203 Before filtering flags: parts ['--'], cursor_part 1
23:23:39 DEBUG    completion completer:_get_new_completion:206 After filtering flags: parts [], cursor_part 1
23:23:39 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/completer.py", line 326, in update_completion
    model = self._get_new_completion(parts, self._cursor_part)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/completer.py", line 213, in _get_new_completion
    completions = cmdutils.cmd_dict[parts[0]].completion
IndexError: list index out of range
```

**Comment by The-Compiler** [comment]
Fixed via #1531.
