### ISSUE TITLE
OSError during downloads with no space left

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1580]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 647, in on_ready_read
    self.fileobj.write(self.reply.readAll())
OSError: [Errno 28] No space left on device
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 649, in on_ready_read
    self._die(e.strerror)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/downloads.py", line 416, in _die
    self.fileobj.close()
OSError: [Errno 28] No space left on device
```

**Comment by The-Compiler** [comment]
I don't think so - there are various locations in the download code where we could get an exception with a full disk. With `/dev/full`, that's only testing one scenario.
