### ISSUE TITLE
 QtWebEngineWidgets must be imported before a QCoreApplication instance is created

### ISSUE THREAD

**Issue by fermuch** [The-Compiler/qutebrowser#1640]
## Error:
```
08:34:43 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/qutebrowser/app.py", line 198, in _process_args
    _open_startpage()
  File "/usr/lib64/python3.5/site-packages/qutebrowser/app.py", line 309, in _open_startpage
    tabbed_browser.tabopen(url)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 382, in tabopen
    tab = browsertab.create(win_id=self._win_id, parent=self)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/browser/browsertab.py", line 47, in create
    from qutebrowser.browser.webengine import webenginetab
  File "/usr/lib64/python3.5/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 29, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created
```

## qutebrowser --version:
```
qutebrowser v0.7.0
Git commit: v0.7.0-293-ge9d606a (2016-07-11 12:09:41 +0200)

CPython: 3.5.1
Qt: 5.6.0
PyQt: 5.6.1.dev1604271126

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Platform: Linux-4.5.2-1-x86_64-Intel-R-_Core-TM-_i5-2430M_CPU_@_2.40GHz-with-gentoo-2.2.0, 64bit
Desktop: lxqt
Frozen: False
Imported from /usr/lib64/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/gentoo-release ---
Funtoo Linux - baselayout 2.2.0

--- /etc/lsb-release ---
DISTRIB_ID="Gentoo"
```

**Comment by The-Compiler** [comment]
Hmm, interesting that you're still getting it... Can you please pull and show the output with `--debug`? I just added some debug logging.

**Comment by fermuch** [comment]
(testing with commit 7e36884cbd83750e6d3de48b88ae444cdd247684)

```
08:57:32 DEBUG    init       earlyinit:init_log:301 Log initialized.
08:57:32 DEBUG    init       earlyinit:maybe_import_webengine:277 Failed to import QtWebEngineWidgets: No module named 'PyQt5.QtWebChannel'
08:57:32 DEBUG    init       app:__init__:752 Qt arguments: ['/usr/lib/python-exec/python3.5/qutebrowser'], based on Namespace(backend='webengine', basedir=None, cachedir=None, color=True, command=['2'], confdir=None, datadir=None, debug=True, debug_exit=False, force_color=False, harfbuzz='auto', json_args=None, json_logging=False, logfilter=None, loglevel='info', loglines=2000, no_err_windows=False, nowindow=False, override_restore=False, pdb_postmortem=False, qt_name=None, qt_qmljsdebugger=None, qt_reverse=None, qt_style=None, qt_stylesheet=None, qt_widgetcount=None, relaxed_config=False, session=None, target=None, temp_basedir=False, temp_basedir_restarted=None, temp_settings=[], url=[], version=False)
08:57:32 DEBUG    init       app:__init__:755 Initializing application...
08:57:32 WARNING  qt         Unknown module:none:0 QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-fermuch'
  File "/usr/lib/python-exec/python3.5/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.7.0', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib64/python3.5/site-packages/qutebrowser/qutebrowser.py", line 163, in main
    return app.run(args)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/app.py", line 94, in run
    server = ipc.send_or_listen(args)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/misc/ipc.py", line 522, in send_or_listen
    socketname = _get_socketname(args.basedir)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/misc/ipc.py", line 65, in _get_socketname
    target_dir = standarddir.runtime()
  File "/usr/lib64/python3.5/site-packages/qutebrowser/utils/standarddir.py", line 108, in runtime
    path = _writable_location(typ)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/utils/standarddir.py", line 126, in _writable_location
    path = QStandardPaths.writableLocation(typ)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/utils/log.py", line 375, in qt_message_handler
    stack = ''.join(traceback.format_stack())

08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for RuntimeLocation: /tmp/runtime-fermuch
08:57:32 DEBUG    ipc        ipc:_has_legacy_server:421 Trying to connect to qutebrowser-fermuch
08:57:32 DEBUG    ipc        ipc:_has_legacy_server:428 Socket error: QLocalSocket::connectToServer: Invalid name (2)
08:57:32 DEBUG    ipc        ipc:send_to_running_instance:468 Connecting to /tmp/runtime-fermuch/qutebrowser/ipc-4be76efe44c1570f9a41007f542b7bf5
08:57:32 DEBUG    ipc        ipc:send_to_running_instance:501 No existing instance present (error 0)
08:57:32 DEBUG    init       ipc:send_or_listen:531 Starting IPC server...
08:57:32 DEBUG    ipc        ipc:__init__:192 Not calling setSocketOptions
08:57:32 DEBUG    ipc        ipc:listen:203 Listening as /tmp/runtime-fermuch/qutebrowser/ipc-4be76efe44c1570f9a41007f542b7bf5
08:57:32 DEBUG    init       app:init:128 Starting init...
08:57:32 DEBUG    init       app:_init_modules:386 Initializing save manager...
08:57:32 DEBUG    init       app:_init_modules:390 Initializing network...
08:57:32 DEBUG    init       networkmanager:init:92 Default Qt ciphers: ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-RSA-AES256-SHA384, ECDHE-ECDSA-AES256-SHA384, ECDHE-RSA-AES256-SHA, ECDHE-ECDSA-AES256-SHA, SRP-DSS-AES-256-CBC-SHA, SRP-RSA-AES-256-CBC-SHA, SRP-AES-256-CBC-SHA, DH-DSS-AES256-GCM-SHA384, DHE-DSS-AES256-GCM-SHA384, DH-RSA-AES256-GCM-SHA384, DHE-RSA-AES256-GCM-SHA384, DHE-RSA-AES256-SHA256, DHE-DSS-AES256-SHA256, DH-RSA-AES256-SHA256, DH-DSS-AES256-SHA256, DHE-RSA-AES256-SHA, DHE-DSS-AES256-SHA, DH-RSA-AES256-SHA, DH-DSS-AES256-SHA, DHE-RSA-CAMELLIA256-SHA, DHE-DSS-CAMELLIA256-SHA, DH-RSA-CAMELLIA256-SHA, DH-DSS-CAMELLIA256-SHA, ECDH-RSA-AES256-GCM-SHA384, ECDH-ECDSA-AES256-GCM-SHA384, ECDH-RSA-AES256-SHA384, ECDH-ECDSA-AES256-SHA384, ECDH-RSA-AES256-SHA, ECDH-ECDSA-AES256-SHA, AES256-GCM-SHA384, AES256-SHA256, AES256-SHA, CAMELLIA256-SHA, PSK-AES256-CBC-SHA, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-SHA256, ECDHE-ECDSA-AES128-SHA256, ECDHE-RSA-AES128-SHA, ECDHE-ECDSA-AES128-SHA, SRP-DSS-AES-128-CBC-SHA, SRP-RSA-AES-128-CBC-SHA, SRP-AES-128-CBC-SHA, DH-DSS-AES128-GCM-SHA256, DHE-DSS-AES128-GCM-SHA256, DH-RSA-AES128-GCM-SHA256, DHE-RSA-AES128-GCM-SHA256, DHE-RSA-AES128-SHA256, DHE-DSS-AES128-SHA256, DH-RSA-AES128-SHA256, DH-DSS-AES128-SHA256, DHE-RSA-AES128-SHA, DHE-DSS-AES128-SHA, DH-RSA-AES128-SHA, DH-DSS-AES128-SHA, DHE-RSA-SEED-SHA, DHE-DSS-SEED-SHA, DH-RSA-SEED-SHA, DH-DSS-SEED-SHA, DHE-RSA-CAMELLIA128-SHA, DHE-DSS-CAMELLIA128-SHA, DH-RSA-CAMELLIA128-SHA, DH-DSS-CAMELLIA128-SHA, ECDH-RSA-AES128-GCM-SHA256, ECDH-ECDSA-AES128-GCM-SHA256, ECDH-RSA-AES128-SHA256, ECDH-ECDSA-AES128-SHA256, ECDH-RSA-AES128-SHA, ECDH-ECDSA-AES128-SHA, AES128-GCM-SHA256, AES128-SHA256, AES128-SHA, SEED-SHA, CAMELLIA128-SHA, IDEA-CBC-SHA, PSK-AES128-CBC-SHA, ECDHE-RSA-RC4-SHA, ECDHE-ECDSA-RC4-SHA, ECDH-RSA-RC4-SHA, ECDH-ECDSA-RC4-SHA, RC4-SHA, RC4-MD5, PSK-RC4-SHA
08:57:32 DEBUG    init       networkmanager:init:108 Disabling bad ciphers: ECDHE-RSA-RC4-SHA, ECDHE-ECDSA-RC4-SHA, ECDH-RSA-RC4-SHA, ECDH-ECDSA-RC4-SHA, RC4-SHA, RC4-MD5, PSK-RC4-SHA
08:57:32 DEBUG    init       app:_init_modules:392 Initializing readline-bridge...
08:57:32 DEBUG    init       app:_init_modules:395 Initializing directories...
08:57:32 DEBUG    init       standarddir:init:207 Base directory: None
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for CacheLocation: /home/fermuch/.cache/qutebrowser
08:57:32 DEBUG    init       app:_init_modules:397 Initializing config...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       ini:__init__:56 Reading config from /home/fermuch/.config/qutebrowser/qutebrowser.conf
08:57:32 DEBUG    url        urlutils:get_path_if_valid:358 Checking if 'https://google.com' is a path
08:57:32 DEBUG    url        urlutils:fuzzy_url:190 URL is a fuzzy address
08:57:32 DEBUG    url        urlutils:fuzzy_url:193 Converting fuzzy term 'https://google.com' to URL -> https://google.com
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       keyconf:__init__:101 Loaded bindings: OrderedDict([('!normal', OrderedDict([('<escape>', 'clear-keychain ;; leave-mode'), ('<ctrl-[>', 'clear-keychain ;; leave-mode')])), ('normal', OrderedDict([('<escape>', 'clear-keychain ;; search'), ('o', 'set-cmd-text -s :open'), ('go', 'set-cmd-text :open {url:pretty}'), ('O', 'set-cmd-text -s :open -t'), ('gO', 'set-cmd-text :open -t {url:pretty}'), ('xo', 'set-cmd-text -s :open -b'), ('xO', 'set-cmd-text :open -b {url:pretty}'), ('wo', 'set-cmd-text -s :open -w'), ('wO', 'set-cmd-text :open -w {url:pretty}'), ('ga', 'open -t'), ('<ctrl-t>', 'open -t'), ('<ctrl-n>', 'open -w'), ('d', 'tab-close'), ('<ctrl-w>', 'tab-close'), ('D', 'tab-close -o'), ('co', 'tab-only'), ('J', 'tab-focus'), ('<ctrl-pgdown>', 'tab-focus'), ('gm', 'tab-move'), ('gl', 'tab-move -'), ('gr', 'tab-move +'), ('K', 'tab-prev'), ('<ctrl-pgup>', 'tab-prev'), ('gC', 'tab-clone'), ('r', 'reload'), ('<f5>', 'reload'), ('R', 'reload -f'), ('<ctrl-f5>', 'reload -f'), ('H', 'back'), ('th', 'back -t'), ('wh', 'back -w'), ('L', 'forward'), ('tl', 'forward -t'), ('wl', 'forward -w'), ('<f11>', 'fullscreen'), ('f', 'hint'), ('F', 'hint all tab'), ('wf', 'hint all window'), (';b', 'hint all tab-bg'), (';f', 'hint all tab-fg'), (';h', 'hint all hover'), (';i', 'hint images'), (';I', 'hint images tab'), ('.i', 'hint images tab-bg'), (';o', 'hint links fill ":open {hint-url}"'), (';O', 'hint links fill ":open -t {hint-url}"'), ('.o', 'hint links fill ":open -b {hint-url}"'), (';y', 'hint links yank'), (';Y', 'hint links yank-primary'), (';r', 'hint --rapid links tab-bg'), (';R', 'hint --rapid links window'), (';d', 'hint links download'), (';t', 'hint inputs'), ('h', 'scroll left'), ('j', 'scroll down'), ('k', 'scroll up'), ('l', 'scroll right'), ('u', 'undo'), ('<ctrl-shift-t>', 'undo'), ('gg', 'scroll-perc 0'), ('G', 'scroll-perc'), ('n', 'search-next'), ('N', 'search-prev'), ('i', 'enter-mode insert'), ('v', 'enter-mode caret'), ('`', 'enter-mode set_mark'), ("'", 'enter-mode jump_mark'), ('yy', 'yank'), ('yY', 'yank -s'), ('yt', 'yank -t'), ('yT', 'yank -ts'), ('yd', 'yank -d'), ('yD', 'yank -ds'), ('yp', 'yank -p'), ('yP', 'yank -ps'), ('pp', 'paste'), ('pP', 'paste -s'), ('Pp', 'paste -t'), ('PP', 'paste -ts'), ('wp', 'paste -w'), ('wP', 'paste -ws'), ('b', 'set-cmd-text -s :quickmark-load'), ('B', 'set-cmd-text -s :quickmark-load -t'), ('wb', 'set-cmd-text -s :quickmark-load -w'), ('M', 'bookmark-add'), ('gb', 'set-cmd-text -s :bookmark-load'), ('gB', 'set-cmd-text -s :bookmark-load -t'), ('wB', 'set-cmd-text -s :bookmark-load -w'), ('sf', 'save'), ('ss', 'set-cmd-text -s :set'), ('sl', 'set-cmd-text -s :set -t'), ('sk', 'set-cmd-text -s :set keybind'), ('-', 'zoom-out'), ('+', 'zoom-in'), ('=', 'zoom'), ('[[', 'navigate prev'), (']]', 'navigate next'), ('{{', 'navigate prev -t'), ('}}', 'navigate next -t'), ('gu', 'navigate up'), ('gU', 'navigate up -t'), ('<ctrl-a>', 'navigate increment'), ('<ctrl-x>', 'navigate decrement'), ('wi', 'inspector'), ('gd', 'download'), ('ad', 'download-cancel'), ('cd', 'download-clear'), ('gf', 'view-source'), ('gt', 'set-cmd-text -s :buffer'), ('<ctrl-tab>', 'tab-focus last'), ('<ctrl-v>', 'enter-mode passthrough'), ('<ctrl-q>', 'quit'), ('<ctrl-f>', 'scroll-page 0 1'), ('<ctrl-b>', 'scroll-page 0 -1'), ('<ctrl-d>', 'scroll-page 0 0.5'), ('<ctrl-u>', 'scroll-page 0 -0.5'), ('<alt-1>', 'tab-focus 1'), ('<alt-2>', 'tab-focus 2'), ('<alt-3>', 'tab-focus 3'), ('<alt-4>', 'tab-focus 4'), ('<alt-5>', 'tab-focus 5'), ('<alt-6>', 'tab-focus 6'), ('<alt-7>', 'tab-focus 7'), ('<alt-8>', 'tab-focus 8'), ('<alt-9>', 'tab-focus 9'), ('<ctrl-h>', 'home'), ('<ctrl-s>', 'stop'), ('<ctrl-alt-p>', 'print'), ('Ss', 'open qute:settings'), ('<return>', 'follow-selected'), ('<ctrl-m>', 'follow-selected'), ('<ctrl-j>', 'follow-selected'), ('<shift-return>', 'follow-selected'), ('<enter>', 'follow-selected'), ('<shift-enter>', 'follow-selected'), ('<ctrl-return>', 'follow-selected -t'), ('<ctrl-enter>', 'follow-selected -t'), ('m', 'spawn mpv {url}')])), ('insert', OrderedDict([('<ctrl-e>', 'open-editor'), ('<shift-ins>', 'paste-primary')])), ('hint', OrderedDict([('<return>', 'follow-hint'), ('<ctrl-m>', 'follow-hint'), ('<ctrl-j>', 'follow-hint'), ('<shift-return>', 'follow-hint'), ('<enter>', 'follow-hint'), ('<shift-enter>', 'follow-hint'), ('<ctrl-r>', 'hint --rapid links tab-bg'), ('<ctrl-f>', 'hint links'), ('<ctrl-b>', 'hint all tab-bg')])), ('command', OrderedDict([('<ctrl-p>', 'command-history-prev'), ('<ctrl-n>', 'command-history-next'), ('<shift-tab>', 'completion-item-prev'), ('<up>', 'completion-item-prev'), ('<tab>', 'completion-item-next'), ('<down>', 'completion-item-next'), ('<ctrl-d>', 'completion-item-del'), ('<return>', 'command-accept'), ('<ctrl-m>', 'command-accept'), ('<ctrl-j>', 'command-accept'), ('<shift-return>', 'command-accept'), ('<enter>', 'command-accept'), ('<shift-enter>', 'command-accept')])), ('prompt', OrderedDict([('<return>', 'prompt-accept'), ('<ctrl-m>', 'prompt-accept'), ('<ctrl-j>', 'prompt-accept'), ('<shift-return>', 'prompt-accept'), ('<enter>', 'prompt-accept'), ('<shift-enter>', 'prompt-accept'), ('y', 'prompt-yes'), ('n', 'prompt-no')])), ('command,prompt', OrderedDict([('<ctrl-b>', 'rl-backward-char'), ('<ctrl-f>', 'rl-forward-char'), ('<alt-b>', 'rl-backward-word'), ('<alt-f>', 'rl-forward-word'), ('<ctrl-a>', 'rl-beginning-of-line'), ('<ctrl-e>', 'rl-end-of-line'), ('<ctrl-u>', 'rl-unix-line-discard'), ('<ctrl-k>', 'rl-kill-line'), ('<alt-d>', 'rl-kill-word'), ('<ctrl-w>', 'rl-unix-word-rubout'), ('<alt-backspace>', 'rl-unix-word-rubout'), ('<ctrl-y>', 'rl-yank'), ('<ctrl-?>', 'rl-delete-char'), ('<ctrl-h>', 'rl-backward-delete-char')])), ('caret', OrderedDict([('v', 'toggle-selection'), ('<space>', 'toggle-selection'), ('<ctrl-space>', 'drop-selection'), ('c', 'enter-mode normal'), ('j', 'move-to-next-line'), ('k', 'move-to-prev-line'), ('l', 'move-to-next-char'), ('h', 'move-to-prev-char'), ('e', 'move-to-end-of-word'), ('w', 'move-to-next-word'), ('b', 'move-to-prev-word'), (']', 'move-to-start-of-next-block'), ('[', 'move-to-start-of-prev-block'), ('}', 'move-to-end-of-next-block'), ('{', 'move-to-end-of-prev-block'), ('0', 'move-to-start-of-line'), ('$', 'move-to-end-of-line'), ('gg', 'move-to-start-of-document'), ('G', 'move-to-end-of-document'), ('Y', 'yank-selected -p'), ('y', 'yank-selected'), ('<return>', 'yank-selected'), ('<ctrl-m>', 'yank-selected'), ('<ctrl-j>', 'yank-selected'), ('<shift-return>', 'yank-selected'), ('<enter>', 'yank-selected'), ('<shift-enter>', 'yank-selected'), ('H', 'scroll left'), ('J', 'scroll down'), ('K', 'scroll up'), ('L', 'scroll right')]))])
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    save       savemanager:mark_dirty:73 Marking key-config as dirty.
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    init       ini:__init__:56 Reading config from /home/fermuch/.local/share/qutebrowser/state
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    init       lineparser:__init__:222 Reading /home/fermuch/.local/share/qutebrowser/cmd-history
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       app:_init_modules:400 Initializing web history...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    init       app:_init_modules:402 Initializing crashlog...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    init       app:_init_modules:405 Initializing sessions...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    init       app:_init_modules:407 Initializing js-bridge...
08:57:32 DEBUG    init       app:_init_modules:410 Initializing websettings...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for CacheLocation: /home/fermuch/.cache/qutebrowser
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       app:_init_modules:412 Initializing adblock...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       app:_init_modules:416 Initializing quickmarks...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       lineparser:__init__:222 Reading /home/fermuch/.config/qutebrowser/quickmarks
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       app:_init_modules:419 Initializing bookmarks...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       lineparser:__init__:222 Reading /home/fermuch/.config/qutebrowser/bookmarks/urls
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for ConfigLocation: /home/fermuch/.config
08:57:32 DEBUG    init       app:_init_modules:422 Initializing proxy...
08:57:32 DEBUG    init       app:_init_modules:424 Initializing cookies...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for AppLocalDataLocation: /home/fermuch/.local/share/qutebrowser
08:57:32 DEBUG    init       lineparser:__init__:222 Reading /home/fermuch/.local/share/qutebrowser/cookies
08:57:32 DEBUG    init       app:_init_modules:429 Initializing cache...
08:57:32 DEBUG    misc       standarddir:_writable_location:128 writable location for CacheLocation: /home/fermuch/.cache/qutebrowser
08:57:32 DEBUG    init       app:_init_modules:432 Initializing completions...
08:57:32 DEBUG    init       app:_init_modules:434 Misc initialization...
08:57:32 DEBUG    init       app:init:143 Initializing eventfilter...
08:57:32 DEBUG    init       app:init:148 Connecting signals...
08:57:32 DEBUG    init       app:init:158 Init done!
08:57:32 DEBUG    save       savemanager:save:98 Save of key-config requested - dirty True, save_on_exit False, is_exit False, force False -> True
08:57:32 DEBUG    destroy    keyconf:save:148 Saving key config to /home/fermuch/.config/qutebrowser/keys.conf
08:57:32 DEBUG    init       app:_process_args:191 Initializing main window...
08:57:32 DEBUG    init       mainwindow:__init__:134 Initializing downloads...
08:57:32 DEBUG    init       networkmanager:__init__:155 Initializing NetworkManager
08:57:32 DEBUG    init       networkmanager:__init__:160 NetworkManager init done
08:57:33 DEBUG    statusbar  bar:_hide_cmd_widget:390 Hiding cmd widget, queue: deque([])
08:57:33 DEBUG    statusbar  bar:_set_prompt_active:300 Setting prompt_active to False
08:57:33 DEBUG    statusbar  bar:_hide_prompt_widget:418 Hiding prompt widget, queue: deque([])
08:57:33 DEBUG    init       mainwindow:__init__:167 Initializing modes...
08:57:33 DEBUG    init       mainwindow:_load_geometry:262 Loading mainwindow from b'\x01\xd9\xd0\xcb\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05U\x00\x00\x02\xdf\x00\x00\x002\x00\x00\x002\x00\x00\x03Q\x00\x00\x02\x89\x00\x00\x00\x00\x02\x00\x00\x00\x05V'
08:57:33 DEBUG    init       mainwindow:__init__:177 Initial main window geometry: PyQt5.QtCore.QRect(50, 50, 800, 600)
08:57:33 DEBUG    init       app:process_pos_args:269 Startup URL 2
08:57:33 DEBUG    url        urlutils:get_path_if_valid:358 Checking if '2' is a path
08:57:33 DEBUG    url        urlutils:is_url:242 Checking if '2' is a URL (autosearch=naive).
08:57:33 DEBUG    url        urlutils:is_url:279 Checking via naive check
08:57:33 DEBUG    url        urlutils:is_url:283 url = False
08:57:33 DEBUG    url        urlutils:fuzzy_url:184 URL is a fuzzy search term
08:57:33 DEBUG    url        urlutils:_get_search_url:96 Finding search engine for '2'
08:57:33 DEBUG    url        urlutils:_parse_search_term:83 engine None, term '2'
08:57:33 DEBUG    url        urlutils:fuzzy_url:193 Converting fuzzy term '2' to URL -> https://google.com/search?q=2
08:57:33 DEBUG    webview    tabbedbrowser:tabopen:373 Creating new tab with URL PyQt5.QtCore.QUrl('https://google.com/search?q=2')
08:57:33 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/qutebrowser/app.py", line 197, in _process_args
    process_pos_args(args.command)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/app.py", line 280, in process_pos_args
    explicit=True)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 382, in tabopen
    tab = browsertab.create(win_id=self._win_id, parent=self)
  File "/usr/lib64/python3.5/site-packages/qutebrowser/browser/browsertab.py", line 47, in create
    from qutebrowser.browser.webengine import webenginetab
  File "/usr/lib64/python3.5/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 29, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created
08:57:33 DEBUG    misc       app:on_focus_changed:345 on_focus_changed called with non-QWidget None
08:57:33 DEBUG    init       app:_init_late_modules:445 Reading web history...
08:57:33 DEBUG    misc       app:on_focus_object_changed:767 Focus object changed: <PyQt5.QtWidgets.QTextEdit object at 0x7fb768e42af8>
08:57:33 DEBUG    misc       app:on_focus_object_changed:767 Focus object changed: <PyQt5.QtWidgets.QTextEdit object at 0x7fb768e42af8>
08:57:33 DEBUG    init       debug:__exit__:256 Reading history took 0.099641 seconds.
08:57:33 DEBUG    misc       app:on_focus_changed:345 on_focus_changed called with non-QWidget None
08:57:33 DEBUG    misc       app:on_focus_object_changed:767 Focus object changed: None
08:57:33 DEBUG    misc       app:on_focus_object_changed:767 Focus object changed: <PyQt5.QtWidgets.QTextEdit object at 0x7fb768e42af8>
08:57:33 DEBUG    misc       app:on_focus_object_changed:767 Focus object changed: <PyQt5.QtWidgets.QTextEdit object at 0x7fb768e42af8>
08:57:34 DEBUG    misc       app:on_focus_changed:345 on_focus_changed called with non-QWidget None
```

**Comment by fermuch** [comment]
Oh, it seems like the problem is on my side. I forgot to enable QtWebChannel.

Will recompile and test again.

**Comment by The-Compiler** [comment]
Hmm, right - though the fact that the initial import hides that error is somewhat unfortunate...

**Comment by fermuch** [comment]
Fixed after recompiling PyQt5 with QtWebChannel support.

**Comment by The-Compiler** [comment]
Glad to hear! I guess the early import should actually error out with `--backend webengine` if it isn't available, but that's one for later. :wink:
