### ISSUE TITLE
Can't launch after setting recursive settings

### ISSUE THREAD

**Issue by mbjd** [The-Compiler/qutebrowser#1696]
So I stupidly set the following settings:

    :set colors tabs.bg.selected.odd ${tabs.bg.selected.even}
    :set colors tabs.bg.selected.even ${tabs.bg.selected.odd}

The program crashed and I submitted a bug report, including the following log: http://pastebin.com/8gsj6pet

Now if I try to open the program by double-clicking qutebrowser.app, I get the following error message: 

![image](http://i.imgur.com/9vQfFAp.png)

And if I do it by executing

    $ /Applications/qutebrowser.app/Contents/MacOS/qutebrowser

the output looks like this (the above error window still opens):

    18:12:03 ERROR: Recursion limit exceeded in value substitution: option 'tabs.bg.selected.odd' in section 'colors' contains an interpolation key which cannot be substituted in 10 steps. Raw value: '${tabs.bg.selected.even}'
    Traceback (most recent call last):
      File "qutebrowser/config/config.py", line 144, in _init_main_config
      File "qutebrowser/config/config.py", line 583, in read
      File "qutebrowser/config/config.py", line 540, in _validate_all
      File "configparser.py", line 454, in before_get
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 510, in _interpolate_some
      File "configparser.py", line 469, in _interpolate_some
    configparser.InterpolationDepthError: Recursion limit exceeded in value substitution: option 'tabs.bg.selected.odd' in section 'colors' contains an interpolation key which cannot be substituted in 10 steps. Raw value: '${tabs.bg.selected.even}'

In order to manually revert these settings, I searched for a config file in `~/.config/`, but there's no qutebrowser directory (even though the environment variable XDG_CONFIG_HOME is set to ~/.config). Where can I find the config file so I can set the settings back to something valid?

Version infos:

    $ /Applications/qutebrowser.app/Contents/MacOS/qutebrowser --version
    qutebrowser v0.8.1
    Git commit: v0.8.1-1-gc94ed93 (2016-07-27 12:36:43 +0200)
    
    CPython: 3.5.1
    Qt: 5.6.1
    PyQt: 5.6
    
    sip: 4.18
    colorama: 0.3.7
    pypeg2: 2.15
    jinja2: 2.8
    pygments: 2.1.3
    yaml: 3.11
    cssutils: 1.0.1 $Id$
    typing: yes
    PyQt5.QtWebEngineWidgets: no
    pdf.js: 1.4.20 (bundled)
    Webkit: 538.1
    Harfbuzz: system
    SSL: Secure Transport, OS X El Capitan (10.11)
    
    Platform: Darwin-15.5.0-x86_64-i386-64bit, 64bit
    Desktop: None
    Frozen: True
    Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
    OS Version: 10.11.5, x86_64
    Failed to execute script __main__

**Comment by The-Compiler** [comment]
Hah, I *thought* I was already checking for this when I read the crash report, but I could reproduce the issue and opened #1695. Turns out it's only when setting that value in the browser which isn't handled correctly.

Anyways - the config file is in `~/Library/Preferences/qutebrowser` on OS X.

**Comment by mbjd** [comment]
Well that was quick -- thanks a lot! Written from a perfectly working qutebrowser!
