### ISSUE TITLE
qutebrowser always segfaults on exit

### ISSUE THREAD

**Issue by rumpelsepp** [The-Compiler/qutebrowser#1825]
It is always the same:
```
./qutebrowser.py --backend webengine -l critical
[0810/075548:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
libpng warning: iCCP: known incorrect sRGB profile
^Cfish: “./qutebrowser.py --backend webe…” terminated by signal SIGSEGV (Address boundary error)
```

I am on an up to date arch linux. Let me know if you need more information. :)

**Comment by The-Compiler** [comment]
It's a Qt bug, see #1387. If it bothers you enough, you can use the `qt5-base-debug` package from [my repo](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc#archlinux) where I applied the patches (which aren't even merged to Qt yet...).

**Comment by haasn** [comment]
The linked patch does not fix the segfault on exit for me.

```
λ python3 -m qutebrowser --temp-basedir --backend webengine
[0811/010209:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
^C01:02:11 INFO: SIGINT/SIGTERM received, shutting down!
01:02:11 INFO: Do the same again to forcefully quit.
01:02:12 WARNING: STUB: shutdown
zsh: segmentation fault (core dumped)  python3 -m qutebrowser --temp-basedir --backend webengine
```

```
(gdb) info registers
rax            0x358526141b8	3677874110904
rbx            0x6a0540efd0	455354675152
rcx            0x0	0
rdx            0x6a05458410	455354975248
rsi            0x6a05901f20	455359864608
rdi            0x6a05458410	455354975248
rbp            0x6a05901f60	0x6a05901f60
rsp            0x3d32d6dd5e0	0x3d32d6dd5e0
r8             0x3586e9cb090	3678347767952
r9             0x6a05901c00	455359863808
r10            0x3586e9c9010	3678347759632
r11            0x246	582
r12            0x6a058ff6d0	455359854288
r13            0x357fc003320	3676424909600
r14            0x357fc003230	3676424909360
r15            0x0	0
rip            0x3586c3955ae	0x3586c3955ae <QObjectPrivate::~QObjectPrivate()+478>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) bt
#0  0x000003586c3955ae in QObjectPrivate::~QObjectPrivate() () from /usr/lib64/libQt5Core.so.5
#1  0x000003586c39572c in QObjectPrivate::~QObjectPrivate() () from /usr/lib64/libQt5Core.so.5
#2  0x000003586c39c7c1 in QObject::~QObject() () from /usr/lib64/libQt5Core.so.5
#3  0x0000035858b9026d in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::~MessagePumpForUIQt() () from /usr/lib64/libQt5WebEngineCore.so.5
#4  0x000003585a43ecda in base::MessageLoop::~MessageLoop() () from /usr/lib64/libQt5WebEngineCore.so.5
#5  0x00000358598c2756 in base::MessageLoopForUI::~MessageLoopForUI() () from /usr/lib64/libQt5WebEngineCore.so.5
#6  0x00000358598c30ec in content::BrowserMainLoop::~BrowserMainLoop() () from /usr/lib64/libQt5WebEngineCore.so.5
#7  0x00000358596ef89d in content::BrowserMainRunnerImpl::~BrowserMainRunnerImpl() () from /usr/lib64/libQt5WebEngineCore.so.5
#8  0x0000035858bdaa1f in QtWebEngineCore::WebEngineContext::~WebEngineContext() () from /usr/lib64/libQt5WebEngineCore.so.5
#9  0x0000035858bdaad9 in scoped_refptr<QtWebEngineCore::WebEngineContext>::~scoped_refptr() () from /usr/lib64/libQt5WebEngineCore.so.5
#10 0x000003586dd62a58 in __run_exit_handlers () from /lib64/libc.so.6
#11 0x000003586dd62ab4 in exit () from /lib64/libc.so.6
#12 0x000003586e454e12 in Py_Exit () from /usr/lib64/libpython3.5m.so.1.0
#13 0x000003586e458717 in handle_system_exit.part () from /usr/lib64/libpython3.5m.so.1.0
#14 0x000003586e458b8d in PyErr_PrintEx () from /usr/lib64/libpython3.5m.so.1.0
#15 0x000003586e472c5d in RunModule () from /usr/lib64/libpython3.5m.so.1.0
#16 0x000003586e4733bc in Py_Main () from /usr/lib64/libpython3.5m.so.1.0
#17 0x0000006a00d5dbff in main ()
```

**Comment by manolollr** [comment]
The linked patch works for me.

Thank you.
