### ISSUE TITLE
AssertionError when clicking elements partially outside of view

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1910]
- Open a 4chan board
- Go to Settings -> Monitoring -> Turn on thread watcher
- Scroll down
- Move watcher so it's almost out of the page (center isn't visible)
- Click watcher via hints

```
23:10:58 DEBUG    hints      webelem:click:368 Sending fake click to '<img id="twPrune" class="pointer right" src="//s.4cdn.org/image/buttons/burichan/refresh.png" alt="R" title="Refresh">' at position PyQt5.QtCore.QPoint(564, -5) with target ClickTarget.normal
23:10:58 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/mouse.py", line 235, in eventFilter
    return self._handlers[evtype](event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/mouse.py", line 100, in _handle_mouse_press
    self._tab.elements.find_at_pos(e.pos(), self._mousepress_insertmode_cb)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webkit/webkittab.py", line 536, in find_at_pos
    assert pos.y() >= 0
AssertionError
```

**Comment by lahwaacz** [comment]
I guess the easiest fix would be to detect this sooner than the hints are shown and not show hints for such elements. But the same error happens if the screen is scrolled after the hints are shown...
