### ISSUE TITLE
KeyError for last-visible-main-window when pressing ctrl-c

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1918]
I just got this:

```
12:22:12 INFO     destroy    app:qt_mainloop:118 SIGINT/SIGTERM received, shutting down!
12:22:12 INFO     destroy    app:qt_mainloop:118 Do the same again to forcefully quit.
12:22:12 DEBUG    destroy    app:shutdown:626 Shutting down with status 130, session None...
12:22:12 DEBUG    destroy    app:_shutdown:659 Stage 2 of shutting down...
12:22:12 DEBUG    destroy    app:_shutdown:665 Removing eventfilter...
12:22:13 DEBUG    destroy    mainwindow:_do_close:500 Closing window 33
12:22:13 DEBUG    destroy    webview:shutdown:123 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=58 url='https://duckduckgo.com/?q=sailfish+os+updates&ia=web'>.
12:22:13 DEBUG    destroy    webview:shutdown:123 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=59 url='https://security.google.com/settings/security/apppasswords?utm_source=OGB&pli=1'>.
12:22:13 DEBUG    destroy    mainwindow:_do_close:500 Closing window 30
12:22:13 DEBUG    destroy    webview:shutdown:123 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=51 url='http://imgur.com/gallery/LNge4'>.
12:22:13 DEBUG    destroy    mainwindow:_do_close:500 Closing window 11
12:22:13 DEBUG    destroy    webview:shutdown:123 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=23 url='https://github.com/The-Compiler/qutebrowser/issues/1848'>.
12:22:13 DEBUG    destroy    webview:shutdown:123 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=24 url='http://httpbin.org/'>.
12:22:13 DEBUG    destroy    mainwindow:_do_close:500 Closing window 0
12:22:13 DEBUG    destroy    webview:shutdown:123 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=0 url='https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/misc/pastebin.py#L87-L90'>.
12:22:13 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 536, in closeEvent
    self._do_close()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 492, in _do_close
    last_visible = objreg.get('last-visible-main-window')
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 228, in get
    return reg[name]
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/collections/__init__.py", line 986, in __getitem__
    raise KeyError(key)
KeyError: 'last-visible-main-window'
```

**Comment by The-Compiler** [comment]
cc @antoyo because you reported this before as well
