### ISSUE TITLE
Handle invalid session files gracefully

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1926]
Loading invalid session files can crash qutebrowser in a variety of ways, because the structure of the file is never verified.

**Comment by haasn** [comment]
What kind of crashes are you looking at? One thing you we could try is isolating the session loading code into a dummy context and running that through `afl`, but I'm not really sure what kinds of errors we're trying to catch.

**Comment by The-Compiler** [comment]
The one I did run into was the toplevel object being a list instead of a dict (`- windows:` instead of `windows:`), but I'm sure there are lots more. Basically, qutebrowser should validate the schema/types of the loaded YAML file somehow.

**Comment by lahwaacz** [comment]
That sounds more like a problem with the serialization or (lack of) migration, though verification of the input file(s) would also be good to detect issues caused by external effects.

**Comment by The-Compiler** [comment]
> One thing you we could try is isolating the session loading code into a dummy context and running that through `afl`

One problem I see with AFL is that the files actually need to be valid YAML, otherwise the YAML parser will reject them outright. But it'd probably be a good opportunity to use [hypothesis](http://hypothesis.works/) more.

> That sounds more like a problem with the serialization or (lack of) migration, though verification of the input file(s) would also be good to detect issues caused by external effects.

That broken file was caused by external effects (me while writing a session test) :wink:

**Comment by haasn** [comment]
> One problem I see with AFL is that the files actually need to be valid YAML, otherwise the YAML parser will reject them outright. But it'd probably be a good opportunity to use hypothesis more.

Okay, that's what I was trying to figure out: You're concerned about syntactically valid YAML files that are semantic garbage, not syntactically broken YAML files

**Comment by The-Compiler** [comment]
Since some people like to create session files by hand (or scripted somehow), we should also ignore missing values if they aren't essential (like the geometry).

**Comment by NoctuaNivalis** [comment]
That'd make it a lot easier. I tried to modify a session file once.

**Comment by The-Compiler** [comment]
A particularly interesting one:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 295, in run_safely
    self.run(text, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 274, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 432, in session_load
    self.load(name, temp=temp)
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 389, in load
    self._load_tab(new_tab, tab)
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 362, in _load_tab
    new_tab.history.load_items(entries)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webkit/webkittab.py", line 523, in load_items
    self._tab.zoom.set_factor(cur_data['zoom'])
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/browsertab.py", line 264, in set_factor
    self._neighborlist.fuzzyval = int(factor * 100)
OverflowError: cannot convert float infinity to integer
```

**Comment by The-Compiler** [comment]
Some related crashes:

```
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 230, in _load_session
    session_manager.load(name)
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 395, in load
    for win in data['windows']:
TypeError: 'NoneType' object is not subscriptable
```

```
  File "/home/njr/.home/dot-files/.build/qutebrowser/qutebrowser/misc/sessions.py", line 432, in session_load
    self.load(name, temp=temp)
  File "/home/njr/.home/dot-files/.build/qutebrowser/qutebrowser/misc/sessions.py", line 382, in load
    window = mainwindow.MainWindow(geometry=win['geometry'])
KeyError: 'geometry'
```

```
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 228, in _load_session
    session_manager.load(name)
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 389, in load
    self._load_tab(new_tab, tab)
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 349, in _load_tab
    url = QUrl.fromEncoded(histentry['url'].encode('ascii'))
KeyError: 'url'
```

```
  File "/usr/lib/python3.4/site-packages/qutebrowser/app.py", line 218, in _load_session
    session_manager.load(name)
  File "/usr/lib/python3.4/site-packages/qutebrowser/misc/sessions.py", line 347, in load
    self._load_tab(new_tab, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/misc/sessions.py", line 286, in _load_tab
    for histentry in data['history']:
KeyError: 'history'
```

**Comment by toofar** [comment]
I also have this local change FYI, I don't think it is from normal usage. It was probably me making changes that caused a crash at init-ish.
```diff
diff --git a/qutebrowser/misc/sessions.py b/qutebrowser/misc/sessions.py
index 1155a33ef99e..886d0cf508b4 100644
--- a/qutebrowser/misc/sessions.py
+++ b/qutebrowser/misc/sessions.py
@@ -273,6 +273,13 @@ class SessionManager(QObject):
         else:
             data = self._save_all(only_window=only_window,
                                   with_private=with_private)
+
+        # Sometimes if there is an error during startup an empty session is
+        # saved.
+        if not data.get("windows", []) or not data["windows"][0].get("tabs", []):
+            log.sessions.error("Not saving empty session: {}".format(name))
+            return
+
         log.sessions.vdebug("Saving data: {}".format(data))
         try:
             with qtutils.savefile_open(path) as f:
```
