### ISSUE TITLE
Handle UnicodeEncodeError when reading userscript data

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#2100]
I can only reproduce this with this script:

```bash
#!/bin/bash
dd if=/dev/urandom of="$QUTE_FIFO"
```

but I also got a report of someone getting this for any non-ascii chars (without `LC_*` set):

```
11:11:47 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/userscripts.py", line 68, in read_line
    for line in self._fifo:
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 0: invalid start byte
```

**Comment by HolySmoke86** [comment]
For a more deterministic way to trigger that:
```#!/bin/bash
printf \\x80 > "$QUTE_FIFO"
```

Or this one:
```#!/bin/bash
http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt > "$QUTE_FIFO"
```
although it's probably not necessary to stress test python's UTF-8 decoder here ^^
