### ISSUE TITLE
"I/O operation on closed file" when cancelling mhtml download

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#2101]
When cancelling an MHTML download, we get:

```
11:20:42 DEBUG    downloads  mhtml:_cancelled:435 MHTML download cancelled by user: PyQt5.QtCore.QUrl('https://fedoramagazine.org/wp-content/themes/fedoramagazine-theme-0.05/images/icons/1x/social/mail-g.png')
11:20:42 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webkit/mhtml.py", line 437, in _cancelled
    item.fileobj.seek(0)
ValueError: I/O operation on closed file.
```

When downloading https://fedoramagazine.org/inkscape-adding-colour/ and just cancelling a random download.

@Kingdread one for you?

**Comment by Kingdread** [comment]
Weird, just tried to reproduce it without success... I just did `:download --mhtml` and then spammed `ad`, even trying with numbers.

However, it seems like the mhtml-"Overwrite?" prompt got broken with the new prompts:

```
Traceback (most recent call last):
  File "/home/daniel/Code/qutebrowser/qutebrowser/browser/webkit/mhtml.py", line 545, in start_download_checked
    message_bridge.ask(q, blocking=False)
AttributeError: 'MessageBridge' object has no attribute 'ask'
```

**Comment by The-Compiler** [comment]
I can reproduce it somewhat reliably on that page by trying to right-click and cancel on running downloads (definitely works better on a slow connection :laughing:)

I'll fix the overwrite prompt.

**Comment by Kingdread** [comment]
I managed to crash it! :satisfied:

```
16:20:40 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/daniel/Code/qutebrowser/qutebrowser/browser/webkit/mhtml.py", line 436, in _cancelled
    item.fileobj.seek(0)
ValueError: I/O operation on closed file.
```

I've played around with `trickle` a bit (not sure if it helped) to limit my bandwidth. Now, I'll see if I can reliably recreate it and see what causes it (looks like some race condition)
