### ISSUE TITLE
Decode percent escapes in download filenames

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#2122]
When downloading http://t.cmpl.cc/with%20spaces qutebrowser (with QtWebEngine) does not decode the percent escapes.

**Comment by luumelo14** [comment]
Hi! Is anyone working on this issue? If not, can I give it a try?

**Comment by The-Compiler** [comment]
Nobody is as far as I know - so sure, please do!

**Comment by luumelo14** [comment]
Sorry it took so long for me to reply. I had many issues with QtWebEngine, and when I finally thought I made it work, I got this error when trying to run "qutebrowser --backend webengine":

11:01:53 WARNING: /usr/lib/python3.4/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)

Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.8.4', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3/dist-packages/qutebrowser/qutebrowser.py", line 159, in main
    earlyinit.earlyinit(args)
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/earlyinit.py", line 328, in earlyinit
    check_libraries(args)
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/earlyinit.py", line 278, in check_libraries
    importlib.import_module(name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1715, in load_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
RuntimeError: the sip module implements API v11.0 but the PyQt5.QtWebEngineWidgets module requires API v11.3

I tried to run again and then I got segmentation fault!

Fatal Python error: Segmentation fault

Current thread 0x00007f4aa9835740 (most recent call first):
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/earlyinit.py", line 109 in _die
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/earlyinit.py", line 280 in check_libraries
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/earlyinit.py", line 328 in earlyinit
  File "/usr/lib/python3/dist-packages/qutebrowser/qutebrowser.py", line 159 in main
  File "/usr/bin/qutebrowser", line 9 in <module>
Falha de segmentação (imagem do núcleo gravada)


Do you have any idea of what might be happening?

**Comment by The-Compiler** [comment]
That sounds like your PyQt/Qt setup is broken somehow - the first message means that you have a too old version of `sip` installed, for example. What distribution are you on, and how did you install them?

**Comment by The-Compiler** [comment]
I just fixed a different issue with QtWebEngine download filenames, so I decided to fix this one too. Hope you don't mind! Of course I'm still happy to help trying to get your PyQt running.
