### ISSUE TITLE
FileNotFoundError crash when page is unreachable on debian

### ISSUE THREAD

**Issue by sim590** [The-Compiler/qutebrowser#2205]
I get this error with qutebrowser 0.9.0 on debian.

```
04:29:02 ERROR: Error while loading https://awesome.naquadah.org/wiki/Revelation: Host unreachable
04:29:02 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/browser/webkit/webpage.py", line 423, in extension
    return handler(opt, out)
  File "/usr/lib/python3/dist-packages/qutebrowser/browser/webkit/webpage.py", line 173, in _handle_errorpage
    title=title, url=urlstr, error=error_str, icon='')
  File "/usr/lib/python3/dist-packages/qutebrowser/utils/jinja.py", line 112, in render
    return _env.get_template(template).render(**kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "html/error.html", line 1, in top-level template code
  File "html/base.html", line 28, in top-level template code
  File "html/error.html", line 76, in block "content"
  File "/usr/lib/python3/dist-packages/qutebrowser/utils/jinja.py", line 102, in data_url
    data = utils.read_file(path, binary=True)
  File "/usr/lib/python3/dist-packages/qutebrowser/utils/utils.py", line 140, in read_file
    data = pkg_resources.resource_string(qutebrowser.__name__, filename)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1210, in resource_string
    self, resource_name
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1452, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1572, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/qutebrowser/img/broken_qutebrowser_logo.png'
```

## Version

```
qutebrowser v0.9.0
Git commit: 

CPython: 3.5.2+
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.8.0-2-amd64-x86_64-with-debian-stretch-sid, 64bit
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian

Paths:
data: /home/simon/.local/share/qutebrowser
cache: /home/simon/.cache/qutebrowser
runtime: /run/user/1000/qutebrowser
download: /home/simon
config: /home/simon/.config/qutebrowser
system_data: /usr/share/qutebrowser
```

**Comment by sim590** [comment]
This doesn't happen when using qutebrowser built from source instead of the debian 0.9.0 package. Closing this.

**Comment by The-Compiler** [comment]
Reopening as we're building/releasing those Debian packages currently :wink:

It seems like that file is missing from the Debian package indeed... @fiete201 is looking into this.

**Comment by fiete201** [comment]
Yes the picture was missing. Its added now and fixed package uploaded to the releases page. Please install the new version @sim590 

Best regards
Fritz

**Comment by The-Compiler** [comment]
Closing this then, thanks @fiete201!
