### ISSUE TITLE
Errors at startup: The 'qutebrowser==0.8.4' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by code-hunger** [The-Compiler/qutebrowser#2224]
Just did an update and the browser can't start anymore:
```
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qutebrowser==0.8.4' distribution was not found and is required by the application

```

Running `qutebrowser-git` from the AUR (ver. `r10898.e1b5f6a64-1`). The `git clon`ed latest version (a10a6bdfa238745641ba5d6a98e2a067612a19ca) starts just fine.

Looking at the pacman.log there are many python updates, I can provide a list if needed. (including pyqt5 upgrade from 5.7-2 to 5.7-3)

**Comment by The-Compiler** [comment]
You'll need to rebuild `qutebrowser-git` (and any other Python packages from the AUR) against Python 3.6. I'll push a version upgrade so this happens automatically for qutebrowser at least.
