### ISSUE TITLE
Recent updates in Arch have broken compatibility. ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

### ISSUE THREAD

**Issue by vmikhaliuk** [The-Compiler/qutebrowser#2234]
After update to harfbuzz-1.4.1-1 and recompile qutebrowser-git via aur (r10984.5ede2c641-1)

    $qutebrowser --backend webengine

    Traceback (most recent call last):
      File "/usr/bin/qutebrowser", line 11, in <module>
        load_entry_point('qutebrowser==0.9.0', 'gui_scripts', 'qutebrowser')()
      File "/usr/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 165, in main
        earlyinit.earlyinit(args)
      File "/usr/lib/python3.6/site-packages/qutebrowser/misc/earlyinit.py", line 359, in earlyinit
        check_qt_version(args)
      File "/usr/lib/python3.6/site-packages/qutebrowser/misc/earlyinit.py", line 245, in check_qt_version
        from qutebrowser.utils import qtutils
      File "/usr/lib/python3.6/site-packages/qutebrowser/utils/qtutils.py", line 38, in <module>
        from PyQt5.QtWidgets import QApplication
    ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

Downgrading harfbuzz to 1.3.4-1 solve this problem.

**Comment by lahwaacz** [comment]
This is not a problem in qutebrowser, see https://bbs.archlinux.org/viewtopic.php?id=221644.
