### ISSUE TITLE
Qutebrowser Crashing upon opening 

### ISSUE THREAD

**Issue by austinf24** [The-Compiler/qutebrowser#2253]
linux noob seeking help with no idea where to start. I installed qutebrowser as per instructions on the qutebrowser website for my openSuse tumbleweed setup. upon trying to run qutebrowser I get the following error message: 

austin@linux-77cz:~> qutebrowser
11:33:54 ERROR: No option 'yank-ignored-url-parameters' in section 'general'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 780, in set
    sect.setv(layer, optname, value, interpolated)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/sections.py", line 128, in setv
    self.values[key].setv(layer, value, interpolated)
KeyError: 'yank-ignored-url-parameters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 144, in _init_main_config
    relaxed=args.relaxed_config)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 581, in read
    self._from_cp(parser, relaxed)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 501, in _from_cp
    self._from_cp_section(sectname, cp, relaxed)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 527, in _from_cp_section
    self.set('conf', sectname, k, v, validate=False)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 782, in set
    raise configexc.NoOptionError(optname, sectname)
qutebrowser.config.configexc.NoOptionError: No option 'yank-ignored-url-parameters' in section 'general'
austin@linux-77cz:~> qutebrowser
11:52:59 ERROR: No option 'yank-ignored-url-parameters' in section 'general'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 780, in set
    sect.setv(layer, optname, value, interpolated)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/sections.py", line 128, in setv
    self.values[key].setv(layer, value, interpolated)
KeyError: 'yank-ignored-url-parameters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 144, in _init_main_config
    relaxed=args.relaxed_config)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 581, in read
    self._from_cp(parser, relaxed)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 501, in _from_cp
    self._from_cp_section(sectname, cp, relaxed)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 527, in _from_cp_section
    self.set('conf', sectname, k, v, validate=False)
  File "/usr/lib/python3.5/site-packages/qutebrowser/config/config.py", line 782, in set
    raise configexc.NoOptionError(optname, sectname)
qutebrowser.config.configexc.NoOptionError: No option 'yank-ignored-url-parameters' in section 'general'
austin@linux-77cz:~> 

please help get this running again as I have no clue where to start.

**Comment by The-Compiler** [comment]
That looks like you have a newer config lying around (v0.9.0 or newer) but are trying to run an older qutebrowser (v0.8.4 or older).

You can do either of the following:

- Upgrade to v0.9.1 (which I'd really recommend anyways!)
- Start with `--relaxed-config` and do `:save` once
- Remove your `~/.config/qutebrowser` if you don't care about your config.

**Comment by The-Compiler** [comment]
@austinf24 any update on this?

**Comment by The-Compiler** [comment]
...closing this - let me know if it doesn't work though!
