### ISSUE TITLE
Performance issue when clicking links on twitter

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#260]
Sometimes when clicking links on twitter opening the new tab takes multiple seconds.

Profile:

![2014-11-15-222300_1366x768_scrot](https://cloud.githubusercontent.com/assets/625793/5059292/2c3063a4-6d16-11e4-89d4-cdf1d076ecc9.png)

Additionally we get this when opening a lot of them:

```
Traceback (most recent call last):
  File "scripts/../qutebrowser/keyinput/modeman.py", line 126, in eventFilter
    window='current')
  File "scripts/../qutebrowser/utils/objreg.py", line 221, in get
    reg = _get_registry(scope, window, tab)
  File "scripts/../qutebrowser/utils/objreg.py", line 210, in _get_registry
    return _get_window_registry(window)
  File "scripts/../qutebrowser/utils/objreg.py", line 175, in _get_window_registry
    app = get('app')
  File "scripts/../qutebrowser/utils/objreg.py", line 223, in get
    return reg[name]
RuntimeError: maximum recursion depth exceeded
```

**Comment by The-Compiler** [comment]
I don't see this anymore - and if it still happens, let's blame QtWebKit for this one.
