### ISSUE TITLE
Weird exceptions on shutdown

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#359]
```
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: hintmanager
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: 2
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: main-window
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: message-bridge
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: download-manager
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: tabbed-browser
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: statusbar
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: prompt
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: status-command
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: completion
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: completer
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: search-runner
19:43:33 DEBUG misc objreg:_on_destroyed:123 removed: mode-manager
19:43:37 DEBUG modes modeman:_eventFilter_keyrelease:249 filter: False
19:43:38 DEBUG modes modeman:_eventFilter_keypress:204 got keypress in mode KeyMode.normal - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
19:43:38 DEBUG keyboard basekeyparser:_debug_log:103 No binding found for d.
19:43:38 DEBUG keyboard basekeyparser:_debug_log:103 Got key: 0x44 / text: 'd'
19:43:38 DEBUG keyboard basekeyparser:_debug_log:103 Definitive match for 'd'.
19:43:38 DEBUG commands command:run:468 command called: tab-close
19:43:38 DEBUG commands command:run:482 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
19:43:38 DEBUG destroy webview:shutdown:285 Shutting down <qutebrowser.browser.webview.WebView tab_id=9 url='https://github.com/nhomar/pelican/blob/master/LIC…'>.
19:43:38 DEBUG signals signalfilter:_filter_signals:95 ignoring: cur_link_hovered('', '', '') (tab 0)
19:43:38 DEBUG modes tabbedbrowser:on_current_changed:525 Current tab changed, focusing <qutebrowser.browser.webview.WebView tab_id=8 url='https://duckduckgo.com/?q=pelican+blog+generator'>
19:43:38 DEBUG modes modeman:maybe_leave:109 Mode KeyMode.hint not on mode stack! (leave reason: tab changed)
19:43:38 DEBUG modes modeman:maybe_leave:109 Mode KeyMode.insert not on mode stack! (leave reason: tab changed)
19:43:38 DEBUG modes modeman:_eventFilter_keypress:228 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=8
url='https://duckduckgo.com/?q=pelican+blog+generator'>)
19:43:38 DEBUG misc objreg:on_destroyed:118 schedule removal: 9
19:43:38 DEBUG misc objreg:on_destroyed:118 schedule removal: webview
19:43:38 DEBUG misc objreg:on_destroyed:118 schedule removal: hintmanager
19:43:38 DEBUG misc objreg:_on_destroyed:123 removed: 9
19:43:38 DEBUG misc objreg:_on_destroyed:123 removed: webview
19:43:38 DEBUG misc objreg:_on_destroyed:123 removed: hintmanager
19:43:38 DEBUG modes modeman:_eventFilter_keyrelease:249 filter: True
19:43:39 DEBUG modes modeman:_eventFilter_keypress:204 got keypress in mode KeyMode.normal - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Ignoring only-modifier keyeevent.
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Got key: 0x1000022 / text: ''
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Ignoring, no text char
19:43:39 DEBUG modes modeman:_eventFilter_keypress:228 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=8
url='https://duckduckgo.com/?q=pelican+blog+generator'>)
19:43:39 DEBUG modes modeman:_eventFilter_keypress:204 got keypress in mode KeyMode.normal - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Ignoring only-modifier keyeevent.
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Got key: 0x1000020 / text: ''
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Ignoring, no text char
19:43:39 DEBUG modes modeman:_eventFilter_keypress:228 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=8
url='https://duckduckgo.com/?q=pelican+blog+generator'>)
19:43:39 DEBUG destroy mainwindow:closeEvent:339 Closing window 3
19:43:39 DEBUG destroy webview:shutdown:285 Shutting down <qutebrowser.browser.webview.WebView tab_id=8 url='https://duckduckgo.com/?q=pelican+blog+generator'>.
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: 8
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: webview
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: hintmanager
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: 3
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: main-window
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: message-bridge
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: download-manager
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: tabbed-browser
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: statusbar
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: prompt
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: status-command
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: completion
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: completer
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: search-runner
19:43:39 DEBUG misc objreg:on_destroyed:118 schedule removal: mode-manager
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: 8
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: webview
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: hintmanager
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: 3
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: main-window
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: message-bridge
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: download-manager
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: tabbed-browser
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: statusbar
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: prompt
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: status-command
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: completion
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: completer
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: search-runner
19:43:39 DEBUG misc objreg:_on_destroyed:123 removed: mode-manager
19:43:39 DEBUG modes modeman:_eventFilter_keypress:204 got keypress in mode KeyMode.normal - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Ignoring only-modifier keyeevent.
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Got key: 0x1000020 / text: ''
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Ignoring, no text char
19:43:39 DEBUG modes modeman:_eventFilter_keypress:228 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=11
url='https://github.com/The-Compiler/qutebrowser/issue…'>)
19:43:39 DEBUG modes modeman:_eventFilter_keypress:204 got keypress in mode KeyMode.normal - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Ignoring only-modifier keyeevent.
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Got key: 0x1000022 / text: ''
19:43:39 DEBUG keyboard basekeyparser:_debug_log:103 Ignoring, no text char
19:43:39 DEBUG modes modeman:_eventFilter_keypress:228 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=11
url='https://github.com/The-Compiler/qutebrowser/issue…'>)
19:43:39 DEBUG destroy mainwindow:closeEvent:339 Closing window 5
19:43:39 DEBUG destroy webview:shutdown:285 Shutting down <qutebrowser.browser.webview.WebView tab_id=11 url='https://github.com/The-Compiler/qutebrowser/issue…'>.
19:43:40 DEBUG destroy app:shutdown:686 Shutting down with status 0...
19:43:40 DEBUG destroy app:_shutdown:712 Stage 2 of shutting down...
19:43:40 DEBUG destroy app:_shutdown:715 Removing eventfilter...
19:43:40 DEBUG destroy app:_shutdown:769 Saving config (handler: qutebrowser.config.config.ConfigManager.save)
19:43:40 DEBUG destroy config:save:576 Saving config to /home/florian/.config/qutebrowser/qutebrowser.conf
19:43:40 DEBUG destroy app:_shutdown:769 Saving keyconfig (handler: qutebrowser.config.parsers.keyconf.KeyConfigParser.save)
19:43:40 DEBUG destroy keyconf:save:128 Saving key config to /home/florian/.config/qutebrowser/keys.conf
19:43:40 DEBUG destroy app:_shutdown:769 Saving window geometry (handler: qutebrowser.app.Application._save_geometry)
19:43:40 DEBUG destroy app:_shutdown:769 Saving command history (handler: qutebrowser.config.parsers.line.LineConfigParser.save)
19:43:40 DEBUG destroy line:save:106 Saving config to /home/florian/.local/share/qutebrowser/cmd-history
19:43:40 DEBUG destroy app:_shutdown:769 Saving command history (handler: qutebrowser.browser.quickmarks.QuickmarkManager.save)
19:43:40 DEBUG destroy line:save:106 Saving config to /home/florian/.config/qutebrowser/quickmarks
19:43:40 DEBUG destroy app:_shutdown:769 Saving window geometry (handler: qutebrowser.config.parsers.ini.ReadWriteConfigParser.save)
19:43:40 DEBUG destroy ini:save:69 Saving config to /home/florian/.local/share/qutebrowser/state
19:43:40 DEBUG destroy app:_shutdown:769 Saving cookies (handler: qutebrowser.browser.cookies.CookieJar.save)
19:43:40 DEBUG destroy line:save:106 Saving config to /home/florian/.local/share/qutebrowser/cookies
19:43:40 DEBUG destroy app:_shutdown:781 Deactiving crash log...
19:43:40 DEBUG destroy app:_shutdown:784 Deactiving message handler...
19:43:40 DEBUG destroy app:_shutdown:787 Deferring QApplication::exit...
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: 11
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: webview
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: hintmanager
19:43:40 DEBUG destroy app:exit:816 Now calling QApplication::exit.
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: 5
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: main-window
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: message-bridge
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: download-manager
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: tabbed-browser
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: statusbar
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: prompt
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: status-command
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: completion
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: completer
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: search-runner
19:43:40 DEBUG misc objreg:on_destroyed:118 schedule removal: mode-manager
19:43:40 DEBUG statusbar prompter:_restore_ctx:120 Restoring context PromptContext(question=<qutebrowser.utils.usertypes.Question text='[js confirm] Leave tizag.com?' mode=<PromptMode.yesno: 1> default=None>,
text='[js confirm] Leave tizag.com?', input_text='', echo_mode=0, input_visible=False)
19:43:40 ERROR misc app:_exception_hook:483 Uncaught exception
Traceback (most recent call last):
 File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 190, in _get_window_registry
 win = window_registry[window]
 File "/usr/lib/python3.4/collections/__init__.py", line 884, in __getitem__
 raise KeyError(key)
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/statusbar/prompter.py", line 333, in ask_question
 if not self._restore_ctx(context):
 File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/statusbar/prompter.py", line 126, in _restore_ctx
 prompt = objreg.get('prompt', scope='window', window=self._win_id)
 File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 221, in get
 reg = _get_registry(scope, window, tab)
 File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 210, in _get_registry
 return _get_window_registry(window)
 File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 192, in _get_window_registry
 raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
19:43:40 ERROR destroy app:_exception_hook:504 Error while recovering pages
Traceback (most recent call last):
 File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 502, in _exception_hook
 pages = self._recover_pages(forgiving=True)
 File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 426, in _recover_pages
 for tab in tabbed_browser.widgets():
 File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 128, in widgets
 for i in range(self.count()):
RuntimeError: wrapped C/C++ object of type TabbedBrowser has been deleted
19:43:40 ERROR destroy app:_exception_hook:516 Error while getting objects
Traceback (most recent call last):
 File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 514, in _exception_hook
 objects = self.get_all_objects()
 File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 406, in get_all_objects
 output += objreg.dump_objects()
 File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 268, in dump_objects
 blocks.append(('window-{}'.format(win_id), registry.dump_objects()))
 File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 134, in dump_objects
 lines.append("{}: {}".format(name, repr(obj)))
 File "/usr/lib/python3.4/collections/__init__.py", line 895, in __repr__
 def __repr__(self): return repr(self.data)
 File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webview.py", line 130, in __repr__
 url = utils.elide(self.url().toDisplayString(), 50)
RuntimeError: wrapped C/C++ object of type WebView has been deleted
19:43:40 ERROR destroy app:_destroy_crashlogfile:466 Could not remove crash log!
Traceback (most recent call last):
 File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 464, in _destroy_crashlogfile
 os.remove(self._crashlogfile.name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/florian/.local/share/qutebrowser/crash.log'
```

**Comment by The-Compiler** [comment]
I have no idea how this happens and it never happened again, so closing this.
