### ISSUE TITLE
Segfault when refreshing while (e.g. SSL) question is open

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#431]
Report: http://paste.the-compiler.org/view/f393c11a

How to reproduce:
* Navigate to a site with SSL errors, with `network->ssl-strict = ask` which will ask several SSL questions, e.g. https://suckup.de/tag/claws-mail-android/
* Answer no to the first question
* Click "Try again" while the second question is open.

**Comment by The-Compiler** [comment]
The backtrace is pretty much useless:

```
#0  0x00007fffdf98c389 in ?? ()
#1  0x00007fffdddd7f10 in ?? ()
#2  0x0000000000ebe2b0 in ?? ()
#3  0x00007fffdddd7f50 in ?? ()
#4  0x0000000000ebe610 in ?? ()
#5  0x0000000000001000 in ?? ()
#6  0x00007ffff2087ece in QThreadPrivate::start (arg=0xebe2b0) at thread/qthread_unix.cpp:337
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by The-Compiler** [comment]
Otter seemed to have a similiar problem: https://github.com/Emdek/otter/commit/67991929e70099bf701064e9f84d4e7a052cd577
