### ISSUE TITLE
Unknown segfault on novell.com

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#434]
Report: http://paste.the-compiler.org/view/14dca69d

Segfault in Qt mainloop.

@mattiasgiese - Can you reproduce the issue? Do you see a `python3.4` entry in `coredumpctl list`? If so, can you do the following steps please? (replace PID by the column after the date in the list)

```
$ coredumpctl gdb PID
...
(gdb) set logging on
(gdb) bt
...
(gdb) set logging off
```

After that you should find a `gdb.txt` in your working directory with a C++ stacktrace - I hope this will help diagnosing what happened. Thanks!

**Comment by mattiasgiese** [comment]
Here is the log from the (hopefully right, i have a few) backtrace:

```
#0  0x00007f0d3013e0d9 in raise () from /usr/lib/libpthread.so.0
#1  <signal handler called>
#2  0x0000000002e6ad30 in ?? ()
#3  0x00007f0d19ab7ac1 in ?? () from /usr/lib/python3.4/site-packages/PyQt5/QtWebKitWidgets.so
#4  0x00007f0d2462794c in ?? () from /usr/lib/python3.4/site-packages/sip.so
#5  0x00007f0d2463078b in ?? () from /usr/lib/python3.4/site-packages/sip.so
#6  0x00007f0d287ef638 in ?? () from /usr/lib/python3.4/site-packages/PyQt5/QtCore.so
#7  0x00007f0d287fac1e in ?? () from /usr/lib/python3.4/site-packages/PyQt5/QtCore.so
#8  0x00007f0d287faef0 in ?? () from /usr/lib/python3.4/site-packages/PyQt5/QtCore.so
#9  0x00007f0d287fb837 in ?? () from /usr/lib/python3.4/site-packages/PyQt5/QtCore.so
#10 0x00007f0d283c0082 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#11 0x00007f0d20d73247 in QNetworkAccessManager::sslErrors(QNetworkReply*, QList<QSslError> const&) ()
   from /usr/lib/libQt5Network.so.5
#12 0x00007f0d20d7591d in ?? () from /usr/lib/libQt5Network.so.5
#13 0x00007f0d283bff69 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#14 0x00007f0d20e1a3f5 in QNetworkReply::sslErrors(QList<QSslError> const&) ()
   from /usr/lib/libQt5Network.so.5
#15 0x00007f0d20d9687e in ?? () from /usr/lib/libQt5Network.so.5
#16 0x00007f0d20e1b4ab in ?? () from /usr/lib/libQt5Network.so.5
#17 0x00007f0d283c10ea in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#18 0x00007f0d19e8ad5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#19 0x00007f0d19e90340 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007f0d1a79f8fe in ?? () from /usr/lib/python3.4/site-packages/PyQt5/QtWidgets.so
#21 0x00007f0d283906cb in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#22 0x00007f0d2839270b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/libQt5Core.so.5
#23 0x00007f0d283e78b3 in ?? () from /usr/lib/libQt5Core.so.5
#24 0x00007f0d297fba0d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#25 0x00007f0d297fbcf8 in ?? () from /usr/lib/libglib-2.0.so.0
#26 0x00007f0d297fbdac in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#27 0x00007f0d283e7ca7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#28 0x00007f0d2838e162 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#29 0x00007f0d28395b3c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#30 0x00007f0d1a79e31b in ?? () from /usr/lib/python3.4/site-packages/PyQt5/QtWidgets.so
#31 0x00007f0d30462609 in call_function (oparg=<optimized out>, pp_stack=0x7fff543f0810)
    at Python/ceval.c:4234
#32 PyEval_EvalFrameEx (f=0x1d3fce8, throwflag=<optimized out>) at Python/ceval.c:2836
#33 0x00007f0d30463859 in PyEval_EvalCodeEx (_co=0x2f63e80, _co@entry=0x7f0d308f5930, globals=0x0, 
    locals=0x1d3fe60, args=0x12969b8, argcount=20779928, argcount@entry=0, kws=0x0, kwcount=0, defs=0x0, 
    defcount=0, kwdefs=0x0, closure=0x7f0d2ed31dd8) at Python/ceval.c:3585
#34 0x00007f0d3046195f in fast_function (nk=0, na=0, n=<optimized out>, pp_stack=0x7fff543f0a10, 
    func=<optimized out>) at Python/ceval.c:4341
#35 call_function (oparg=<optimized out>, pp_stack=0x7fff543f0a10) at Python/ceval.c:4259
#36 PyEval_EvalFrameEx (f=0x1296808, throwflag=<optimized out>) at Python/ceval.c:2836
#37 0x00007f0d30463859 in PyEval_EvalCodeEx (_co=0x2f63e80, _co@entry=0x7f0d308f59c0, globals=0x0, 
    locals=0x1296980, args=0x11753e0, argcount=20779928, argcount@entry=0, kws=0x0, kwcount=1, defs=0x0, 
    defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3585
#38 0x00007f0d3046195f in fast_function (nk=0, na=0, n=<optimized out>, pp_stack=0x7fff543f0c10, 
    func=<optimized out>) at Python/ceval.c:4341
#39 call_function (oparg=<optimized out>, pp_stack=0x7fff543f0c10) at Python/ceval.c:4259
#40 PyEval_EvalFrameEx (f=0x1175258, throwflag=<optimized out>) at Python/ceval.c:2836
#41 0x00007f0d30463859 in PyEval_EvalCodeEx (_co=0x2f63e80, _co@entry=0x7f0d308f5150, globals=0x0, 
    locals=0x11753d0, args=0x0, argcount=20779928, argcount@entry=0, kws=kws@entry=0x0, kwcount=0, 
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3585
#42 0x00007f0d304638fb in PyEval_EvalCode (co=co@entry=0x7f0d308f5150, 
    globals=globals@entry=0x7f0d3095f448, locals=locals@entry=0x7f0d3095f448) at Python/ceval.c:773
#43 0x00007f0d3047fbb4 in run_mod (mod=mod@entry=0x1159350, filename=filename@entry=0x7f0d30856b28, 
    globals=globals@entry=0x7f0d3095f448, locals=locals@entry=0x7f0d3095f448, 
    flags=flags@entry=0x7fff543f0e90, arena=arena@entry=0x11940c0) at Python/pythonrun.c:2180
#44 0x00007f0d30481de5 in PyRun_FileExFlags (fp=0x1151b70, filename_str=<optimized out>, 
    start=<optimized out>, globals=0x7f0d3095f448, locals=0x7f0d3095f448, closeit=1, flags=0x7fff543f0e90)
    at Python/pythonrun.c:2133
#45 0x00007f0d30482db3 in PyRun_SimpleFileExFlags (fp=0x2f63e80, 
    filename=0x7f0d3091eb40 "/usr/bin/qutebrowser", closeit=1, flags=0x7f0d287d2850)
    at Python/pythonrun.c:1606
#46 0x00007f0d3049901c in run_file (p_cf=<optimized out>, filename=<optimized out>, fp=<optimized out>)
    at Modules/main.c:319
#47 Py_Main (argc=814049944, argv=0x7f0d3091eb20) at Modules/main.c:751
#48 0x0000000000400af6 in main ()

```

**Comment by The-Compiler** [comment]
I wonder if this is a duplicate of #431, or at least the same cause... Can you reproduce it?

**Comment by mattiasgiese** [comment]
This may be indeed the case. Unfortunately not ATM. When qutebrowser crashed ihad a bunch of tabs open. I tried to reproduce it right now with two Tabs open -> https://novell.com and pfsense web-ui with self-signed cert. On the pfsense page it asks whether i want to continue or not on every reload but does not crash.

**Comment by The-Compiler** [comment]
Let's see if this fixes it - please let me know if it happens again!
