### ISSUE TITLE
Error install archlinux "TypeError: 'encoding' is an invalid keyword argument for this function" python3

### ISSUE THREAD

**Issue by avelino** [The-Compiler/qutebrowser#466]
```
$ /usr/bin/python --version
Python 3.4.2

$ /usr/bin/python 
Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```
```
==> Starting build()...
Traceback (most recent call last):
File "setup.py", line 27, in <module>
from scripts import setupcommon as common
File "/tmp/pacaurtmp-avelino/qutebrowser/src/qutebrowser-0.1.2/scripts/setupcommon.py", line 97, in <module>
'version': '.'.join(map(str, _get_constant('version_info'))),
File "/tmp/pacaurtmp-avelino/qutebrowser/src/qutebrowser-0.1.2/scripts/setupcommon.py", line 57, in _get_constant
line = field_re.search(read_file(path)).group(1)
File "/tmp/pacaurtmp-avelino/qutebrowser/src/qutebrowser-0.1.2/scripts/setupcommon.py", line 38, in read_file
with open(name, 'r', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
==> ERROR: A failure occurred in build().
Aborting...
:: qutebrowser cleaning skipped
:: failed to build qutebrowser package(s)
```

**Comment by The-Compiler** [comment]
As said in my AUR comment, this looks like `setup.py` gets executed with python2 rather than with python3. Is it possible you have a python2-`python` in your `$PATH` before `/usr/bin/python`? What does `which python` say?

**Comment by avelino** [comment]
True, I was with a virtualenv active!
