### ISSUE TITLE
pkg_resources.DistributionNotFound: pypeg2

### ISSUE THREAD

**Issue by avelino** [The-Compiler/qutebrowser#467]
Run in archlinux, install via pacaur!
```
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pypeg2
```

**Comment by The-Compiler** [comment]
Again it works fine here.

Did you (or pacaur) install python-pypeg2 from AUR which is a dependency?
