### ISSUE TITLE
Segfault related to SSL errors and inspector.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#482]
I just had that overight:

```
#0  0x00007f2445c830d9 in raise () from /usr/lib/libpthread.so.0
#1  <signal handler called>
#2  0x0000000000000021 in ?? ()
#3  0x00007f242f5fcf7a in QObject::inherits (this=0x48d8f60, classname=0x7f242f6061ca <sipStrings_QtWebKitWidgets+4810> "QWebInspector") at /usr/include/qt/QtCore/qobject.h:426
#4  0x00007f242f5fc790 in sipSubClass_QWebView (sipCppRet=0x7fff757e9ef0) at /home/florian/proj/qt-debug-pkgbuild/pyqt5/src/PyQt-gpl-5.4-snapshot-850ad2e2dd38/sip/QtWebKitWidgets/qwebview.sip:50
#5  0x00007f243c86d94c in ?? () from /usr/lib/python3.4/site-packages/sip.so
#6  0x00007f243c87678b in ?? () from /usr/lib/python3.4/site-packages/sip.so
#7  0x00007f2440c797cd in Chimera::toPyObject (this=0x22213c0, cpp=0x7fff757ea2c8) at ../qpy/QtCore/qpycore_chimera.cpp:1427
#8  0x00007f2440c6823c in PyQtSlot::invoke (this=0x4b52bb0, qargs=0x7fff757ea2d8, self=0x0, result=0x0, no_receiver_check=false) at ../qpy/QtCore/qpycore_pyqtslot.cpp:133
#9  0x00007f2440c68026 in PyQtSlot::invoke (this=0x4b52bb0, qargs=0x7fff757ea2d0, no_receiver_check=false) at ../qpy/QtCore/qpycore_pyqtslot.cpp:76
#10 0x00007f2440c6999d in PyQtSlotProxy::unislot (this=0x4b544b0, qargs=0x7fff757ea2d0) at ../qpy/QtCore/qpycore_pyqtslotproxy.cpp:205
#11 0x00007f2440c698f1 in PyQtSlotProxy::qt_metacall (this=0x4b544b0, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fff757ea2d0) at ../qpy/QtCore/qpycore_pyqtslotproxy.cpp:170
#12 0x00007f2440829082 in QMetaObject::activate (sender=0x4b51c60, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fff757ea2d0) at kernel/qobject.cpp:3731
#13 0x00007f24408295f7 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x7f243951eb40 <QNetworkAccessManager::staticMetaObject>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fff757ea2d0)
    at kernel/qobject.cpp:3582
#14 0x00007f243942e247 in QNetworkAccessManager::sslErrors (this=<optimized out>, _t1=0x48d8f60, _t2=...) at .moc/moc_qnetworkaccessmanager.cpp:328
#15 0x00007f243943091d in QNetworkAccessManager::qt_static_metacall (_o=0x48d8f60, _c=794845642, _id=76386144, _a=0x7f242f6061ca <sipStrings_QtWebKitWidgets+4810>) at .moc/moc_qnetworkaccessmanager.cpp:155
#16 0x00007f2440828f69 in QMetaObject::activate (sender=0x48d8f60, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fff757ea450) at kernel/qobject.cpp:3716
#17 0x00007f24408295f7 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x7f2439521d60 <QNetworkReply::staticMetaObject>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fff757ea450)
    at kernel/qobject.cpp:3582
#18 0x00007f24394d53f5 in QNetworkReply::sslErrors (this=<optimized out>, _t1=...) at .moc/moc_qnetworkreply.cpp:340
#19 0x00007f243945187e in QNetworkReplyHttpImplPrivate::replySslErrors (this=0xbdf7530, list=..., ignoreAll=0x7f239660836f, toBeIgnored=0x7f2396608370) at access/qnetworkreplyhttpimpl.cpp:1252
#20 0x00007f24394d64ab in QNetworkReplyHttpImpl::qt_static_metacall (_o=0x48d8f60, _c=794845642, _id=76386144, _a=0x7f242f6061ca <sipStrings_QtWebKitWidgets+4810>) at .moc/moc_qnetworkreplyhttpimpl_p.cpp:234
#21 0x00007f244082a0ea in QObject::event (this=0x48d8f60, e=<optimized out>) at kernel/qobject.cpp:1245
#22 0x00007f242f9f5d5c in QApplicationPrivate::notify_helper (this=0x1b7d9d0, receiver=0x48d8f60, e=0x7f23a4030df0) at kernel/qapplication.cpp:3722
#23 0x00007f242f9fb340 in QApplication::notify (this=0x1bbe790, receiver=0x48d8f60, e=0x7f23a4030df0) at kernel/qapplication.cpp:3505
#24 0x00007f243021fec8 in sipQApplication::notify (this=0x1bbe790, a0=0x48d8f60, a1=0x7f23a4030df0) at sipQtWidgetsQApplication.cpp:349
#25 0x00007f24407f96cb in QCoreApplication::notifyInternal (this=0x1bbe790, receiver=0x48d8f60, event=event@entry=0x7f23a4030df0) at kernel/qcoreapplication.cpp:932
#26 0x00007f24407fb70b in sendEvent (event=0x7f23a4030df0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:228
#27 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x1fa83c0) at kernel/qcoreapplication.cpp:1536
#28 0x00007f24407fbd08 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1394
#29 0x00007f24408508b3 in postEventSourceDispatch (s=0x1fd6080) at kernel/qeventdispatcher_glib.cpp:271
#30 0x00007f2441f61a0d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#31 0x00007f2441f61cf8 in ?? () from /usr/lib/libglib-2.0.so.0
#32 0x00007f2441f61dac in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#33 0x00007f2440850ca7 in QEventDispatcherGlib::processEvents (this=0x1fd9880, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#34 0x00007f24407f7162 in QEventLoop::exec (this=this@entry=0x7fff757eaaa0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#35 0x00007f24407feb3c in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1185
```

On fb2e84b on Arch, Qt 5.4.0, PyQt 5.4-snapshot-850ad2e2dd38

**Comment by The-Compiler** [comment]
https://www.mail-archive.com/pyqt@riverbankcomputing.com/msg23338.html looks related - but I don't know how this happened and what to do about it.
