### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'isFinished'

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#495]
Report: http://paste.the-compiler.org/view/66f9e2e4 - on f6d0907 with Qt 5.2.1.

Exception:

```
Traceback (most recent call last):
  File "/home/yume/lib/qutebrowser/qutebrowser/browser/downloads.py", line 269, in _create_fileobj
    self.set_fileobj(fileobj)
  File "/home/yume/lib/qutebrowser/qutebrowser/browser/downloads.py", line 435, in set_fileobj
    if self.reply.isFinished():
AttributeError: 'NoneType' object has no attribute 'isFinished'
```

Log:

```
downloads  downloads:fetch:705 fetch: PyQt5.QtCore.QUrl('http://www.compoundchem.com/wp-content/uploads/2015/01/The-Maillard-Reaction.pdf') -> The-Maillard-Reaction.pdf
downloads  downloads:set_filename:411 Setting filename to The-Maillard-Reaction.pdf
statusbar  prompter:ask_question:303 Asking question <qutebrowser.utils.usertypes.Question default=None text='/home/yume/Downloads/The-Maillard-Reaction.pdf already exists. Overwrite? (y/n)' mode=<PromptMode.yesno: 1>>, blocking False, loops [], queue deque([])
[...]
qt         qnetworkreplyhttpimpl:void QNetworkReplyHttpImplPrivate::error(QNetworkReply::NetworkError, const QString&):1929 QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
misc       message:error:213 Download error: Error downloading http://www.compoundchem.com/wp-content/uploads/2015/01/The-Maillard-Reaction.pdf - server replied: Not Acceptable
[...]
modes      modeman:_eventFilter_keypress:176 got keypress in mode KeyMode.yesno - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
[...]
commands   command:run:473 command called: prompt-yes
downloads  downloads:set_fileobj:431 buffer: 0 bytes
misc       app:_exception_hook:513 Uncaught exception
```

**Comment by The-Compiler** [comment]
Fixed in cbde36948ad096ad3691b8b5c06352486b6ac593.
