### ISSUE TITLE
"OSError: Reply is closed!" in download read timer timeout.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#502]
> I was downloading an ISO and when it reached 100% i wanted to click the download link away. Then it seemingly tried to restart the download and then it crashed.

On fba2b2b, Qt 5.4.0

Exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/downloads.py", line 513, in on_read_timer_timeout
    raise OSError("Reply is closed!")
OSError: Reply is closed!
```

Config:

```
[ui]
remove-finished-downloads = true
```

Objects:

```
window-0 object registry - 15 objects:
    download-manager: <qutebrowser.browser.downloads.DownloadManager downloads=1>
    prompter: <qutebrowser.mainwindow.statusbar.prompter.Prompter busy=True question=<qutebrowser.utils.usertypes.Question text='Save file to:' mode=<PromptMode.text: 2> default='GoboLinux-015-i686.iso'> queue=0 loops=0>
```

Log:

```
17:22:14 DEBUG    downloads  downloads:cancel:347 cancelled
17:22:14 DEBUG    downloads  downloads:fetch:707 fetch: PyQt5.QtCore.QUrl('http://mirror.layerjet.com/gobolinux/GoboLinux-015-i686.iso') -> GoboLinux-015-i686.iso
17:22:14 DEBUG    statusbar  prompter:ask_question:303 Asking question <qutebrowser.utils.usertypes.Question text='Save file to:' mode=<PromptMode.text: 2> default='GoboLinux-015-i686.iso'>, blocking False, loops [], queue deque([])
[...]
17:22:14 DEBUG    downloads  networkmanager:on_adopted_download_destroyed:224 Adopted download destroyed, 0 left.
17:22:16 ERROR    misc       app:_exception_hook:520 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/downloads.py", line 513, in on_read_timer_timeout
    raise OSError("Reply is closed!")
OSError: Reply is closed!
17:22:16 ERROR    misc       app:_exception_hook:517 ARGH, there was an exception while the crash dialog is already shown:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/mainwindow.py", line 368, in closeEvent
    self._tabbed_browser.shutdown()
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 211, in shutdown
    self._remove_tab(tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 259, in _remove_tab
    tab.shutdown()
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/webview.py", line 318, in shutdown
    if download_manager.has_downloads_with_nam(nam):
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/downloads.py", line 805, in has_downloads_with_nam
    download.reply.manager() is nam)
RuntimeError: wrapped C/C++ object of type QNetworkReply has been deleted
```

**Comment by The-Compiler** [comment]
According to the reporter the connection went down shorly before the download was finished, it was shown in red, and he middle-clicked it.

**Comment by The-Compiler** [comment]
I've not seen the first error so far, but I can reproduce the second one like this:

* Start a download
* Close the tab where the download was running
* Provoke the error, e.g. by restarting the httpd
* Retry the download

**Comment by The-Compiler** [comment]
Better debug log:

```
downloads  downloads:fetch:705 fetch: PyQt5.QtCore.QUrl('http://draco.the-compiler.org:8000/100mb.bin') -> 100mb.bin
[...]
statusbar  prompter:ask_question:303 Asking question <qutebrowser.utils.usertypes.Question text='Save file to:' default='100mb.bin' mode=<PromptMode.text: 2>>, blocking False, loops [], queue deque([])
[...]
downloads  downloads:set_filename:423 Setting filename to 100mb.bin
downloads  downloads:set_fileobj:443 buffer: 1024 bytes
[...]
commands   command:run:487 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
destroy    webview:shutdown:309 Shutting down <qutebrowser.browser.webview.WebView tab_id=0 url='http://draco.the-compiler.org:8000/'>.
downloads  downloads:has_downloads_with_nam:867 Found running/failed downloads, adopting the NAM.
[...]
misc       objreg:on_destroyed:118 schedule removal: 0
misc       objreg:on_destroyed:118 schedule removal: webview
misc       objreg:on_destroyed:118 schedule removal: hintmanager
misc       objreg:_on_destroyed:123 removed: 0
misc       objreg:_on_destroyed:123 removed: webview
misc       objreg:_on_destroyed:123 removed: hintmanager
[...]
qt         Unknown module:none:0 QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 136, in main
    ret = qt_mainloop()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 127, in qt_mainloop
    return app.exec_()  # pylint: disable=maybe-no-member
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloads.py", line 517, in on_reply_error
    self._die(self.reply.errorString())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloads.py", line 299, in _die
    self.reply.abort()

misc       message:error:213 Download error: Connection closed
[...]
downloads  downloads:cancel:351 cancelled
downloads  downloads:fetch:705 fetch: PyQt5.QtCore.QUrl('http://draco.the-compiler.org:8000/100mb.bin') -> 100mb.bin
statusbar  prompter:ask_question:303 Asking question <qutebrowser.utils.usertypes.Question text='Save file to:' default='100mb.bin' mode=<PromptMode.text: 2>>, blocking False, loops [], queue deque([])
[...]
downloads  networkmanager:on_adopted_download_destroyed:235 Adopted download destroyed, 0 left.
misc       app:_exception_hook:550 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloads.py", line 522, in on_read_timer_timeout
    if not self.reply.isOpen():
RuntimeError: wrapped C/C++ object of type QNetworkReply has been deleted
destroy    mainwindow:closeEvent:370 Closing window 0
destroy    webview:shutdown:309 Shutting down <qutebrowser.browser.webview.WebView tab_id=1 url='about:blank'>.
misc       app:_exception_hook:547 ARGH, there was an exception while the crash dialog is already shown:
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 371, in closeEvent
    self._tabbed_browser.shutdown()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 237, in shutdown
    self._remove_tab(tab)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 285, in _remove_tab
    tab.shutdown()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webview.py", line 313, in shutdown
    self.page().shutdown()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webpage.py", line 222, in shutdown
    if download_manager.has_downloads_with_nam(nam):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloads.py", line 862, in has_downloads_with_nam
    download.reply.manager() is nam)
RuntimeError: wrapped C/C++ object of type QNetworkReply has been deleted
```

Full logs: http://paste.the-compiler.org/view/cb1ca19e

Also note `python3 -m http.server` is quite useful to reproduce this.

Note how `on_adopted_download_destroyed` is called which probably shouldn't...

**Comment by The-Compiler** [comment]
Partially working patch:

```diff
diff --git a/qutebrowser/browser/downloads.py b/qutebrowser/browser/downloads.py
index b5fe94b..033348b 100644
--- a/qutebrowser/browser/downloads.py
+++ b/qutebrowser/browser/downloads.py
@@ -868,6 +868,7 @@ class DownloadManager(QAbstractListModel):
                                     "adopting the NAM.")
                 nam.adopted_downloads += 1
                 download.destroyed.connect(nam.on_adopted_download_destroyed)
+                download.do_retry.connect(nam.on_adopted_download_retried)
         return nam.adopted_downloads
 
     def can_clear(self):
diff --git a/qutebrowser/browser/network/networkmanager.py b/qutebrowser/browser/network/networkmanager.py
index e601607..12f8fe6 100644
--- a/qutebrowser/browser/network/networkmanager.py
+++ b/qutebrowser/browser/network/networkmanager.py
@@ -237,6 +237,13 @@ class NetworkManager(QNetworkAccessManager):
         if self.adopted_downloads == 0:
             self.deleteLater()
 
+    @pyqtSlot()
+    def on_adopted_download_retried(self):
+        """Called when a download is about to get retried."""
+        self.adopted_downloads += 1
+        log.downloads.debug("Adopted download retried, {} left.".format(
+            self.adopted_downloads))
+
     # WORKAROUND for:
     # http://www.riverbankcomputing.com/pipermail/pyqt/2014-September/034806.html
     #
```

This however doesn't decrement the adopted download count when the retried one is finished.
