### ISSUE TITLE
Tab switches widget focus / QtValueError in download model

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#504]
When in prompt mode (e.g. on https://cmpl.cc/), pressing <kbd>Tab</kbd> once or twice switches focus to the download view (which shouldn't happen).

When pressing <kbd>Ctrl-C</kbd> there, we get this exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/downloads.py", line 886, in data
    qtutils.ensure_valid(index)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/qtutils.py", line 127, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: <PyQt5.QtCore.QModelIndex object at 0x7f276c6b3cf8> is not valid
```

So it seems Qt itself calls `DownloadManager.data` with an invalid `QModelIndex` - should we remove that check even if the tab-bug is fixed?

**Comment by The-Compiler** [comment]
It seems it's still somehow possible to focus the download view (got 2 more reports):

> Uh, I was on the http://www.animereactor.dk/aegisub/webassdraw/ tab when I pressed ^C in the browser...

```
16:00:21 DEBUG    statusbar  prompter:ask_question:304 Asking question <qutebrowser.utils.usertypes.Question default=None mode=<PromptMode.alert: 4> text='[js alert] m 100 100 l 100 200 200 200 b 300 200 b 300 100 b 200 100 m 300 300 l 320 360 360 320'>, blocking True, loops [], queue deque([])
16:00:21 DEBUG    modes      prompter:_display_question:183 Question asked, focusing <qutebrowser.mainwindow.statusbar.prompt.PromptLineEdit>
16:00:21 DEBUG    statusbar  bar:_set_prompt_active:294 Setting prompt_active to True
16:00:21 DEBUG    modes      modeman:enter:240 Entering mode KeyMode.prompt (reason: question asked)
16:00:21 DEBUG    statusbar  text:set_text:59 Setting normal text to '-- PROMPT MODE --'.
16:00:21 DEBUG    webview    webview:on_mode_entered:460 Ignoring focus because mode KeyMode.prompt was entered.
16:00:21 DEBUG    webview    webview:on_mode_entered:460 Ignoring focus because mode KeyMode.prompt was entered.
16:00:21 DEBUG    webview    webview:on_mode_entered:460 Ignoring focus because mode KeyMode.prompt was entered.
16:00:21 DEBUG    webview    webview:on_mode_entered:460 Ignoring focus because mode KeyMode.prompt was entered.
16:00:21 DEBUG    webview    webview:on_mode_entered:460 Ignoring focus because mode KeyMode.prompt was entered.
16:00:21 DEBUG    webview    webview:on_mode_entered:460 Ignoring focus because mode KeyMode.prompt was entered.
16:00:21 DEBUG    webview    webview:on_mode_entered:460 Ignoring focus because mode KeyMode.prompt was entered.
16:00:21 DEBUG    webview    webview:on_mode_entered:460 Ignoring focus because mode KeyMode.prompt was entered.
16:00:24 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='prompt' warn=False>
16:00:24 DEBUG    commands   command:run:489 command called: leave-mode
16:00:24 DEBUG    commands   command:run:503 Calling qutebrowser.keyinput.modeman.ModeManager.leave_current_mode(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.prompt: 5>>)
16:00:24 DEBUG    modes      modeman:leave:283 Leaving mode KeyMode.prompt (reason: leave current)
16:00:24 DEBUG    statusbar  text:set_text:59 Setting normal text to ''.
16:00:24 DEBUG    statusbar  bar:_set_prompt_active:294 Setting prompt_active to False
16:00:24 DEBUG    statusbar  bar:_hide_prompt_widget:412 Hiding prompt widget, queue: deque([])
16:00:24 DEBUG    modes      tabbedbrowser:on_mode_left:501 Left status-input mode, focusing <qutebrowser.browser.webview.WebView tab_id=11 url='http://www.animereactor.dk/aegisub/webassdraw/'>
16:00:24 DEBUG    webview    webview:on_mode_left:488 Restoring focus policy because mode KeyMode.prompt was left.
16:00:24 DEBUG    webview    webview:on_mode_left:488 Restoring focus policy because mode KeyMode.prompt was left.
16:00:24 DEBUG    webview    webview:on_mode_left:488 Restoring focus policy because mode KeyMode.prompt was left.
16:00:24 DEBUG    webview    webview:on_mode_left:488 Restoring focus policy because mode KeyMode.prompt was left.
16:00:24 DEBUG    webview    webview:on_mode_left:488 Restoring focus policy because mode KeyMode.prompt was left.
16:00:24 DEBUG    webview    webview:on_mode_left:488 Restoring focus policy because mode KeyMode.prompt was left.
16:00:24 DEBUG    webview    webview:on_mode_left:488 Restoring focus policy because mode KeyMode.prompt was left.
16:00:24 DEBUG    webview    webview:on_mode_left:488 Restoring focus policy because mode KeyMode.prompt was left.
16:00:24 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=11 url='http://www.animereactor.dk/aegisub/webassdraw/'>)
16:00:24 DEBUG    statusbar  prompter:_restore_ctx:137 Restoring context None
16:00:24 DEBUG    statusbar  bar:_set_prompt_active:294 Setting prompt_active to False
16:00:24 DEBUG    statusbar  bar:_hide_prompt_widget:412 Hiding prompt widget, queue: deque([])
16:00:24 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: True
16:00:25 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:00:25 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
16:00:25 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x1000022 / text: ''
16:00:25 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
16:00:25 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=11 url='http://www.animereactor.dk/aegisub/webassdraw/'>)
16:02:41 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
16:02:45 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:02:45 DEBUG    keyboard   basekeyparser:_debug_log:107 No binding found for tab.
16:02:45 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x1000001 / text: '	'
16:02:45 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
16:02:45 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab True --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=11 url='http://www.animereactor.dk/aegisub/webassdraw/'>)
16:02:45 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
16:02:45 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:02:45 DEBUG    keyboard   basekeyparser:_debug_log:107 No binding found for tab.
16:02:45 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x1000001 / text: '	'
16:02:45 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
16:02:45 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab True --> filter: True (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
16:02:46 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: True
16:02:47 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:02:47 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
16:02:47 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x1000021 / text: ''
16:02:47 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
16:02:47 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
16:02:47 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:02:47 DEBUG    commands   command:run:489 command called: enter-mode ['passthrough']
16:02:47 DEBUG    commands   command:run:503 Calling qutebrowser.keyinput.modeman.ModeManager.enter_mode(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.normal: 1>>, 'passthrough')
16:02:47 DEBUG    modes      modeman:enter:240 Entering mode KeyMode.passthrough (reason: command)
16:02:47 DEBUG    statusbar  text:set_text:59 Setting normal text to '-- PASSTHROUGH MODE --'.
16:02:47 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: True (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
16:02:48 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: True
16:02:48 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
16:02:49 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
16:02:49 DEBUG    commands   command:run:489 command called: leave-mode
16:02:49 DEBUG    commands   command:run:503 Calling qutebrowser.keyinput.modeman.ModeManager.leave_current_mode(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.passthrough: 7>>)
16:02:49 DEBUG    modes      modeman:leave:283 Leaving mode KeyMode.passthrough (reason: leave current)
16:02:49 DEBUG    statusbar  text:set_text:59 Setting normal text to ''.
16:02:49 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
16:02:49 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: True
16:02:49 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:02:49 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
16:02:49 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x1000021 / text: ''
16:02:49 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
16:02:49 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
16:02:49 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:02:49 DEBUG    keyboard   basekeyparser:_debug_log:107 No binding found for ctrl+c.
16:02:49 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x43 / text: ''
16:02:49 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
16:02:49 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
16:02:49 ERROR    misc       crashsignal:exception_hook:207 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/downloads.py", line 1024, in data
    qtutils.ensure_valid(index)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/qtutils.py", line 127, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: <PyQt5.QtCore.QModelIndex object at 0x7f7cd52a5518> is not valid
```

```
...
18:01:30 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:30 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:30 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True, is_tab True --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=38 url='https://labxnow.org/labxweb/projects'>)
18:01:30 INFO     webview    networkmanager:createRequest:352 Request to s.youtube.com blocked by host blocker.
18:01:30 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:31 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:31 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:31 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:31 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:31 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:31 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:31 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:31 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:31 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:31 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:31 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:32 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:32 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:32 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True, is_tab True --> filter: True (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:32 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: True
18:01:36 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:36 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:36 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:38 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:38 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:38 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:38 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:38 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:38 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:38 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:38 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:38 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:39 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:39 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:39 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:39 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:39 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:39 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:39 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:39 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:39 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:39 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:39 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:39 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: False
18:01:44 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:44 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:44 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.passthrough - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='passthrough' warn=True>
18:01:44 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.downloadview.DownloadView count=0>)
18:01:44 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/downloads.py", line 1066, in data
    qtutils.ensure_valid(index)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/qtutils.py", line 147, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: <PyQt5.QtCore.QModelIndex object at 0x7fcb80064908> is not valid
```

**Comment by The-Compiler** [comment]
I can reproduce this by starting `qutebrowser --temp-basedir about:blank`, then pressing <kbd>Tab</kbd> and <kbd>Ctrl+C</kbd>
