### ISSUE TITLE
Queue error messages until window is visible.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#512]
Existing workarounds:

* d8fe62bc61eebcc1088a9230ceca157034adbd98
* 46a3e2af9203dc31265c760685cfec5e1448f7dc

Instead we should find some way to queue messages, notify the message handler when the first window is available, and reply them then.

**Comment by The-Compiler** [comment]
Related crash reports on 2da45e9:

```
11:18:10 DEBUG    init       app:__init__:156 Init done!
11:18:10 ERROR    misc       app:_exception_hook:550 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line 188, in _get_window_registry
    return win.registry
AttributeError: 'NoneType' object has no attribute 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/message.py", line 40, in <lambda>
    0, lambda: _get_bridge(win_id).error(message, immediately))
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/message.py", line 29, in _get_bridge
    return objreg.get('message-bridge', scope='window', window=win_id)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line 215, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line 204, in _get_registry
    return _get_window_registry(window)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line 190, in _get_window_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
```
