### ISSUE TITLE
Invalid QModelIndex in completion model

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#528]
On v0.1.3 with Qt 5.4.0 on OS X

Exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/qutebrowser/completion/models/base.py", line 98, in flags
    qtutils.ensure_valid(index)
  File "/usr/local/lib/python3.4/site-packages/qutebrowser/utils/qtutils.py", line 127, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: <PyQt5.QtCore.QModelIndex object at 0x126e382e8> is not valid
```

Log:

```
keyboard   basekeyparser:_debug_log:103 Definitive match for 'O'.
commands   command:run:468 command called: set-cmd-text [':open -t ']
commands   command:run:482 Calling qutebrowser.mainwindow.statusbar.command.Command.set_cmd_text_command(<qutebrowser.mainwindow.statusbar.command.Command>, ':open -t ')
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
modes      command:set_cmd_text:92 Setting command text, focusing <qutebrowser.mainwindow.statusbar.command.Command>
modes      modeman:enter:254 Entering mode KeyMode.command (reason: cmd focus)
statusbar  text:set_text:59 Setting normal text to '-- COMMAND MODE --'.
webview    webview:on_mode_entered:426 Ignoring focus because mode KeyMode.command was entered.
modes      modeman:_eventFilter_keypress:204 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: True (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t']: QuickmarkCompletionModel, with pattern ''
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keyrelease:225 filter: True
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 't'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 't'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 't'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 't']: QuickmarkCompletionModel, with pattern 't'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 'tr'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 'tr'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 'tr'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 'tr']: QuickmarkCompletionModel, with pattern 'tr'
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 'tra'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 'tra'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 'tra'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 'tra']: QuickmarkCompletionModel, with pattern 'tra'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 'tran'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 'tran'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 'tran'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 'tran']: QuickmarkCompletionModel, with pattern 'tran'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 'trans'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 'trans'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 'trans'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 'trans']: QuickmarkCompletionModel, with pattern 'trans'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keyrelease:225 filter: True
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
commands   command:run:468 command called: completion-item-next
commands   command:run:482 Calling qutebrowser.completion.completionwidget.CompletionView.completion_item_next(<qutebrowser.completion.completionwidget.CompletionView>)
modes      modeman:_eventFilter_keypress:204 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True --> filter: True (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
modes      modeman:_eventFilter_keyrelease:225 filter: True
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 'tran'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 'tran'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 'tran'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 'tran']: QuickmarkCompletionModel, with pattern 'tran'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 'tra'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 'tra'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 'tra'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 'tra']: QuickmarkCompletionModel, with pattern 'tra'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 'tr'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 'tr'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 'tr'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 'tr']: QuickmarkCompletionModel, with pattern 'tr'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 't'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 't'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 't'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 't']: QuickmarkCompletionModel, with pattern 't'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t']: QuickmarkCompletionModel, with pattern ''
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', '1'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', '1'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', '1'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', '1']: QuickmarkCompletionModel, with pattern '1'
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', '10'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', '10'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', '10'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', '10']: QuickmarkCompletionModel, with pattern '10'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keyrelease:225 filter: True
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
modes      modeman:_eventFilter_keypress:204 handled: False, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: False (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', '10.'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', '10.'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', '10.'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', '10.']: QuickmarkCompletionModel, with pattern '10.'
modes      modeman:_eventFilter_keyrelease:225 filter: False
modes      modeman:_eventFilter_keypress:180 got keypress in mode KeyMode.command - calling handler qutebrowser.keyinput.basekeyparser.BaseKeyParser.handle
commands   command:run:468 command called: completion-item-next
commands   command:run:482 Calling qutebrowser.completion.completionwidget.CompletionView.completion_item_next(<qutebrowser.completion.completionwidget.CompletionView>)
completion completer:change_completed_part:413 changing part 2 to 'http://10.25.1.6/'
completion completer:schedule_completion_update:268 Scheduling completion update.
completion completer:schedule_completion_update:265 Ignoring update because there were no changes.
completion completer:change_completed_part:431 Placing cursor after ':open -t http://10.25.1.6/ '
modes      completer:change_completed_part:432 Completion triggered, focusing <qutebrowser.completion.completer.Completer>
modes      modeman:_eventFilter_keypress:204 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True --> filter: True (focused: <qutebrowser.mainwindow.statusbar.command.Command>)
completion completer:update_cursor_part:399 cursor_part 2, spaces False
completion completer:update_completion:281 Updating completion - prefix :, parts ['open', '-t', 'http://10.25.1.6/'], cursor_part 2
completion completer:_get_new_completion:184 Before filtering flags: parts ['open', '-t', 'http://10.25.1.6/'], cursor_part 2
completion completer:_get_new_completion:187 After filtering flags: parts ['open', 'http://10.25.1.6/'], cursor_part 1
completion completer:_get_new_completion:211 completions: *quickmark_by_url*
completion completer:update_completion:320 New completion for ['open', '-t', 'http://10.25.1.6/']: QuickmarkCompletionModel, with pattern 'http://10.25.1.6/'
qt         Unknown module:none:0 QSortFilterProxyModel: index from wrong model passed to mapFromSource
misc       app:_exception_hook:513 Uncaught exception
```

**Comment by athrabeth** [comment]
i haven't been able to reproduce it regularly, but its happened several times before and since, all around opening from quickmarks. most of the time (actually all except this time) the error dialog states the crash was in pyqt. this was the only time i saw the report dialog. last night i upgraded from 5.3.2 to 5.4 and i haven't had the crash yet.

**Comment by athrabeth** [comment]
here's the contents of my quickmarks:

```
facebook https://www.facebook.com/
aeg http://alderac.com/forum/search.php?search_id=newposts
spiderclan forum http://www.spiderclan.net/search.php?search_id=newposts
deluge http://10.0.0.37:8112/
sickbeard http://10.0.0.37:8081/comingEpisodes
twitter https://twitter.com/
tumblr https://www.tumblr.com/dashboard
simple bank https://bank.simple.com/activity
storium https://storium.com/
fever http://mournival.org/fever/
~
```

**Comment by The-Compiler** [comment]
Thanks for the information! Though I'm a bit confused:

* The log says this was on Qt 5.4.0 already, not 5.3.2. Can you confirm this?
* In the log I see `10.` being completed to `http://10.25.1.6/` - though I don't see this anywhere in your quickmarks. How did that completion happen? Your file above ends with `~`, is that intended?

I wonder if it's a race condition which was introduced in fb3682f5fa9ff702488277521e60c5425cafc64d - maybe the `QTimer` used to update the completion somehow sets a new model while the view still operates on the old one?

**Comment by The-Compiler** [comment]
Closing this because of inactivity.
