### ISSUE TITLE
IndexError when doing tab-clone with tabs-are-windows=true

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#536]
After doing `:set -t tabs tabs-are-windows true`, doing `:tab-clone` will give us this exception:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 111, in eventFilter
    return modeman.eventFilter(obj, event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 345, in eventFilter
    return self._eventFilter_keypress(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 178, in _eventFilter_keypress
    handled = handler(event) if handler is not None else False
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 305, in handle
    match = self._handle_single_key(e)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeparsers.py", line 69, in _handle_single_key
    match = super()._handle_single_key(e)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 196, in _handle_single_key
    self.execute(binding, self.Type.chain, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyparser.py", line 42, in execute
    self._commandrunner.run(cmdstr, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 301, in run
    self._cmd.run(self._win_id, args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 497, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 394, in tab_clone
    tabbed_browser.set_page_title(idx, cur_title)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabwidget.py", line 87, in set_page_title
    self.tabBar().set_tab_data(idx, 'page-title', title.replace('&', '&&'))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabwidget.py", line 245, in set_tab_data
    idx, self.count()))
IndexError: Tab index (-1) out of range (1)!
```

Logs:

```
commands   command:run:496 Calling qutebrowser.browser.commands.CommandDispatcher.tab_clone(<qutebrowser.browser.commands.CommandDispatcher>, False, False)
webview    tabbedbrowser:tabopen:347 Creating new tab with URL None
init       mainwindow:__init__:88 Initial mainwindow geometry: PyQt5.QtCore.QRect(50, 50, 800, 600)
init       mainwindow:__init__:93 Initializing downloads...
init       networkmanager:__init__:75 Initializing NetworkManager
init       networkmanager:__init__:80 NetworkManager init done
statusbar  bar:_hide_cmd_widget:308 Hiding cmd widget, queue: deque([])
statusbar  bar:_set_prompt_active:245 Setting prompt_active to False
statusbar  bar:_hide_prompt_widget:336 Hiding prompt widget, queue: deque([])
init       mainwindow:__init__:117 Initializing search...
init       mainwindow:__init__:122 Initializing modes...
webview    tabbedbrowser:tabopen:347 Creating new tab with URL None
init       networkmanager:__init__:75 Initializing NetworkManager
init       networkmanager:__init__:80 NetworkManager init done
webview    tabbedbrowser:_get_new_tab_idx:400 new-tab-position last -> opening new tab at -1, next left: 0 / right: -1
modes      tabbedbrowser:on_current_changed:548 Current tab changed, focusing <qutebrowser.browser.webview.WebView url='' tab_id=1>
modes      modeman:maybe_leave:93 Not in mode KeyMode.hint! (leave reason: tab changed)
modes      modeman:maybe_leave:93 Not in mode KeyMode.insert! (leave reason: tab changed)
misc       app:_exception_hook:550 Uncaught exception
```

**Comment by The-Compiler** [comment]
Using `:back -w` is broken as well.

Logs:

```
DEBUG    commands   command:run:496 Calling qutebrowser.browser.commands.CommandDispatcher.back(<qutebrowser.browser.commands.CommandDispatcher>, False, False, True, 1)
DEBUG    init       mainwindow:__init__:88 Initial mainwindow geometry: PyQt5.QtCore.QRect(50, 50, 800, 600)
DEBUG    init       mainwindow:__init__:93 Initializing downloads...
DEBUG    init       networkmanager:__init__:75 Initializing NetworkManager
DEBUG    init       networkmanager:__init__:80 NetworkManager init done
DEBUG    statusbar  bar:_hide_cmd_widget:308 Hiding cmd widget, queue: deque([])
DEBUG    statusbar  bar:_set_prompt_active:245 Setting prompt_active to False
DEBUG    statusbar  bar:_hide_prompt_widget:336 Hiding prompt widget, queue: deque([])
DEBUG    init       mainwindow:__init__:117 Initializing search...
DEBUG    init       mainwindow:__init__:122 Initializing modes...
ERROR    misc       app:_exception_hook:550 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 111, in eventFilter
    return modeman.eventFilter(obj, event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 345, in eventFilter
    return self._eventFilter_keypress(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 178, in _eventFilter_keypress
    handled = handler(event) if handler is not None else False
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 305, in handle
    match = self._handle_single_key(e)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeparsers.py", line 69, in _handle_single_key
    match = super()._handle_single_key(e)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 196, in _handle_single_key
    self.execute(binding, self.Type.chain, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyparser.py", line 42, in execute
    self._commandrunner.run(cmdstr, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 301, in run
    self._cmd.run(self._win_id, args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 497, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 431, in back
    self._back_forward(tab, bg, window, count, forward=False)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 411, in _back_forward
    widget = self.tab_clone(bg, window)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 391, in tab_clone
    cur_title = tabbed_browser.page_title(self._current_index())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabwidget.py", line 92, in page_title
    return self.tabBar().page_title(idx)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabwidget.py", line 270, in page_title
    return self.tab_data(idx, 'page-title')
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabwidget.py", line 256, in tab_data
    idx, self.count()))
IndexError: Tab index (0) out of range (0)!
```

**Comment by The-Compiler** [comment]
bisected to 66d3ec1c081e4a99890f26b0777233f3ae382d7f
