### ISSUE TITLE
Segfault on cross-code

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#605]
When loading http://www.cross-code.com/en/start we get a segfault in qutebrowser and QupZilla, but not with Otter, Rekonq or the demo browser.

Output and stacktrace:

```
(python3:20051): GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gstsystemclock: write control failed in wakeup_async: 24:Too many open files


(python3:20051): GStreamer-CRITICAL **: gst_poll_free: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gstsystemclock: write control failed in wakeup_async: 24:Too many open files


(python3:20051): GStreamer-CRITICAL **: gst_poll_free: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gstsystemclock: write control failed in wakeup_async: 24:Too many open files


(python3:20051): GStreamer-CRITICAL **: gst_poll_free: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gst_poll_get_read_gpollfd: assertion 'set != NULL' failed

(python3:20051): GStreamer-CRITICAL **: gst_bus_create_watch: assertion 'bus->priv->poll != NULL' failed

(python3:20051): GLib-CRITICAL **: g_source_set_callback: assertion 'source != NULL' failed
[New Thread 0x7ffe91f1b700 (LWP 20328)]
[...]
[New Thread 0x7ffff3f1e700 (LWP 20055)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff10de2e4 in g_source_attach () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff10de2e4 in g_source_attach () from /usr/lib/libglib-2.0.so.0
#1  0x00007fffe346b258 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#2  0x00007fffe346b55e in gst_bus_add_signal_watch_full () from /usr/lib/libgstreamer-1.0.so.0
#3  0x00007fffe4fe98b0 in WebCore::MediaPlayerPrivateGStreamer::createGSTPlayBin (this=0x7fff6435b700)
    at platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:1597
#4  0x00007fffe4fe9ed8 in WebCore::MediaPlayerPrivateGStreamer::load (this=0x7fff6435b700, url=...)
    at platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:292
#5  0x00007fffe4fe2813 in WebCore::MediaPlayer::loadWithNextMediaEngine (this=this@entry=0x7fff6435a960, 
    current=current@entry=0x0) at platform/graphics/MediaPlayer.cpp:447
#6  0x00007fffe4fe2c62 in WebCore::MediaPlayer::load (this=0x7fff6435a960, url=..., contentType=..., 
    keySystem=...) at platform/graphics/MediaPlayer.cpp:392
#7  0x00007fffe58b45ea in WebCore::HTMLMediaElement::loadResource (this=this@entry=0x5555585e8000, 
    initialURL=..., contentType=..., keySystem=...) at html/HTMLMediaElement.cpp:1111
#8  0x00007fffe58b4bc8 in WebCore::HTMLMediaElement::selectMediaResource (this=this@entry=0x5555585e8000)
    at html/HTMLMediaElement.cpp:985
#9  0x00007fffe58be336 in WebCore::HTMLMediaElement::loadInternal (this=this@entry=0x5555585e8000)
    at html/HTMLMediaElement.cpp:918
#10 0x00007fffe58d5451 in WebCore::HTMLMediaElement::load (this=0x5555585e8000)
    at html/HTMLMediaElement.cpp:785
#11 0x00007fffe53766b7 in WebCore::jsHTMLMediaElementPrototypeFunctionLoad (exec=<optimized out>)
    at generated/JSHTMLMediaElement.cpp:810
#12 0x00007fff97fff0e5 in ?? ()
#13 0x0000000000000200 in ?? ()
#14 0x00007fff980b77ff in ?? ()
#15 0x00007fffdc0cc9c0 in ?? ()
#16 0x00007fff6aea3a90 in ?? ()
#17 0x00007fff6ae95300 in ?? ()
#18 0x00007fff8dbd25b0 in ?? ()
#19 0x00007fff98073d1f in ?? ()
#20 0x00007fff8c0d6a00 in ?? ()
#21 0x0000000000000080 in ?? ()
#22 0x00007fff0000003f in ?? ()
#23 0x000000000000000a in ?? ()
#24 0x00007fff97fff280 in ?? ()
#25 0x00007fffdc0cd210 in ?? ()
#26 0x00007fff942e8470 in ?? ()
#27 0x0000000000000000 in ?? ()

```

**Comment by The-Compiler** [comment]
Now it doesn't load at all anymore with 5.5 beta, so merging this into #656
