### ISSUE TITLE
Use decorators instead of function annotations for `cmdutils.register`

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#637]
Currently we make use of Python [function annotations](https://www.python.org/dev/peps/pep-3107/) for our own purposes, for special/typed parameters for commands (see [CONTRIBUTING](https://github.com/The-Compiler/qutebrowser/blob/master/CONTRIBUTING.asciidoc#commands)).

Examples where this is used currently:

```python
@cmdutils.register(instance='search-runner', hide=True, scope='window')
def search_next(self, count: {'special': 'count'}=1):
```

```python
@cmdutils.register(name='set', instance='config',
                   completion=[Completion.section, Completion.option,
                               Completion.value])
def set_command(self, win_id: {'special': 'win_id'},
                sectname: {'name': 'section'}=None,
                optname: {'name': 'option'}=None, value=None, temp=False,
                print_val: {'name': 'print'}=False):
```

```python
@cmdutils.register(name=['session-save', 'w'],
                   completion=[usertypes.Completion.sessions],
                   instance='session-manager')
def session_save(self, win_id: {'special': 'win_id'},
                 name: {'type': str}=default, current=False, quiet=False,
                 force=False):
```

As the annotations will be reserved for [type hints](https://www.python.org/dev/peps/pep-0484/) with Python 3.5 (?) we should get rid of them and move the information to the decorator instead, e.g. like so:

For `{'special': ...}` we can probably just add a `count_arg`/`win_id_arg` argument to `cmdutils.register`:

```python
@cmdutils.register(instance='search-runner', hide=True, scope='window',
                   count_arg='count')
def search_next(self, count=1):
```

For renaming of args, a separate decorator might be better:

(TBD: should `rename_args` really be a separate decorator? Should we pass a
dict instead of kwargs?)

```python
@cmdutils.register(name='set', instance='config',
                   completion=[Completion.section, Completion.option,
                               Completion.value],
                   win_id_arg='win_id')
@cmdutils.rename_args(sectname='section', optname='option', print_val='print')
def set_command(self, win_id, sectname=None, optname=None, value=None,
                temp=False, print_val=False):
```

For types, we can keep the annotations as they'll double as Python and as command type annotations:

```python
@cmdutils.register(name=['session-save', 'w'],
                   completion=[usertypes.Completion.sessions],
                   instance='session-manager')
def session_save(self, win_id, name: str=default, current=False, quiet=False,
                 force=False):
```

**Comment by The-Compiler** [comment]
After a first cleanup, those are remaining:

```python
qutebrowser/browser/commands.py
558:    def scroll(self, dx: {'type': float}, dy: {'type': float}, count=1):
574:    def scroll_perc(self, perc: {'type': float}=None,
591:    def scroll_page(self, x: {'type': float}, y: {'type': float}, count=1):
656:    def zoom(self, zoom: {'type': int}=None, count=None):

qutebrowser/misc/utilcmds.py
38:def later(ms: {'type': int}, command, win_id):
67:def repeat(times: {'type': int}, command, win_id):

qutebrowser/misc/sessions.py
329:    def session_save(self, win_id, name: {'type': str}=default, current=False,
```

Those map 1:1 to Python type annotations.

```python
qutebrowser/browser/commands.py
512:    def navigate(self, where: {'type': ('prev', 'next', 'up', 'increment',
763:    def tab_focus(self, index: {'type': (int, 'last')}=None, count=None):
788:    def tab_move(self, direction: {'type': ('+', '-')}=None, count=None):

qutebrowser/misc/utilcmds.py
112:def debug_crash(typ: {'type': ('exception', 'segfault')}='exception'):
```

Not sure what to do here exactly. Does Python have a type annotation for, essentially, enums?

```python
qutebrowser/browser/commands.py
867:    def run_userscript(self, cmd, *args: {'nargs': '*'}):

qutebrowser/misc/savemanager.py
188:    def save_command(self, win_id, *what: {'nargs': '*'}):
```

I guess the goal of those was to make those arguments optional and `+` was the default? Then maybe `@cmdutils.register` needs a `star_arg_optional` or whatever parameter?

**Comment by The-Compiler** [comment]
After some thought about this, it'd probably be best to add a new `@cmdutils.arg` decorator, [similar to `click`](http://click.pocoo.org/5/api/#click.argument).

---

For trivial scenarios, we could re-use `typing` annotations:

```python
@cmdutils.register()
def scroll_page(x: float, y: float):
    pass
```

---

For things like `:tab-focus` we'd have a little duplication:

```python
@cmdutils.register()
@cmdutils.arg('index', type=(int, 'last'))
def tab_focus(index: typing.Union[int, str]):
    pass
```

current:

```python
@cmdutils.register()
def tab_focus(self, index: {'type': (int, 'last')}=None, count=None):
    pass
```

An alternative would be to check `__union_params__` on the `typing.Union`
annotation and rename `type` to `choices` (which would only apply if the
argument can't be parsed according via `int()` according to the union type), but
that sounds like too much magic

---

For commands supporting string choices only:

```python
@cmdutils.register()
@cmdutils.arg('where', type=('prev', 'next', 'up', 'increment', 'decrement'))
def navigate(where: str):
    pass
```

current:

```python
@cmdutils.register()
def navigate(self, where: {'type': ('prev', 'next', 'up', 'increment',
                                    'decrement')}):
    pass
```

---

The `flag` annotation could be handled the same:

```python
@cmdutils.register()
@cmdutils.arg('horizontal', flag='x')
def scroll_perc(..., horizontal=False):
    pass
```

current:

```python
@cmdutils.register(flags={'horizontal': 'x'})
def scroll_perc(self, ..., horizontal=False):
    pass
```

---

And special args like `count` as well:

```python
@cmdutils.register()
@cmdutils.arg('count', count=True)
def zoom(..., count=None):
    pass
```

current:

```python
@cmdutils.register(count='count')
def zoom(..., count=None):
    pass
```

---

Random notes:

- `cmdutils.arg` would ensure the given string is a valid argument, and then
  save the info into a `_qute_arginfo` dict attached to the function
- `cmdutils.register` reads `_qute_arginfo` if present, and sets it to some
  sentinel (`None`?)
- `cmdutils.arg` checks the sentinel and fails if it's set so we don't
  accidentally use it after (i.e. above) `cmdutils.register`

**Comment by rcorre** [comment]
This sounds like it could eventually enable arg completions as well (e.g. a completion menu for `bind --mode=`)

**Comment by The-Compiler** [comment]
Not yet I think - it's mainly a move from annotations to decorators (see the [annotations branch](https://github.com/The-Compiler/qutebrowser/compare/master...annotations))

**Comment by The-Compiler** [comment]
This is mostly done in the `annotations` branch, but e.g. scrolling still fails:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/argparse.py", line 2286, in _get_value
    result = type_func(arg_string)
  File "/usr/lib64/python3.5/typing.py", line 130, in __new__
    raise TypeError("Cannot instantiate %r" % self.__class__)
TypeError: Cannot instantiate <class 'typing.UnionMeta'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.5/argparse.py", line 1967, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib64/python3.5/argparse.py", line 1923, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.5/argparse.py", line 1816, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python3.5/argparse.py", line 2257, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib64/python3.5/argparse.py", line 2299, in _get_value
    raise ArgumentError(action, msg % args)
argparse.ArgumentError: argument direction: invalid Union value: 'down'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 498, in run
    self.namespace = self.parser.parse_args(args)
  File "/usr/lib64/python3.5/argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.5/argparse.py", line 1765, in parse_known_args
    self.error(str(err))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/argparser.py", line 83, in error
    raise ArgumentParserError(msg.capitalize())
qutebrowser.commands.argparser.ArgumentParserError: Argument direction: invalid union value: 'down'
```
