### ISSUE TITLE
Segfault on OSM page

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#649]
When zooming in on http://www.skolelinux.no/testskoler/map/openlayers.html a lot of RAM is used, and there's a segfault here:

```
#0  0x00007ffff63296c0 in WebCore::ImageBuffer::context() const () from /usr/lib/libQt5WebKit.so.5
#1  0x00007ffff6336c6e in WebCore::BitmapTextureImageBuffer::updateContents(WebCore::TextureMapper*, WebCore::GraphicsLayer*, WebCore::IntRect const&, WebCore::IntPoint const&, WebCore::BitmapTexture::UpdateContentsFlag) ()
   from /usr/lib/libQt5WebKit.so.5
#2  0x00007ffff633c64c in WebCore::TextureMapperTile::updateContents(WebCore::TextureMapper*, WebCore::GraphicsLayer*, WebCore::IntRect const&, WebCore::BitmapTexture::UpdateContentsFlag) () from /usr/lib/libQt5WebKit.so.5
#3  0x00007ffff633dc98 in WebCore::TextureMapperTiledBackingStore::updateContents(WebCore::TextureMapper*, WebCore::GraphicsLayer*, WebCore::FloatSize const&, WebCore::IntRect const&, WebCore::BitmapTexture::UpdateContentsFlag) () from /usr/lib/libQt5WebKit.so.5
#4  0x00007ffff6334606 in WebCore::GraphicsLayerTextureMapper::updateBackingStoreIfNeeded() () from /usr/lib/libQt5WebKit.so.5
#5  0x00007ffff63334dc in WebCore::GraphicsLayerTextureMapper::flushCompositingState(WebCore::FloatRect const&) () from /usr/lib/libQt5WebKit.so.5
#6  0x00007ffff633353b in WebCore::GraphicsLayerTextureMapper::flushCompositingState(WebCore::FloatRect const&) () from /usr/lib/libQt5WebKit.so.5
#7  0x00007ffff633353b in WebCore::GraphicsLayerTextureMapper::flushCompositingState(WebCore::FloatRect const&) () from /usr/lib/libQt5WebKit.so.5
#8  0x00007ffff633353b in WebCore::GraphicsLayerTextureMapper::flushCompositingState(WebCore::FloatRect const&) () from /usr/lib/libQt5WebKit.so.5
#9  0x00007ffff633353b in WebCore::GraphicsLayerTextureMapper::flushCompositingState(WebCore::FloatRect const&) () from /usr/lib/libQt5WebKit.so.5
#10 0x00007ffff633353b in WebCore::GraphicsLayerTextureMapper::flushCompositingState(WebCore::FloatRect const&) () from /usr/lib/libQt5WebKit.so.5
#11 0x00007ffff633353b in WebCore::GraphicsLayerTextureMapper::flushCompositingState(WebCore::FloatRect const&) () from /usr/lib/libQt5WebKit.so.5
#12 0x00007ffff6df9d29 in WebCore::RenderLayerCompositor::flushPendingLayerChanges(bool) () from /usr/lib/libQt5WebKit.so.5
#13 0x00007ffff61a3a73 in WebCore::FrameView::flushCompositingStateForThisFrame(WebCore::Frame*) () from /usr/lib/libQt5WebKit.so.5
#14 0x00007ffff61a3e0f in WebCore::FrameView::paintContents(WebCore::GraphicsContext*, WebCore::IntRect const&) () from /usr/lib/libQt5WebKit.so.5
#15 0x00007ffff5ddbba2 in QWebFrameAdapter::renderRelativeCoords(QPainter*, int, QRegion const&) () from /usr/lib/libQt5WebKit.so.5
#16 0x00007ffff7f92d0e in QWebFrame::render(QPainter*, QFlags<QWebFrame::RenderLayer>, QRegion const&) () from /usr/lib/libQt5WebKitWidgets.so.5
#17 0x00007ffff7f92d31 in QWebFrame::render(QPainter*, QRegion const&) () from /usr/lib/libQt5WebKitWidgets.so.5
#18 0x00007ffff7f9e1b5 in QWebView::paintEvent(QPaintEvent*) () from /usr/lib/libQt5WebKitWidgets.so.5
#19 0x00007ffff52dae08 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff7f9f1eb in QWebView::event(QEvent*) () from /usr/lib/libQt5WebKitWidgets.so.5
#21 0x00007ffff5297acc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff529cf10 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff49b1dbb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#24 0x00007ffff52d4519 in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff52d4b70 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff52a4f10 in QWidgetBackingStore::doSync() () from /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff52a5309 in QWidgetBackingStore::sync() () from /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff52c5f8f in QWidgetPrivate::syncBackingStore() () from /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff52daeb8 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff53ef33b in QMainWindow::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff5297acc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff529cf10 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff49b1dbb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#34 0x00007ffff49b3dfb in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#35 0x00007ffff4a09dc3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /usr/lib/libQt5Core.so.5
#36 0x00007ffff1e729fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#37 0x00007ffff1e72ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#38 0x00007ffff1e72d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#39 0x00007ffff4a0a1b7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#40 0x00007ffff49af852 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#41 0x00007ffff49b722c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#42 0x00005555555dbf6c in main (argc=1, argv=0x7fffffffda38) at main.cpp:51
```

Before reporting this upstream I want to test if it's the same as [QTBUG-44523](https://bugreports.qt.io/browse/QTBUG-44523).

**Comment by The-Compiler** [comment]
Seems to be fixed with Qt 5.5 beta.
