### ISSUE TITLE
NUL-bytes / ValueError in history

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#670]
I have no idea what's going on, but this has been reported by four people already, on 0.2.1/
8edfa42/71608af, Qt 5.4.1, Python 3.4.3, Archlinux and Windows.

## Stacktrace

```
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.2.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.4/site-packages/qutebrowser/qutebrowser.py", line 142, in main
    app = app.Application(args)
  File "/usr/lib/python3.4/site-packages/qutebrowser/app.py", line 142, in __init__
    self._init_modules()
  File "/usr/lib/python3.4/site-packages/qutebrowser/app.py", line 192, in _init_modules
    history.init(self)
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/history.py", line 168, in init
    history = WebHistory(parent)
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/history.py", line 103, in __init__
    self._history_dict[url] = HistoryEntry(atime, url)
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/history.py", line 44, in __init__
    self.atime = float(atime)
ValueError: could not convert string to float: ...
```

## Texts

> After setting the web site history to 0 (to delete the history) and restarting, the browser stopped working. Even after purging the configuration and reinstalling.

---

> Open new session

---

> Had qutebrowser open, rebooted my machine 

## Values

`'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001431512219'`

`'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001431457608'`

---

`'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001431138528'`

---

`'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001430227366'`

---

`'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001432660716'`

## Reports

- http://paste.the-compiler.org/view/bc1dcb50
- http://paste.the-compiler.org/view/46b25dd5
- http://paste.the-compiler.org/view/147470f7

---

- http://paste.the-compiler.org/view/4169d0b9
- http://paste.the-compiler.org/view/3903fa5d
- http://paste.the-compiler.org/view/5f9d57b7

---

- http://paste.the-compiler.org/view/04a64f42
- http://paste.the-compiler.org/view/4873c6d2

**Comment by The-Compiler** [comment]
This could possibly happen when something is seeking past EOF when writing the file:

```
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> f = open('foofile', 'w')
>>> f.seek(100)
100
>>> f.write("foo")
3
>>> f.close()
>>> quit()
$ hexdump -C foofile 
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000060  00 00 00 00 66 6f 6f                              |....foo|
00000067
```

**Comment by The-Compiler** [comment]
Closing this for now as the workaround seems to work fine and I have no idea what's going wrong.

**Comment by The-Compiler** [comment]
```
<Carpetsmoker> So I've beenm getting
<Carpetsmoker> WARNING: Removing NUL bytes from entry ['\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001439555801', 'http://ruby-doc.org/core-2.2.0/Array.html'] - see https://github.com/The-Compiler/qutebrowser/issues/670 [ http://cmpl.cc:8888/9gf | http://cmpl.cc:8888/9gg ]
<Carpetsmoker> consistently when starting Qutebrowser for the last week orso
<Carpetsmoker> Does it remove the null bytes and save?
<Carpetsmoker> Or just remove the null bytes and read and leave the file alone?
<Carpetsmoker> ah, file on disk seems unchanged, is that intentional?
<The-Compiler> Carpetsmoker: it just was a quick workaround - I never had the completion corruption issue, on multiple machines
<Carpetsmoker> I think it happened after my laptop's battery went dead, but I'm not sure
<The-Compiler> I think someone else mentioned they had it while shutting down with qutebrowser open, I should test that too
<Carpetsmoker> I guess that's the same effect: the qutebrowser process being killed
<Carpetsmoker> Perhaps a kill -9 might also do the trick
```

**Comment by The-Compiler** [comment]
FWIW, I just saw the same behaviour in zsh's history file after a hard system freeze:

```
pkgfile -s archlinux.vim
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@: 1452612090:0;cd Downloads
: 1452612091:0;ls
```

**Comment by The-Compiler** [comment]
I still have no clue what's going on here and the workaround works, so I'm closing this...
