### ISSUE TITLE
Tox fails to recreate virtual environment

### ISSUE THREAD

**Issue by moozzz** [The-Compiler/qutebrowser#694]
I pulled the newest version of Qutebrowser today in the morning ("git pull origin master") and tried to recreate the virtual environment via "tox -r -e mkvenv" which failed. Below are the outputs of git pull and tox:

>> git pull origin master

```
Aktualisiere a345b02..534dbfc
Fast-forward
CHANGELOG.asciidoc                                  |   1 +
README.asciidoc                                         |   1 +
doc/help/settings.asciidoc                              |  12 ++++
doc/quickstart.asciidoc                                  |   1 +
qutebrowser/config/configdata.py                  |   4 ++
qutebrowser/mainwindow/tabbedbrowser.py |  11 +++
qutebrowser/mainwindow/tabwidget.py         |  13 ++++
qutebrowser/utils/qtutils.py                           | 124 ++++++++++++++++++++++----------
qutebrowser/utils/urlutils.py                          |  17 ++---
scripts/link_pyqt.py                                      |  11 +--
tests/misc/test_lineparser.py                        |  10 +--
tox.ini                                                           |   9 +--
12 files changed, 151 insertions(+), 63 deletions(-)
```

>> tox -r -e mkvenv

```
mkvenv recreate: /home/maxim/Software/qutebrowser/.venv
ERROR: invocation failed (exit code 1), logfile: /home/maxim/Software/qutebrowser/.venv/log/mkvenv-0.log
ERROR: actionid=mkvenv
msg=getenv
cmdargs=['/usr/bin/python3', '-m', 'virtualenv', '--setuptools', '--python', '/usr/bin/python3', '.venv']
env={'OLDPWD': '/home/maxim/Software', 'LD_LIBRARY_PATH': '/usr/lib/openmpi/lib', 'XDG_RUNTIME_DIR': '/run/user/1000', 'EDITOR': '/usr/bin/vim', 'SSH_AGENT_PID': '25581', 'LOGNAME': 'maxim', 'COLORTERM': 'rxvt-xpm', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'XAUTHORITY': '/home/maxim/.Xauthority', 'DESKTOP_SESSION': 'dwm', 'QT4_IM_MODULE': 'xim', 'XDG_SESSION_TYPE': 'x11', 'PS1': '\\[\\e]0;\\u@\\h: \\w\\a\\]\\[\x1b[38;5;1m\\]┌─╼ \\[\x1b[38;5;7m\\][\\w]\\n\\[\x1b[38;5;1m\\]$(if [[ $? == 0 ]]; then echo "\\[\x1b[38;5;1m\\]└────╼"; else echo "\\[\x1b[38;5;1m\\]└╼"; fi) \\[\x1b[38;5;7m\\]', 'GTK_IM_MODULE': 'xim', 'TERM': 'rxvt-256color', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-WyZHTAblC1,guid=25323fd6d3f545ec1670e71255681525', 'COLORFGBG': 'default;default', 'HEX_CACHE': '/home/maxim/Software/hex/hex_cache', 'USER': 'maxim', 'XMODIFIERS': '@im=none', 'VIRTUAL_ENV': '/home/maxim/Software/qutebrowser/.venv', 'XDG_VTNR': '7', 'GDM_LANG': 'de_DE.utf8', 'CLUTTER_IM_MODULE': 'xim', 'PYTHONHASHSEED': '4086445260', 'TEXTDOMAIN': 'im-config', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session1', 'HEX_ROOT': '/home/maxim/Software/hex', '_': '/usr/bin/tox', 'LANG': 'de_DE.UTF-8', 'SSH_AUTH_SOCK': '/tmp/ssh-DqDYQGNRwBo9/agent.25544', 'GDMSESSION': 'dwm', 'HOME': '/home/maxim', 'XDG_SEAT': 'seat0', 'DISPLAY': ':0', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm/data/maxim', 'WINDOWID': '54525961', 'XDG_SESSION_DESKTOP': 'dwm', 'HEX_VERSION': '6l', 'XDG_SESSION_ID': '6', 'SHLVL': '1', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'PWD': '/home/maxim/Software/qutebrowser', 'PATH': '/home/maxim/Software/qutebrowser/.venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/maxim/Software/mead-2.2.9/build/bin:/home/maxim/Software/mcce/bin:/home/maxim/Software/hex/bin', 'TEXTDOMAINDIR': '/usr/share/locale/', 'SHELL': '/bin/bash'}
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in .venv/bin/python3
Also creating executable in .venv/bin/python
Installing setuptools, pip...
  Complete output from command /home/maxim/Software...er/.venv/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking setuptools
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/index.py", line 292, in find_requirement
    elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/util.py", line 739, in <listcomp>
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /home/maxim/.pip/pip.log

...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2378, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 830, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1032, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 975, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 917, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/maxim/Software...er/.venv/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 2

ERROR: InvocationError: /usr/bin/python3 -m virtualenv --setuptools --python /usr/bin/python3 .venv (see /home/maxim/Software/qutebrowser/.venv/log/mkvenv-0.log)
___________________________________ summary ____________________________________
ERROR:   mkvenv: InvocationError: /usr/bin/python3 -m virtualenv --setuptools --python /usr/bin/python3 .venv (see /home/maxim/Software/qutebrowser/.venv/log/mkvenv-0.log)
```

**Comment by The-Compiler** [comment]
(I edited your post a bit to put the terminal output between ```-lines, so github doesn't mess them up)

This is unfortunately a debian problem - see the following debian bugs

[786580](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786580)
[785787](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785787)
[786567](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786567)

It seems this should be resolved with the last pip upgrade however - have you tried upgrading your system and trying again?

**Comment by moozzz** [comment]
Yes, I update my system (debian testing) every day. There hasn't been any update for pip so far though. I have however a couple of packages which I put on hold since their update versions contain fatal errors (e. g., cpp-4.9, g++-4.9, gcc-4.9, openssl). But I think it's unrelated to qutebrowser.

I've just tried to upgrade pip via "pip install -U pip" and got an error:

```
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1097, in prepare_files
    req_to_install, self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 292, in find_requirement
    elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable
```

**Comment by The-Compiler** [comment]
Meh. You could always set up things by hand until Debian manages to fix this:

```
$ virtualenv .venv --python=/usr/bin/python3 --no-setuptools
$ wget https://bootstrap.pypa.io/get-pip.py
$ ./.venv/bin/python get-pip.py
$ python3 ~/proj/qutebrowser/git/scripts/link_pyqt.py .venv
$ ./.venv/bin/python setup.py install
```
