### ISSUE TITLE
AttributeError: 'MainWindow' object has no attribute '_completion'

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#766]
> crashes on open when pinned to taskbar windows 8.1

With v0.2.1, Qt/PyQt/runtime 5.4.1.

```
app:__init__:165 Init done!
app:_process_args:292 Initializing main window...
mainwindow:_load_geometry:181 Loading mainwindow from b'\x01\xd9\xd0\xcb\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x7f\x00\x00\x047\x00\x00\x01\xc6\x00\x00\x00\xb9\x00\x00\x04\xe5\x00\x00\x03\x10\x00\x00\x00\x00\x00\x04\x00\x00\x07\x80'
app:_exception_hook:612 Uncaught exception
Traceback (most recent call last):
  File "scripts\..\scripts\..\qutebrowser\mainwindow\mainwindow.py", line 334, in resizeEvent
  File "scripts\..\scripts\..\qutebrowser\mainwindow\mainwindow.py", line 277, in resize_completion
AttributeError: 'MainWindow' object has no attribute '_completion'
```

**Comment by The-Compiler** [comment]
I can't reproduce this on a Windows 8.1.

Apparently `setGeometry` causes a `resizeEvent` to happen, and the geometry is loaded before the completion is set up.
