### ISSUE TITLE
WTFCrash when uploading to up1.ca

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#811]
When uploading a picture to https://up1.ca/, qutebrowser crashes a few seconds after the picture is uploaded.

With the Qt example browser and the minimal webkit testbrowser, uploading doesn't seem to work at all.

However, I can reproduce this with otter:

```
#0  0x00007ffff5bf1fcc in WTFCrash () at wtf/Assertions.cpp:345
#1  0x00007ffff5c2c8e5 in WTF::StringImpl::~StringImpl (this=0x7fff7a57ac00, __in_chrg=<optimized out>) at wtf/text/StringImpl.cpp:120
#2  0x00007ffff5c2c989 in WTF::StringImpl::destroy (stringImpl=0x7fff7a57ac00) at wtf/text/StringImpl.cpp:153
#3  0x00007ffff4596787 in deref (this=<optimized out>) at ../WTF/wtf/text/StringImpl.h:617
#4  derefIfNotNull<WTF::StringImpl> (ptr=<optimized out>) at ../WTF/wtf/PassRefPtr.h:44
#5  ~RefPtr (this=0x7fff7a72ed80, __in_chrg=<optimized out>) at ../WTF/wtf/RefPtr.h:62
#6  ~String (this=0x7fff7a72ed80, __in_chrg=<optimized out>) at ../WTF/wtf/text/WTFString.h:152
#7  destruct (end=0x7fff7a72ed88, begin=<optimized out>) at ../WTF/wtf/Vector.h:52
#8  destruct (end=<optimized out>, begin=<optimized out>) at ../WTF/wtf/Vector.h:214
#9  WTF::Vector<WTF::String, 0ul, WTF::CrashOnOverflow>::shrink (this=this@entry=0x7fff7a6cf830, size=size@entry=0) at ../WTF/wtf/Vector.h:911
#10 0x00007ffff57bf9e6 in ~Vector (this=0x7fff7a6cf830, __in_chrg=<optimized out>) at ../WTF/wtf/Vector.h:538
#11 WebCore::SerializedScriptValue::~SerializedScriptValue (this=0x7fff7a6cf810, __in_chrg=<optimized out>) at bindings/js/SerializedScriptValue.cpp:1698
#12 0x00007ffff5748e7c in deref (this=0x7fff7a6cf810) at ../WTF/wtf/ThreadSafeRefCounted.h:137
#13 derefIfNotNull<WebCore::SerializedScriptValue> (ptr=0x7fff7a6cf810) at ../WTF/wtf/PassRefPtr.h:44
#14 ~RefPtr (this=0x7fff668361c8, __in_chrg=<optimized out>) at ../WTF/wtf/RefPtr.h:62
#15 WebCore::MessageEvent::~MessageEvent (this=0x7fff66836160, __in_chrg=<optimized out>) at dom/MessageEvent.cpp:105
#16 0x00007ffff5748f09 in WebCore::MessageEvent::~MessageEvent (this=0x7fff66836160, __in_chrg=<optimized out>) at dom/MessageEvent.cpp:107
#17 0x00007ffff4db24e0 in deref (this=<optimized out>) at ../WTF/wtf/RefCounted.h:196
#18 releaseImpl (this=<optimized out>) at generated/JSEvent.h:62
#19 WebCore::JSEventOwner::finalize (this=<optimized out>, handle=..., context=0x7ffff7e05580) at generated/JSEvent.cpp:650
#20 0x00007ffff5905010 in finalize (this=0x7fff7a86d000, weakImpl=0x7fff7a86db40) at heap/WeakSetInlines.h:52
#21 JSC::WeakBlock::sweep (this=0x7fff7a86d000) at heap/WeakBlock.cpp:76
#22 0x00007ffff5905620 in JSC::WeakSet::sweep (this=0x7fff90080448) at heap/WeakSet.cpp:47
#23 0x00007ffff5916ef5 in JSC::MarkedBlock::sweep (this=0x7fff90080000, sweepMode=JSC::MarkedBlock::SweepOnly) at heap/MarkedBlock.cpp:111
#24 0x00007ffff5912172 in sweepNextBlock (this=<optimized out>) at heap/IncrementalSweeper.cpp:130
#25 JSC::IncrementalSweeper::doSweep (this=0x555555cf1000, sweepBeginTime=15.471420719999999) at heap/IncrementalSweeper.cpp:108
#26 0x00007ffff5911d4f in JSC::HeapTimer::timerEvent (this=0x555555cf1000) at heap/HeapTimer.cpp:159
#27 0x00007ffff326cd03 in QObject::event (this=0x555555cf1000, e=<optimized out>) at kernel/qobject.cpp:1268
#28 0x00007ffff686efb4 in QApplicationPrivate::notify_helper (this=this@entry=0x555555a8d9e0, receiver=receiver@entry=0x555555cf1000, e=e@entry=0x7fffffffd850) at kernel/qapplication.cpp:3717
#29 0x00007ffff6873e95 in QApplication::notify (this=0x7fffffffdd70, receiver=0x555555cf1000, e=<optimized out>) at kernel/qapplication.cpp:3161
#30 0x00007ffff323d73b in QCoreApplication::notifyInternal (this=0x7fffffffdd70, receiver=0x555555cf1000, event=event@entry=0x7fffffffd850) at kernel/qcoreapplication.cpp:965
#31 0x00007ffff3292efd in sendEvent (event=0x7fffffffd850, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:224
#32 QTimerInfoList::activateTimers (this=0x555555abe5f0) at kernel/qtimerinfo_unix.cpp:637
#33 0x00007ffff3293401 in timerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:177
#34 0x00007ffff15679fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#35 0x00007ffff1567ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#36 0x00007ffff1567d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#37 0x00007ffff32940fb in QEventDispatcherGlib::processEvents (this=0x555555abd1f0, flags=...) at kernel/qeventdispatcher_glib.cpp:420
#38 0x00007fffe3cdd514 in QPAEventDispatcherGlib::processEvents (this=<optimized out>, flags=...) at eventdispatchers/qeventdispatcher_glib.cpp:115
#39 0x00007ffff323b10a in QEventLoop::exec (this=this@entry=0x7fffffffdaa0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#40 0x00007ffff32430ac in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1218
#41 0x00007ffff377118c in QGuiApplication::exec () at kernel/qguiapplication.cpp:1528
#42 0x00007ffff686ab91 in QApplication::exec () at kernel/qapplication.cpp:2977
#43 0x00005555555ed1f9 in main ()
```

**Comment by The-Compiler** [comment]
https://bugreports.qt.io/browse/QTBUG-47268
