### ISSUE TITLE
Tab registry keyerror in NetworkManager.createRequest with downloads

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#889]
Report 1 by @Carpetsmoker, on 0306786

> Right-clicked, selected "save as" or was about to ... Had 2 or 3 downloads going...

```
00:56:12 DEBUG    modes      tabbedbrowser:on_current_changed:517 Current tab changed, focusing <qutebrowser.browser.webview.WebView tab_id=334 url='http://skeptoid.com/episodes/4477'>
[...]
00:56:15 DEBUG    downloads  downloads:fetch:783 fetch: PyQt5.QtCore.QUrl('http://skeptoid.com/audio/skeptoid-4477.mp3') -> skeptoid-4477.mp3
[...]
00:56:15 DEBUG    downloads  downloads:_handle_redirect:607 3: skeptoid-4477.mp3 [   0.00B/s|    ?|??%|0.00B/0.00B]: Handling redirect
00:56:15 DEBUG    downloads  downloads:on_redirect:910 redirected: PyQt5.QtCore.QUrl('http://skeptoid.com/audio/skeptoid-4477.mp3') -> PyQt5.QtCore.QUrl('http://traffic.libsyn.com/skeptoid/skeptoid-4477.mp3')
[...]
00:56:15 DEBUG    commands   command:run:489 command called: tab-close
00:56:15 DEBUG    commands   command:run:503 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
00:56:15 DEBUG    destroy    webview:shutdown:331 Shutting down <qutebrowser.browser.webview.WebView tab_id=334 url='http://skeptoid.com/episodes/4477'>.
00:56:15 DEBUG    downloads  networkmanager:adopt_download:294 Adopted download, 1 adopted.
[...]
00:56:15 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 334
00:56:15 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
00:56:15 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
00:56:15 DEBUG    destroy    objreg:_on_destroyed:123 removed: 334
00:56:15 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
00:56:15 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager
00:56:15 DEBUG    downloads  downloads:_handle_redirect:607 3: skeptoid-4477.mp3 [   0.00B/s|    ?|??%|0.00B/0.00B]: Handling redirect
00:56:15 DEBUG    downloads  downloads:on_redirect:910 redirected: PyQt5.QtCore.QUrl('http://traffic.libsyn.com/skeptoid/skeptoid-4477.mp3') -> PyQt5.QtCore.QUrl('http://ec.libsyn.com/p/c/d/8/cd84ebf7e0e23465/skeptoid-4477.mp3?d13a76d516d9dec20c3d276ce028ed5089ab1ce3dae902ea1d06cb8f3ed1cb549247&c_id=9421798')
00:56:15 ERROR    misc       utils:wrapper:500 Error in qutebrowser.browser.network.networkmanager.NetworkManager.createRequest
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.3.0-py3.4.egg/qutebrowser/utils/utils.py", line 498, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.3.0-py3.4.egg/qutebrowser/browser/network/networkmanager.py", line 345, in createRequest
    tab=self._tab_id)
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.3.0-py3.4.egg/qutebrowser/utils/objreg.py", line 215, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.3.0-py3.4.egg/qutebrowser/utils/objreg.py", line 202, in _get_registry
    return _get_tab_registry(window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.3.0-py3.4.egg/qutebrowser/utils/objreg.py", line 165, in _get_tab_registry
    return tab_registry[tab_id].registry
  File "/usr/lib/python3.4/collections/__init__.py", line 908, in __getitem__
    raise KeyError(key)
KeyError: 334
```

---

Report 2, on 355074f

> Download for .iso file failed. Righclick -> retry -> crash

```
23:35:14 DEBUG    webview    webview:_set_load_status:181 load status for <qutebrowser.browser.webview.WebView tab_id=47 url='http://rlsd3.dimakrasner.com/images/x86_64/iso'>: LoadStatus.loading
[...]
23:35:15 DEBUG    downloads  downloads:fetch:789 fetch: PyQt5.QtCore.QUrl('http://rlsd3.dimakrasner.com/images/x86_64/iso/rlsd-08082015-huge.iso') -> rlsd-08082015-huge.iso
[...]
23:35:45 DEBUG    commands   command:run:490 command called: tab-close
23:35:45 DEBUG    commands   command:run:504 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
23:35:45 DEBUG    destroy    webview:shutdown:331 Shutting down <qutebrowser.browser.webview.WebView tab_id=47 url='http://rlsd3.dimakrasner.com/images/x86_64/iso'>.
23:35:45 DEBUG    downloads  networkmanager:adopt_download:296 Adopted download, 1 adopted.
[...]
23:35:45 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 47
23:35:45 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
23:35:45 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
23:35:45 DEBUG    destroy    objreg:_on_destroyed:123 removed: 47
23:35:45 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
23:35:45 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager
[...]
23:38:14 ERROR    message    message:error:277 [1m 18s ago] Download error: Connection closed
[...]
(the user probably clicked retry here)
23:38:26 ERROR    misc       utils:wrapper:513 Error in qutebrowser.browser.network.networkmanager.NetworkManager.createRequest
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/utils.py", line 511, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/network/networkmanager.py", line 368, in createRequest
    tab=self._tab_id)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line 215, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line 202, in _get_registry
    return _get_tab_registry(window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line 165, in _get_tab_registry
    return tab_registry[tab_id].registry
  File "/usr/lib/python3.4/collections/__init__.py", line 908, in __getitem__
    raise KeyError(key)
KeyError: 47
```

**Comment by The-Compiler** [comment]
I just got another report via email:

> I was downloading a pdf and a epub. The epub download failed and I right clicked on it status and clicked on retry. Qute crashed afterwards :)

```
07:02:31 DEBUG    webview    webview:_set_load_status:181 load status for <qutebrowser.browser.webview.WebView tab_id=43 url='URL_REDACTED'>: LoadStatus.loading
[...]
07:02:32 DEBUG    downloads  downloads:fetch:789 fetch: PyQt5.QtCore.QUrl(' URL_REDACTED') -> FILENAME_REDACTED.epub
[...]
07:03:12 DEBUG    commands   command:run:504 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
07:03:12 DEBUG    destroy    webview:shutdown:331 Shutting down <qutebrowser.browser.webview.WebView tab_id=43 url=' URL_REDACTED'>.
07:03:12 DEBUG    downloads  networkmanager:adopt_download:296 Adopted download, 1 adopted.
[...]
07:03:13 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 43
07:03:13 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
07:03:13 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
07:03:13 DEBUG    destroy    objreg:_on_destroyed:123 removed: 43
07:03:13 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
07:03:13 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager 
[...]
07:07:11 DEBUG    statusbar  bar:_disp_text:437 Displaying text: [8s ago] Download error: Connection closed (severity=Severity.error)
[...]
(user probably clicked retry here)
[...]
07:07:36 ERROR    misc       utils:wrapper:513 Error in qutebrowser.browser.network.networkmanager.NetworkManager.createRequest
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/utils.py", line
511, in wrapper
    return func(*args, **kwargs)
  File
"/usr/lib/python3.4/site-packages/qutebrowser/browser/network/networkmanager.py",
line 368, in createRequest
    tab=self._tab_id)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line
215, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line
202, in _get_registry
    return _get_tab_registry(window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/utils/objreg.py", line
165, in _get_tab_registry
    return tab_registry[tab_id].registry
  File "/usr/lib/python3.4/collections/__init__.py", line 908, in
__getitem__
    raise KeyError(key)
KeyError: 43
```

**Comment by The-Compiler** [comment]
Another one from @Carpetsmoker, with a very similar log to the first one above:

> - Open qutebrowser
> - go to skeptoid.com
> - Open first 3 links in a new tab
> - go to the first of these, right-click "listen", save as -> select dir
> - crash

```
02:08:04 DEBUG    misc       webelem:is_editable:262 Checking if element is editable: <qutebrowser.browser.webelem.WebElementWrapper html='<b>More Unsung Women of Science</b>'>
02:08:04 DEBUG    mouse      webview:_mousepress_insertmode:284 Clicked non-editable element!
02:08:04 DEBUG    mouse      webview:_mousepress_opentarget:324 Middle click, setting target: ClickTarget.tab_bg
02:08:04 DEBUG    webview    webpage:acceptNavigationRequest:559 acceptNavigationRequest, url http://skeptoid.com/episodes/4484, type NavigationTypeLinkClicked, hint target None, open_target ClickTarget.tab_bg
02:08:04 DEBUG    webview    tabbedbrowser:tabopen:346 Creating new tab with URL PyQt5.QtCore.QUrl('http://skeptoid.com/episodes/4484')
02:08:04 DEBUG    webview    tabbedbrowser:on_title_changed:459 Changing title for idx 1 to 'More Unsung Women of Science'

02:08:05 DEBUG    misc       webelem:is_editable:262 Checking if element is editable: <qutebrowser.browser.webelem.WebElementWrapper html='<b>Unsung Women of Science</b>'>
02:08:05 DEBUG    mouse      webview:_mousepress_insertmode:284 Clicked non-editable element!
02:08:05 DEBUG    mouse      webview:_mousepress_opentarget:324 Middle click, setting target: ClickTarget.tab_bg
02:08:05 DEBUG    webview    webpage:acceptNavigationRequest:559 acceptNavigationRequest, url http://skeptoid.com/episodes/4483, type NavigationTypeLinkClicked, hint target None, open_target ClickTarget.tab_bg
02:08:05 DEBUG    webview    tabbedbrowser:tabopen:346 Creating new tab with URL PyQt5.QtCore.QUrl('http://skeptoid.com/episodes/4483')
02:08:06 DEBUG    webview    tabbedbrowser:on_title_changed:459 Changing title for idx 2 to 'Unsung Women of Science'

02:08:08 DEBUG    misc       webelem:is_editable:262 Checking if element is editable: <qutebrowser.browser.webelem.WebElementWrapper html="<b>Sir Franklin's Cannibals</b>">
02:08:08 DEBUG    mouse      webview:_mousepress_insertmode:284 Clicked non-editable element!
02:08:08 DEBUG    mouse      webview:_mousepress_opentarget:324 Middle click, setting target: ClickTarget.tab_bg
02:08:08 DEBUG    webview    webpage:acceptNavigationRequest:559 acceptNavigationRequest, url http://skeptoid.com/episodes/4482, type NavigationTypeLinkClicked, hint target None, open_target ClickTarget.tab_bg
02:08:08 DEBUG    webview    tabbedbrowser:tabopen:346 Creating new tab with URL PyQt5.QtCore.QUrl('http://skeptoid.com/episodes/4482')
02:08:09 DEBUG    webview    tabbedbrowser:on_title_changed:459 Changing title for idx 3 to 'Sir Franklin's Cannibals'

02:08:09 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
02:08:09 DEBUG    commands   command:run:490 command called: tab-close
02:08:09 DEBUG    commands   command:run:504 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
02:08:09 DEBUG    destroy    webview:shutdown:334 Shutting down <qutebrowser.browser.webview.WebView tab_id=0 url='http://skeptoid.com/'>.

02:08:09 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 0
02:08:09 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
02:08:09 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
02:08:09 DEBUG    destroy    objreg:_on_destroyed:123 removed: 0
02:08:09 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
02:08:09 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager

02:08:12 DEBUG    misc       webelem:is_editable:262 Checking if element is editable: <qutebrowser.browser.webelem.WebElementWrapper html='<a href="/audio/skeptoid-4484.mp3">Listen</a>'>
02:08:12 DEBUG    mouse      webview:_mousepress_insertmode:284 Clicked non-editable element!
02:08:12 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.insert! (leave reason: click)
02:08:12 DEBUG    mouse      webview:_mousepress_opentarget:327 Normal click, setting normal target
02:08:13 DEBUG    statusbar  text:set_text:59 Setting temp text to ''.
02:08:13 DEBUG    statusbar  prompter:ask_question:304 Asking question <qutebrowser.utils.usertypes.Question default='/home/martin/' mode=<PromptMode.text: 2> text='Save file to:'>, blocking False, loops [], queue deque([])

02:08:15 DEBUG    commands   command:run:490 command called: prompt-accept
02:08:15 DEBUG    downloads  downloads:fetch:789 fetch: PyQt5.QtCore.QUrl('http://skeptoid.com/audio/skeptoid-4484.mp3') -> skeptoid-4484.mp3

02:08:15 DEBUG    downloads  downloads:_handle_redirect:613 1: skeptoid-4484.mp3 [   0.00B/s|    ?|100%|0.00B/0.00B]: Handling redirect
02:08:15 DEBUG    downloads  downloads:on_redirect:921 redirected: PyQt5.QtCore.QUrl('http://skeptoid.com/audio/skeptoid-4484.mp3') -> PyQt5.QtCore.QUrl('http://traffic.libsyn.com/skeptoid/skeptoid-4484.mp3')
02:08:15 DEBUG    modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>

02:08:15 DEBUG    commands   command:run:490 command called: tab-close
02:08:15 DEBUG    commands   command:run:504 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
02:08:15 DEBUG    destroy    webview:shutdown:334 Shutting down <qutebrowser.browser.webview.WebView tab_id=1 url='http://skeptoid.com/episodes/4484'>.
02:08:15 DEBUG    downloads  networkmanager:adopt_download:296 Adopted download, 1 adopted.

02:08:15 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 1
02:08:15 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
02:08:15 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
02:08:15 DEBUG    destroy    objreg:_on_destroyed:123 removed: 1
02:08:15 DEBUG    destroy    objreg:_on_destroyed:123 removed: webview
02:08:15 DEBUG    destroy    objreg:_on_destroyed:123 removed: hintmanager

02:08:15 DEBUG    downloads  downloads:_handle_redirect:613 1: skeptoid-4484.mp3 [   0.00B/s|    ?|100%|0.00B/0.00B]: Handling redirect
02:08:15 DEBUG    downloads  downloads:on_redirect:921 redirected: PyQt5.QtCore.QUrl('http://traffic.libsyn.com/skeptoid/skeptoid-4484.mp3') -> PyQt5.QtCore.QUrl('http://hwcdn.libsyn.com/p/b/5/5/b556882853a5e5ac/skeptoid-4484.mp3?c_id=9811210&expiration=1442795127&hwt=d8d1e63ddea4a20dab4c15a8cdc14a25')
02:08:15 ERROR    misc       utils:wrapper:513 Error in qutebrowser.browser.network.networkmanager.NetworkManager.createRequest
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/utils/utils.py", line 511, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/browser/network/networkmanager.py", line 367, in createRequest
    tab=self._tab_id)
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/utils/objreg.py", line 215, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/utils/objreg.py", line 202, in _get_registry
    return _get_tab_registry(window, tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/utils/objreg.py", line 165, in _get_tab_registry
    return tab_registry[tab_id].registry
  File "/usr/lib/python3.4/collections/__init__.py", line 908, in __getitem__
    raise KeyError(key)
KeyError: 1
02:08:15 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
TypeError: invalid result from NetworkManager.createRequest(), bool cannot be converted to PyQt5.QtNetwork.QNetworkReply in this context
```

**Comment by The-Compiler** [comment]
I can reproduce this by doing this:

* Open http://skeptoid.com/episodes/4485
* Right-click listen -> save as
* Accept filename prompt
* Immediately close tab

**Comment by The-Compiler** [comment]
I think there are at least two situations that happens:

* Redirection after closing a tab (like described above)
* Error after closing a tab (best reproduced by killing a HTTP server during the download) and then retrying.

**Comment by The-Compiler** [comment]
I tried the redirection case - this seems to be caused by 976f758da1d5ad086bc539b41a3afd534e64b282 (which was a fixup for #731).

**Comment by The-Compiler** [comment]
This still is an issue if the webview is in the middle of a shutdown:

```
09:52:51 DEBUG    commands   command:run:504 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, None)
09:52:51 DEBUG    destroy    webview:shutdown:332 Shutting down <qutebrowser.browser.webview.WebView tab_id=1 url='http://localhost:52228/data/downloads/issue889.html'>.
09:52:51 DEBUG    downloads  networkmanager:adopt_download:296 Adopted download, 1 adopted.
09:52:51 DEBUG    webview    tabbedbrowser:tabopen:378 Creating new tab with URL PyQt5.QtCore.QUrl('about:blank')
09:52:51 DEBUG    init       networkmanager:__init__:89 Initializing NetworkManager
09:52:51 DEBUG    init       networkmanager:__init__:94 NetworkManager init done
09:52:51 DEBUG    webview    tabbedbrowser:_get_new_tab_idx:431 new-tab-position right -> opening new tab at 1, next left: 0 / right: 2
09:52:51 DEBUG    modes      tabbedbrowser:on_current_changed:549 Current tab changed, focusing <qutebrowser.browser.webview.WebView tab_id=2 url=''>
09:52:51 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.hint! (leave reason: tab changed)
09:52:51 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.insert! (leave reason: tab changed)
09:52:51 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.caret! (leave reason: tab changed)
09:52:51 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.passthrough! (leave reason: tab changed)
127.0.0.1 - - [09/Nov/2015 09:52:51] "GET /does-not-exist HTTP/1.1" 404 -
09:52:51 DEBUG    webview    webview:openurl:346 New title: about:blank
09:52:51 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 0 to 'about:blank'
09:52:51 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_url_text_changed('about:blank') (tab 0)
09:52:52 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=2 url=''>: LoadStatus.loading
09:52:52 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('loading') (tab 0)
09:52:52 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 0)
09:52:52 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.insert! (leave reason: load started)
09:52:52 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.hint! (leave reason: load started)
09:52:52 DEBUG    save       savemanager:mark_dirty:73 Marking history as dirty.
09:52:52 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_url_text_changed('about:blank') (tab 0)
09:52:52 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 0 to 'about:blank'
09:52:52 DEBUG    webview    tabbedbrowser:on_title_changed:483 Ignoring title change to ''.
09:52:52 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=2 url='about:blank'>: LoadStatus.success
09:52:52 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('success') (tab 0)
09:52:52 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 0 to 'about:blank'
09:52:52 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(True) (tab 0)
09:52:52 DEBUG    ipc        ipc:handle_connection:264 Socket was disconnected immediately.
09:52:52 DEBUG    ipc        ipc:on_disconnected:270 Client disconnected.
09:52:52 DEBUG    ipc        ipc:handle_connection:248 No new connection to handle.
09:52:52 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: 1
09:52:52 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: webview
09:52:52 DEBUG    destroy    objreg:on_destroyed:118 schedule removal: hintmanager
09:52:52 ERROR    message    message:error:277 Download error: Error downloading http://localhost:52228/does-not-exist - server replied: NOT FOUND
09:52:52 DEBUG    statusbar  bar:_disp_text:437 Displaying text: Download error: Error downloading http://localhost:52228/does-not-exist - server replied: NOT FOUND (severity=Severity.error)
09:52:52 DEBUG    statusbar  bar:_disp_text:445 queue: deque([]) / delta: None
09:52:52 DEBUG    statusbar  bar:_disp_text:451 Displaying immediately
09:52:52 DEBUG    statusbar  bar:_set_severity:281 Setting severity to Severity.error
09:52:52 DEBUG    statusbar  text:set_text:59 Setting temp text to 'Download error: Error downloading http://localhost:52228/does-not-exist - server replied: NOT FOUND'.
09:52:52 DEBUG    ipc        ipc:handle_connection:250 Client connected.
09:52:52 DEBUG    ipc        ipc:on_ready_read:299 Read from socket: b'{"target_arg": "", "version": "0.4.1", "args": [":download-retry"], "protocol_version": 1, "cwd": "/Users/buildbot/buildbot/slave/osx/build"}\n'
09:52:52 DEBUG    ipc        ipc:on_ready_read:309 Processing: {"target_arg": "", "version": "0.4.1", "args": [":download-retry"], "protocol_version": 1, "cwd": "/Users/buildbot/buildbot/slave/osx/build"}
09:52:52 DEBUG    init       app:process_pos_args:261 Startup cmd :download-retry
09:52:52 DEBUG    commands   command:run:490 command called: download-retry
09:52:52 DEBUG    commands   command:run:504 Calling qutebrowser.browser.downloads.DownloadManager.download_retry(<qutebrowser.browser.downloads.DownloadManager downloads=2>, 0)
09:52:52 ERROR    misc       utils:wrapper:522 Error in qutebrowser.browser.network.networkmanager.NetworkManager.createRequest
INVALID: Traceback (most recent call last):
INVALID: RuntimeError: wrapped C/C++ object of type WebView has been deleted
09:52:52 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
INVALID: TypeError: invalid result from NetworkManager.createRequest(), bool cannot be converted to PyQt5.QtNetwork.QNetworkReply in this context
```

This could help but needs some more testing:

```diff
diff --git a/qutebrowser/browser/network/networkmanager.py b/qutebrowser/browser/network/networkmanager.py
index 436db91..66ec759 100644
--- a/qutebrowser/browser/network/networkmanager.py
+++ b/qutebrowser/browser/network/networkmanager.py
@@ -360,17 +360,21 @@ class NetworkManager(QNetworkAccessManager):
         req.setRawHeader('DNT'.encode('ascii'), dnt)
         req.setRawHeader('X-Do-Not-Track'.encode('ascii'), dnt)
 
-        if self._tab_id is None:
-            current_url = QUrl()  # generic NetworkManager, e.g. for downloads
-        else:
+        # There are some scenarios where we can't figure out current_url:
+        # - There's a generic NetworkManager, e.g. for downloads
+        # - The download was in a tab which is now closed.
+        current_url = QUrl()
+
+        if self._tab_id is not None:
             try:
                 webview = objreg.get('webview', scope='tab',
                                      window=self._win_id, tab=self._tab_id)
-            except KeyError:
+                current_url = webview.url()
+            except (KeyError, RuntimeError, TypeError):
                 # https://github.com/The-Compiler/qutebrowser/issues/889
+                # Catching RuntimeError and TypeError because we could be in
+                # the middle of the webpage shutdown here.
                 current_url = QUrl()
-            else:
-                current_url = webview.url()
 
         self.set_referer(req, current_url)
```
