### ISSUE TITLE
ValueError: tab ... is not contained in TabbedWidget

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#906]
From various reports by the same user.

It seems that port is some JDownloader browser captcha solver thing, so I guess something goes wrong when it closes the tab via JS.

I can't reproduce this with [this test](http://www.w3schools.com/jsref/met_win_close.asp) though...

# log

```
06:50:36 DEBUG    ipc        ipc:on_ready_read:146 Processing: {"args": ["http://127.0.0.1:24613/uploaded.to/?id=1440910235887"], "cwd": "/opt/JDownloader"}
[...]
06:50:36 DEBUG    webview    tabbedbrowser:on_title_changed:457 Changing title for idx 12 to 'ReCAPTCHA-Input'
06:50:36 DEBUG    webview    webview:_set_load_status:166 load status for <qutebrowser.browser.webview.WebView url='http://127.0.0.1:24613/uploaded.to/?id=1440910235…' tab_id=98>: LoadStatus.success
[...]
06:50:37 DEBUG    js         webpage:javaScriptConsoleMessage:304 [http://127.0.0.1:24613/uploaded.to/?id=1440910235887:36] CloSe browser
06:50:37 DEBUG    destroy    webview:shutdown:305 Shutting down <qutebrowser.browser.webview.WebView url='http://127.0.0.1:24613/uploaded.to/?id=1440910235…' tab_id=98>.
06:50:37 DEBUG    modes      tabbedbrowser:on_current_changed:527 Current tab changed, focusing <qutebrowser.browser.webview.WebView url='http://www.goodreads.com/book/similar/6706609-bla…' tab_id=97>
[...]
06:50:37 ERROR    misc       app:_exception_hook:514 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 292, in on_window_close_requested
    self.close_tab(widget)
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 217, in close_tab
    self._remove_tab(tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 233, in _remove_tab
    tab))
ValueError: tab <qutebrowser.browser.webview.WebView url='http://127.0.0.1:24613/uploaded.to/?id=1440910235…' tab_id=98> is not contained in TabbedWidget!
```

# relevant config

```ini
[general]
new-instance-open-target = tab
[tabs]
last-close = blank
auto-hide = true
indicator-width = 0
```

# objects

```
    <qutebrowser.browser.webview.WebView url='http://127.0.0.1:24613/uploaded.to/?id=1440910235…' tab_id=98>
```

```
    tab-registry: {..., 98: <qutebrowser.browser.webview.WebView url='http://127.0.0.1:24613/uploaded.to/?id=1440910235…' tab_id=98>}
```

```
    tab-98 object registry - 2 objects:
        hintmanager: <qutebrowser.browser.hints.HintManager object at 0x7fcc5b1a1828>
        webview: <qutebrowser.browser.webview.WebView url='http://127.0.0.1:24613/uploaded.to/?id=1440910235…' tab_id=98>
```

**Comment by The-Compiler** [comment]
Note the user reporting this is on v0.1.2 - so this might as well be fixed already.

**Comment by The-Compiler** [comment]
The same thing seems to happen with a Google Plus post on v0.3.0 for another user:

## Report

> I submitted a Google Plus post.

## Exception

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 317, in on_window_close_requested
    self.close_tab(widget)
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 238, in close_tab
    self._remove_tab(tab)
  File "/usr/lib/python3.4/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 258, in _remove_tab
    tab))
ValueError: tab <qutebrowser.browser.webview.WebView tab_id=7 url='https://plus.google.com/share?url=http://www.huff…'> is not contained in TabbedWidget!
```

# relevant config

```ini
[general]
new-instance-open-target = window
[tabs]
hide-auto = true
show-favicons = false
indicator-width = 0
indicator-space = 0
title-format = {title}
```
# objects

```
<qutebrowser.browser.webview.WebView tab_id=7 url='https://plus.google.com/share?url=http://www.huff…'>
```

```
tab-registry: {... 7: <qutebrowser.browser.webview.WebView tab_id=7 url='https://plus.google.com/share?url=http://www.huff…'>}
```

```
    tab-7 object registry - 2 objects:
        hintmanager: <qutebrowser.browser.hints.HintManager object at 0xa899c854>
        webview: <qutebrowser.browser.webview.WebView tab_id=7 url='https://plus.google.com/share?url=http://www.huff…'>
```

## log

```
modes      tabbedbrowser:on_current_changed:513 Current tab changed, focusing <qutebrowser.browser.webview.WebView tab_id=7 url='https://plus.google.com/share?url=http://www.huff…'>
[...]
misc       webelem:is_editable:260 Checking if element is editable: <qutebrowser.browser.webelem.WebElementWrapper html='<div role="button" class="d-k-l b-c b-c-Ba qy jt" guidedhelpid="sharebutton" aria-disabled="false" tabindex="0" style="-webkit-user-select: none;">Share</div>'>
[...]
destroy    webview:shutdown:331 Shutting down <qutebrowser.browser.webview.WebView tab_id=7 url='https://plus.google.com/share?url=http://www.huff…'>.
modes      tabbedbrowser:on_current_changed:513 Current tab changed, focusing <qutebrowser.browser.webview.WebView tab_id=6 url='http://www.huffingtonpost.com/charles-eisenstein/…'>
[...]
misc       crashsignal:exception_hook:207 Uncaught exception
```

**Comment by The-Compiler** [comment]
Another report of the same issue, on 057cd70:

## Report

> just trying to authorize [swarm simulator](https://swarmsim.github.io/) with dropbox and when i tried to login dropbox it just crashed

## exception

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 353, in on_window_close_requested
    self.close_tab(widget)
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 253, in close_tab
    self._remove_tab(tab)
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 276, in _remove_tab
    tab))
ValueError: tab <qutebrowser.browser.webview.WebView tab_id=2 url='https://swarmsim.github.io/views/dropboxauth.html#access_token=…'> is not contained in TabbedWidget!
```

## config

```
[general]
startpage = file:///home/doublet/.start/index.html
[ui]
downloads-position = bottom
confirm-quit = downloads
smooth-scrolling = true
[network]
accept-language = tr-TR,tr
user-agent = Mozilla/5.0 (X11; CrOS x86_64 7520.55.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.74 Safari/537.36
ssl-strict = false
[tabs]
show = multiple
padding = 3,3,5,5
```

## objects

```
Qt widgets - 42 objects:
    [...]
    <qutebrowser.browser.webview.WebView tab_id=0 url='https://www.google.com.tr/?gfe_rd=cr&ei=…&gws_rd=ssl'>
    <qutebrowser.browser.webview.WebView tab_id=1 url='https://swarmsim.github.io/#/options'>
    <qutebrowser.browser.webview.WebView tab_id=2 url='https://swarmsim.github.io/views/dropboxauth.html#access_token=…'>
    [...]
    <qutebrowser.mainwindow.statusbar.text.Text text='SSL error: The issuer certificate of a locally looked up certificate could not be found'>
    <qutebrowser.mainwindow.statusbar.textbase.TextBase text=''>
    <qutebrowser.mainwindow.statusbar.url.UrlText text='https://swarmsim.github.io/#/options'>
    <qutebrowser.mainwindow.tabbedbrowser.TabbedBrowser count=2>
    <qutebrowser.mainwindow.tabwidget.TabBar count=2>

Qt objects - 25 objects:
    [...]

global object registry - 22 objects:
    [...]

window-0 object registry - 15 objects:
    [...]
    tab-registry: {0: <qutebrowser.browser.webview.WebView tab_id=0 url='https://www.google.com.tr/?gfe_rd=cr&ei=…&gws_rd=ssl'>, 1: <qutebrowser.browser.webview.WebView tab_id=1 url='https://swarmsim.github.io/#/options'>, 2: <qutebrowser.browser.webview.WebView tab_id=2 url='https://swarmsim.github.io/views/dropboxauth.html#access_token=……'>}
    [...]
    last-focused-tab: <qutebrowser.browser.webview.WebView tab_id=1 url='https://swarmsim.github.io/#/options'>
    [...]
    tabbed-browser: <qutebrowser.mainwindow.tabbedbrowser.TabbedBrowser count=2>
    [...]

    tab-0 object registry - 2 objects:
        webview: <qutebrowser.browser.webview.WebView tab_id=0 url='https://www.google.com.tr/?gfe_rd=cr&ei=…&gws_rd=ssl'>
        hintmanager: <qutebrowser.browser.hints.HintManager object at 0x7f26f54c3d38>

    tab-1 object registry - 2 objects:
        webview: <qutebrowser.browser.webview.WebView tab_id=1 url='https://swarmsim.github.io/#/options'>
        hintmanager: <qutebrowser.browser.hints.HintManager object at 0x7f26f655b558>

    tab-2 object registry - 2 objects:
        webview: <qutebrowser.browser.webview.WebView tab_id=2 url='https://swarmsim.github.io/views/dropboxauth.html#access_token=……'>
        hintmanager: <qutebrowser.browser.hints.HintManager object at 0x7f26b2c031f8>
```

## log

```
06:50:33 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_url_text_changed('https://swarmsim.github.io/views/dropboxauth.html#access_token=…&token_type=bearer&state=..&uid=…') (tab 2)
06:50:33 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 2 to 'https://swarmsim.github.io/views/dropboxauth.html#access_token=…&token_type=bearer&state=..&uid=…'
06:50:33 DEBUG    webview    tabbedbrowser:on_title_changed:483 Ignoring title change to ''.
06:50:34 DEBUG    save       savemanager:mark_dirty:73 Marking history as dirty.
06:50:34 DEBUG    destroy    webview:shutdown:332 Shutting down <qutebrowser.browser.webview.WebView tab_id=2 url='https://swarmsim.github.io/views/dropboxauth.html#access_token=…'>.
06:50:34 DEBUG    modes      tabbedbrowser:on_current_changed:549 Current tab changed, focusing <qutebrowser.browser.webview.WebView tab_id=1 url='https://swarmsim.github.io/#/options'>
06:50:34 DEBUG    misc       app:on_focus_object_changed:756 Focus object changed: <qutebrowser.browser.webview.WebView tab_id=1 url='https://swarmsim.github.io/#/options'>
06:50:34 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.hint! (leave reason: tab changed)
06:50:34 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.insert! (leave reason: tab changed)
06:50:34 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.caret! (leave reason: tab changed)
06:50:34 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.passthrough! (leave reason: tab changed)
06:50:34 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 353, in on_window_close_requested
    self.close_tab(widget)
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 253, in close_tab
    self._remove_tab(tab)
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 276, in _remove_tab
    tab))
ValueError: tab <qutebrowser.browser.webview.WebView tab_id=2 url='https://swarmsim.github.io/views/dropboxauth.html#access_token=…'> is not contained in TabbedWidget!
```

**Comment by The-Compiler** [comment]
Another one with a Dropbox auth, on d6fafd4:

# Report

> - Opened laverne.cc
> - Accepted dropbox auth popup page

# Config

```
[general]
startpage = https://www.duckduckgo.com
developer-extras = true
default-encoding = utf-8
new-instance-open-target = window
log-javascript-console = none
session-default-name = latest
[ui]
display-statusbar-messages = true
smooth-scrolling = true
statusbar-padding = 2,2,0,0
[network]
accept-language = en-US,en,es-MX,es
[completion]
shrink = true
[tabs]
background-tabs = true
show = multiple
title-format = {index}{title_sep}{title}
padding = 2,2,0,0
[storage]
download-directory = /tmp
[content]
host-blocking-enabled = false
```

# Environment

```
DESKTOP_SESSION = i3-gnome
LANG = en_US.utf8
LC_COLLATE = en_US.UTF-8
QT_HARFBUZZ = old
```

# Objects

Qt widgets - 43 objects:
    [...]
    <qutebrowser.browser.webview.WebView tab_id=0 url='https://mail.google.com/mail/u/0/#inbox'>
    <qutebrowser.browser.webview.WebView tab_id=1 url='http://electron.atom.io/'>
    <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/'>
    <qutebrowser.browser.webview.WebView tab_id=3 url='https://laverna.cc/app/dropbox.html#access_token=...'>
    [...]

Qt objects - 26 objects:
    [...]

global object registry - 22 objects:
    [...]

window-0 object registry - 15 objects:
    tabbed-browser: <qutebrowser.mainwindow.tabbedbrowser.TabbedBrowser count=3>
    [...]
    last-focused-tab: <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/'>
    [...]
    tab-registry: {0: <qutebrowser.browser.webview.WebView tab_id=0 url='https://mail.google.com/mail/u/0/#inbox'>, 1: <qutebrowser.browser.webview.WebView tab_id=1 url='http://electron.atom.io/'>, 2: <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/'>, 3: <qutebrowser.browser.webview.WebView tab_id=3 url='https://laverna.cc/app/dropbox.html#access_token=...'>}
    [...]

    [...]

    tab-3 object registry - 2 objects:
        hintmanager: <qutebrowser.browser.hints.HintManager object at 0x7fb4951e9828>
        webview: <qutebrowser.browser.webview.WebView tab_id=3 url='https://laverna.cc/app/dropbox.html#access_token=...'>

==== Debug log ====
20:46:32 DEBUG    webview    webview:_set_load_status:182 load status for
<qutebrowser.browser.webview.WebView tab_id=3 url='https://laverna.cc/app/dropbox.html#access_token=...'>: LoadStatus.success_https
20:46:32 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('success_https') (tab 3)
20:46:32 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 3 to 'https://laverna.cc/app/dropbox.html#access_token=...'
20:46:32 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(False) (tab 3)
20:46:32 DEBUG    destroy    webview:shutdown:332 Shutting down
<qutebrowser.browser.webview.WebView tab_id=3 url='https://laverna.cc/app/dropbox.html#access_token=...'>.
20:46:32 DEBUG    modes      tabbedbrowser:on_current_changed:549 Current tab changed, focusing <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/'>
20:46:32 DEBUG    misc       app:on_focus_object_changed:756 Focus object changed: <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/'>
20:46:32 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.hint! (leave reason: tab changed)
20:46:32 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.insert! (leave reason: tab changed)
20:46:32 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.caret! (leave reason: tab changed)
20:46:32 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.passthrough! (leave reason: tab changed)
20:46:32 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 353, in on_window_close_requested
    self.close_tab(widget)
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 253, in close_tab
    self._remove_tab(tab)
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 276, in _remove_tab
    tab))
ValueError: tab <qutebrowser.browser.webview.WebView tab_id=3 url='https://laverna.cc/app/dropbox.html#access_token=...'> is not contained in TabbedWidget!
```

**Comment by The-Compiler** [comment]
I can't reproduce this on https://laverna.cc/ so far, but I get hangs/segfaults here on Qt 5.3.2 (Debian Jessie)...

**Comment by The-Compiler** [comment]
Another one with a Google+ auth on v0.4.1:

> On youtube, trying to share a video on g+. It opened a new window for me to type a post; when I clicked submit, it crashed.

config:

```
[general]
startpage = about:blank
auto-save-config = false
editor = vim "{}"
developer-extras = true
new-instance-open-target = window
[completion]
shrink = true
[tabs]
show = multiple
show-favicons = false
indicator-width = 0
title-format = {title}
indicator-padding = 0,0,0,0
[storage]
maximum-pages-in-cache = 10
[hints]
border = 2px solid #657b83
opacity = 1.0
next-regexes = \bnext\b,\bmore\b,\bnewer\b,\b[>→≫]\b,\b(>>|»)\b
[searchengines]
[...]
[colors]
[...]
[fonts]
[...]
```

**Comment by The-Compiler** [comment]
I could reproduce this once on http://laverna.cc/ by already being logged in in dropbox and then requesting auth. But I still can't consistently reproduce it.

Unfortunately that page also likes to segfault:

```
/usr/lib/libpthread.so.0(raise 0x29)[0x7fd613cabc39]
/usr/lib/libpthread.so.0( 0x10d60)[0x7fd613cabd60]
/usr/lib/libQt5WebKit.so.5(JSC::weakClearSlowCase(JSC::WeakImpl*&) 0x3)[0x7fd602443ba3]
/usr/lib/libQt5WebKit.so.5( 0x17bc091)[0x7fd6022fe091]
/usr/lib/libQt5WebKit.so.5( 0x17bc0d0)[0x7fd6022fe0d0]
/usr/lib/libQt5WebKit.so.5( 0x1322539)[0x7fd601e64539]
/usr/lib/libQt5WebKit.so.5( 0x174488c)[0x7fd60228688c]
/usr/lib/libQt5WebKit.so.5( 0x1744caf)[0x7fd602286caf]
/usr/lib/libQt5WebKit.so.5( 0xaefabd)[0x7fd601631abd]
/usr/lib/libQt5WebKit.so.5( 0xaefca8)[0x7fd601631ca8]
/usr/lib/libQt5WebKit.so.5( 0xae9a0c)[0x7fd60162ba0c]
/usr/lib/libQt5WebKit.so.5( 0xae9a60)[0x7fd60162ba60]
/usr/lib/libpthread.so.0( 0x6579)[0x7fd613ca1579]
/usr/lib/libpthread.so.0( 0x7658)[0x7fd613ca2658]
/usr/lib/libc.so.6(clone 0x6d)[0x7fd6139e013d]
```

The reporter can reproduce it even with the default config, but *not* with `--temp-basedir`. I'm guessing it has something to do with already being logged into dropbox and then requesting auth.

**Comment by The-Compiler** [comment]
Yep, I can also reproduce it with `--temp-basedir` when logging into Dropbox first.

I added some logging:

```patch
diff --git a/qutebrowser/mainwindow/tabbedbrowser.py b/qutebrowser/mainwindow/tabbedbrowser.py
index dc6d3df..3da6eda 100644
--- a/qutebrowser/mainwindow/tabbedbrowser.py
+++ b/qutebrowser/mainwindow/tabbedbrowser.py
@@ -270,6 +270,7 @@ class TabbedBrowser(tabwidget.TabWidget):
         Args:
             tab: The QWebView to be closed.
         """
+        log.webview.debug("Removing tab {!r}".format(tab))
         idx = self.indexOf(tab)
         if idx == -1:
             raise ValueError("tab {} is not contained in TabbedWidget!".format(
@@ -350,6 +351,7 @@ class TabbedBrowser(tabwidget.TabWidget):
     @pyqtSlot(webview.WebView)
     def on_window_close_requested(self, widget):
         """Close a tab with a widget given."""
+        log.webview.debug("Window close requested for {!r}".format(widget))
         self.close_tab(widget)
 
     @pyqtSlot('QUrl', bool)
```

And it seems like `on_window_close_requested` is called twice:

```
07:45:54 DEBUG    webview    tabbedbrowser:on_window_close_requested:354 Window close requested for <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/dropbox.html#state=...&error_description=The+user+chos…'>
07:45:54 DEBUG    webview    tabbedbrowser:_remove_tab:273 Removing tab <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/dropbox.html#state=...&error_description=The+user+chos…'>
07:45:54 DEBUG    destroy    webview:shutdown:332 Shutting down <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/dropbox.html#state=...&error_description=The+user+chos…'>.
07:45:54 DEBUG    modes      tabbedbrowser:on_current_changed:551 Current tab changed, focusing <qutebrowser.browser.webview.WebView tab_id=1 url='https://laverna.cc/app/'>
07:45:54 DEBUG    misc       app:on_focus_object_changed:764 Focus object changed: <qutebrowser.browser.webview.WebView tab_id=1 url='https://laverna.cc/app/'>
07:45:54 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.hint! (leave reason: tab changed)
[...]
07:45:54 DEBUG    webview    tabbedbrowser:on_window_close_requested:354 Window close requested for <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/dropbox.html#state=...&error_description=The+user+chos…'>
07:45:54 DEBUG    webview    tabbedbrowser:_remove_tab:273 Removing tab <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/dropbox.html#state=...&error_description=The+user+chos…'>
07:45:54 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 355, in on_window_close_requested
    self.close_tab(widget)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 253, in close_tab
    self._remove_tab(tab)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 277, in _remove_tab
    tab))
ValueError: tab <qutebrowser.browser.webview.WebView tab_id=2 url='https://laverna.cc/app/dropbox.html#state=...&error_description=The+user+chos…'> is not contained in TabbedWidget!
```

**Comment by The-Compiler** [comment]
I think I have a reproducer - it looks like at least 3 tabs need to be open for it to happen...

```html
<!DOCTYPE html>
<html>
<body>

<button onclick="openWin()">Open "myWindow"</button>
<button onclick="closeWin()">Close "myWindow"</button>

<script>
var myWindow;

function openWin() {
    myWindow = window.open("", "myWindow", "width=200, height=100");
}

function closeWin() {
    myWindow.close();
    myWindow.close();
}
</script>

</body>
</html>
```

```gherkin
    Scenario: Closing a tab
        When I open about:blank
        And I open data/tabclose.html in a new tab
        And I run :hint
        And I run :follow-hint a
        And I run :tab-focus 2
        And I run :hint
        And I run :follow-hint s
        Then no crash should happen
```
