### ISSUE TITLE
Handle not being able to set runtime dir permissions correctly

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#971]
QStandardPaths can be unable to adjust permissions for the runtime directory.

This should probably be handled more gracefully.
## Exception

```
ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.4.0', 'gui_scripts', 'qutebrowser')()
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/qutebrowser.py", line 149, in main
    return app.run(args)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/app.py", line 96, in run
    server = ipc.send_or_listen(args)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/misc/ipc.py", line 491, in send_or_listen
    socketname = _get_socketname(args.basedir)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/misc/ipc.py", line 67, in _get_socketname
    target_dir = standarddir.runtime()
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/utils/standarddir.py", line 56, in runtime
    return _get(QStandardPaths.RuntimeLocation)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/utils/standarddir.py", line 134, in _get
    path = _writable_location(typ)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.4.0-py3.4.egg/qutebrowser/utils/standarddir.py", line 69, in _writable_location
    raise ValueError("QStandardPaths returned an empty value!")
ValueError: QStandardPaths returned an empty value!
```
## Possible causes
- AppArmor is used and misconfigured (see 5130be449576068572ad156240695e92628cb042): `QStandardPaths::writableLocation(QStandardPaths::StandardLocation):144 QStandardPaths: wrong permissions on runtime directory /run/user/1000`
- `/tmp` is picked up for some reason: `QStandardPaths: wrong ownership on runtime directory /tmp/, 0 instead of 1000`
- `QStandardPaths: error creating runtime directory /tmp/runtime-damien: File exists`
- `QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0` (3 reports, maybe when running qutebrowser via sudo?)

**Comment by The-Compiler** [comment]
Another case of this involving `sudo`:

`"WARNING: QStandardPaths: wrong ownership on runtime directory /run/user/0, 0 instead of 1000"`

> it seems to be complaining that I don't have ownership of /run/user/0 as a non-root user. When I changed the ownership of that folder to the user I su'd into, it made the crash go away. Also it doesn't crash if I launch the program as root. If this is only an error on my part then I apologize for throwing you off. Right now I am logged in as root but I used su to get into a subshell of a normal user, and from there typed $> qutebrowser
> I would think that it would look for the corresponding folder to my user id (1000) and not to root's id, but I'm just speculating...

**Comment by The-Compiler** [comment]
I also got 3 reports with `QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0` - I'm guessing that's also when running qutebrowser via sudo.

**Comment by The-Compiler** [comment]
Anothe rone: `QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/tmp/.runtime-r3lgar', please create it with 0700 permissions.`

**Comment by The-Compiler** [comment]
An easy way to test this is apparently running qutebrowser via `systemd-nspawn`.
